### ISSUE TITLE
NullPointerException from Gauge in LLRealtimeSegmentDataManager Due to Race Condition

### ISSUE THREAD

**Issue by ankitsultana** [apache/pinot#10010]
Saw this in one of our production tables.

```
2022-12-19 23:09:37.915 [HelixTaskExecutor-message_handle_thread] INFO  table_name_REALTIME-RealtimeTableDataManager  - Closed segment: table_name__414__311__20221219T2257Z of table: table_name_REALTIME
2022-12-19 23:09:37.915 [table_name__414__312__20221219T2309Z] ERROR o.a.p.c.d.m.r.LLRealtimeSegmentDataManager_table_name__414__312__20221219T2309Z  - Exception while in work
java.lang.NullPointerException: null
        at org.apache.pinot.common.metrics.AbstractMetrics.setValueOfGauge(AbstractMetrics.java:342)
        at org.apache.pinot.common.metrics.AbstractMetrics.setValueOfTableGauge(AbstractMetrics.java:285)
        at org.apache.pinot.core.data.manager.realtime.LLRealtimeSegmentDataManager.consumeLoop(LLRealtimeSegmentDataManager.java:430)
        at org.apache.pinot.core.data.manager.realtime.LLRealtimeSegmentDataManager$PartitionConsumer.run(LLRealtimeSegmentDataManager.java:598)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by ankitsultana** [comment]
This edge case can happen when a realtime segment does a "Consuming to Online" transition which calls `LLRealtimeSegmentDataManager::destroy`, and the next segment for the same partition is assigned to the same server. In between the `containsKey` check in `AbstractMetrics` and the `get()` on the `_gaugeValues` map, the thread that does the  destroy will remove the key from the map causing a NPE in the new segment's consumer thread.

There are multiple issues here:

1. `AbstractMetrics` has a unsafe access pattern. Between when `containsKey` and `get` are called, a competing thread may remove that metric causing a NullPointerException which we saw above.
2. Even if we were to fix that, I am not sure how we guarantee the correctness of metrics.

At a very minimum, ingestion shouldn't be impacted due to metrics which is the case right now. I raised #10022 which should fix that.

---

Just so there's no confusion, this is the line where the exception is thrown. Our internal fork is a few months old.

<img width="519" alt="image" src="https://user-images.githubusercontent.com/8644710/209063451-1c096942-f62a-43ad-82ef-659efde6f083.png">
