### ISSUE TITLE
[Flaky test] ForwardIndexHandlerTest.testEnableDictionaryForMultipleColumns

### ISSUE THREAD

**Issue by Jackie-Jiang** [apache/pinot#10365]
Failure run:
https://github.com/apache/pinot/actions/runs/4307933808/jobs/7513601262

Failure message:
```
Error:  org.apache.pinot.segment.local.segment.index.loader.ForwardIndexHandlerTest.testEnableDictionaryForMultipleColumns  Time elapsed: 0.014 s  <<< FAILURE!
java.lang.IllegalStateException: Cannot regenerate the dictionary for column DIM_RAW_SV_FORWARD_INDEX_DISABLED_INTEGER with forward index disabled. Please refresh or back-fill the data to add back the forward index
	at com.google.common.base.Preconditions.checkState(Preconditions.java:444)
	at org.apache.pinot.segment.local.segment.index.loader.ForwardIndexHandler.computeOperations(ForwardIndexHandler.java:286)
	at org.apache.pinot.segment.local.segment.index.loader.ForwardIndexHandler.updateIndices(ForwardIndexHandler.java:118)
	at org.apache.pinot.segment.local.segment.index.loader.ForwardIndexHandlerTest.testEnableDictionaryForMultipleColumns(ForwardIndexHandlerTest.java:1214)
```

**Comment by Jackie-Jiang** [comment]
@vvivekiyer @somandal Can you help take a look?

**Comment by somandal** [comment]
@Jackie-Jiang I will take a look and fix this. thanks for bringing it up

**Comment by somandal** [comment]
@Jackie-Jiang have a PR open with a fix for this issue: https://github.com/apache/pinot/pull/10366
please take a look when you get a chance. Thanks!
