### ISSUE TITLE
Support string comparison in FilterConfig

### ISSUE THREAD

**Issue by UOETianleZhang** [apache/pinot#10529]
Based on our filterConfig doc, we should be able to support both numerical comparison and string comparison as conditions of filtering during data ingestion: https://docs.pinot.apache.org/developers/advanced/ingestion-level-transformations#filtering.

**Description**

According to the [filterConfig documentation](https://docs.pinot.apache.org/developers/advanced/ingestion-level-transformations#filtering), Pinot should support both numerical and string comparisons as filtering conditions during data ingestion. However, while trying to onboard a real-time table, we discovered that string comparison is not actually supported.

**Issue Details**

When using the filterConfig `statusInt != 1 OR videoEngagementType != 'VIDEO_VIEWED'`, the Pinot server throws a `NumberFormatException` exception, as shown below:
```
Caused by: java.lang.NumberFormatException: For input string: xxx
```
Upon further investigation, we found that the issue stems from the fact that the "!=" operator is interpreted as "notEquals()" by the SqlParser. The problem is that we only have a corresponding Scala function for "notEquals()" that accepts doubles as its arguments. ([code linke](https://github.com/apache/pinot/blob/2cd03495ffe64a790069cc35c9711d4b4ccc496b/pinot-common/src/main/java/org/apache/pinot/common/function/scalar/ComparisonFunctions.java#L52)) Consequently, the Pinot server attempts to convert the string column to a double, causing the exception.

**Proposed Solutions**

To resolve this issue, we can consider the following options:

1. Enable function overloading, allowing "notEquals()" to accept different argument types.
2. Modify the "notEquals()" function to distinguish the input type and handle both numerical and string cases correctly.

**Comment by UOETianleZhang** [comment]
Full server error log:
```
2023/04/03 00:00:02.595 ERROR [LLRealtimeSegmentDataManager_RomaVideoAdsAction__20__3__20230402T0030Z] [RomaVideoAdsAction__20__3__20230402T0030Z] [pinot-server] [] Caught exception while transforming the record: org.apache.pinot.spi.stream.StreamDataDecoderResult@7f7c6f29
java.lang.RuntimeException: Caught exception while executing filter function: statusInt != 1 OR videoEngagementType != 'VIDEO_VIEWED' for record: {
  "fieldToValueMap" : {
    "videoAdsCount" : null,
    "cost" : 0.0,
    "headerTime" : 1680479940000,
    "mobileHeader" : {
      "appMarketingVersion" : null,
      "appVersion" : "4.1.789.1",
      "appState" : null,
      "osVersion" : "31",
      "appVendorVersion" : null,
      "isAdTrackingLimited" : "false",
      "appVendorVersionShort" : null,
      "vendorId" : null,
      "deviceModel" : "Xiaomi_M2102J20SG",
      "osName" : "Android OS",
      "connectionType" : "WIFI",
      "advertiserId" : null
    },
    "statusInt" : 1,
    "osName" : "Android OS",
    "campaigntype" : null,
    "videoEngagementType" : "FIRST_QUARTILE",
    "campaignAdFormat" : "SINGLE_VIDEO",
    "header" : {
      "server" : "lva1-app68530",
      "clientGlobalSequenceNumber" : null,
      "instance" : null,
      "applicationViewerUrn" : null,
      "csUserUrn" : null,
      "clientTopicLocalSequenceNumber" : null,
      "clientMonitoringInstanceEventNumber" : null,
      "requestId" : 480204775,
      "testSegmentId" : null,
      "impersonatorId" : null,
      "pageInstance" : null,
      "clientMonitoringInstanceId" : null,
      "memberId" : 430230835,
      "originSource" : null,
      "appName" : null,
      "traceData" : null,
      "version" : null,
      "viewerUrn" : null,
      "clientApplicationInstance" : null,
      "treeId" : "AAX4YzzVSZjqo3Y415MKwA==",
      "originalClientTime" : null,
      "environment" : "prod-lva1",
      "auditHeader" : {
        "auditVersion" : 1,
        "server" : "lva1-app68530",
        "instance" : "i001",
        "appName" : "tscp-tracking-war",
        "clusterConnectionString" : null,
        "messageId" : "fyl01ddoPGAXlr7UsuwjvQ==",
        "time" : 1680479989633,
        "fabricUrn" : "urn:li:fabric:prod-lva1"
      },
      "viewHierarchy" : null,
      "service" : "tscp-tracking",
      "sessionUrn" : null,
      "guid" : "82sJ/pOuSvlI9AsFcwV0/g==",
      "testId" : null,
      "time" : 1680479989633
    },
    "deviceModel" : "Xiaomi_M2102J20SG",
    "channelId" : 3000
  },
  "nullValueFields" : [ ]
}
	at org.apache.pinot.segment.local.recordtransformer.FilterTransformer.transform(FilterTransformer.java:66) ~[pinot-segment-local-0.13.0-dev-868.jar:0.13.0-dev-868-0362ad369db15b696b733038d16f3a129585b660]
	at org.apache.pinot.segment.local.recordtransformer.CompositeTransformer.transform(CompositeTransformer.java:90) ~[pinot-segment-local-0.13.0-dev-868.jar:0.13.0-dev-868-0362ad369db15b696b733038d16f3a129585b660]
	at org.apache.pinot.segment.local.segment.creator.TransformPipeline.processPlainRow(TransformPipeline.java:97) ~[pinot-segment-local-0.13.0-dev-868.jar:0.13.0-dev-868-0362ad369db15b696b733038d16f3a129585b660]
	at org.apache.pinot.segment.local.segment.creator.TransformPipeline.processRow(TransformPipeline.java:92) ~[pinot-segment-local-0.13.0-dev-868.jar:0.13.0-dev-868-0362ad369db15b696b733038d16f3a129585b660]
	at org.apache.pinot.core.data.manager.realtime.LLRealtimeSegmentDataManager.processStreamEvents(LLRealtimeSegmentDataManager.java:575) [pinot-core-0.13.0-dev-868.jar:0.13.0-dev-868-0362ad369db15b696b733038d16f3a129585b660]
	at org.apache.pinot.core.data.manager.realtime.LLRealtimeSegmentDataManager.consumeLoop(LLRealtimeSegmentDataManager.java:449) [pinot-core-0.13.0-dev-868.jar:0.13.0-dev-868-0362ad369db15b696b733038d16f3a129585b660]
	at org.apache.pinot.core.data.manager.realtime.LLRealtimeSegmentDataManager$PartitionConsumer.run(LLRealtimeSegmentDataManager.java:647) [pinot-core-0.13.0-dev-868.jar:0.13.0-dev-868-0362ad369db15b696b733038d16f3a129585b660]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.RuntimeException: Caught exception while executing function: notEquals(videoEngagementType,'VIDEO_VIEWED')
	at org.apache.pinot.segment.local.function.InbuiltFunctionEvaluator$FunctionExecutionNode.execute(InbuiltFunctionEvaluator.java:231) ~[pinot-segment-local-0.13.0-dev-868.jar:0.13.0-dev-868-0362ad369db15b696b733038d16f3a129585b660]
	at org.apache.pinot.segment.local.function.InbuiltFunctionEvaluator$OrExecutionNode.execute(InbuiltFunctionEvaluator.java:149) ~[pinot-segment-local-0.13.0-dev-868.jar:0.13.0-dev-868-0362ad369db15b696b733038d16f3a129585b660]
	at org.apache.pinot.segment.local.function.InbuiltFunctionEvaluator.evaluate(InbuiltFunctionEvaluator.java:106) ~[pinot-segment-local-0.13.0-dev-868.jar:0.13.0-dev-868-0362ad369db15b696b733038d16f3a129585b660]
	at org.apache.pinot.segment.local.recordtransformer.FilterTransformer.transform(FilterTransformer.java:59) ~[pinot-segment-local-0.13.0-dev-868.jar:0.13.0-dev-868-0362ad369db15b696b733038d16f3a129585b660]
	... 7 more
Caused by: java.lang.NumberFormatException: For input string: "FIRST_QUARTILE"
	at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054) ~[?:?]
	at jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:?]
	at java.lang.Double.parseDouble(Double.java:543) ~[?:?]
	at org.apache.pinot.common.utils.PinotDataType$11.toDouble(PinotDataType.java:622) ~[pinot-common-0.13.0-dev-868.jar:0.13.0-dev-868-0362ad369db15b696b733038d16f3a129585b660]
	at org.apache.pinot.common.utils.PinotDataType$8.convert(PinotDataType.java:478) ~[pinot-common-0.13.0-dev-868.jar:0.13.0-dev-868-0362ad369db15b696b733038d16f3a129585b660]
	at org.apache.pinot.common.utils.PinotDataType$8.convert(PinotDataType.java:426) ~[pinot-common-0.13.0-dev-868.jar:0.13.0-dev-868-0362ad369db15b696b733038d16f3a129585b660]
	at org.apache.pinot.common.function.FunctionInvoker.convertTypes(FunctionInvoker.java:110) ~[pinot-common-0.13.0-dev-868.jar:0.13.0-dev-868-0362ad369db15b696b733038d16f3a129585b660]
	at org.apache.pinot.segment.local.function.InbuiltFunctionEvaluator$FunctionExecutionNode.execute(InbuiltFunctionEvaluator.java:228) ~[pinot-segment-local-0.13.0-dev-868.jar:0.13.0-dev-868-0362ad369db15b696b733038d16f3a129585b660]
	at org.apache.pinot.segment.local.function.InbuiltFunctionEvaluator$OrExecutionNode.execute(InbuiltFunctionEvaluator.java:149) ~[pinot-segment-local-0.13.0-dev-868.jar:0.13.0-dev-868-0362ad369db15b696b733038d16f3a129585b660]
	at org.apache.pinot.segment.local.function.InbuiltFunctionEvaluator.evaluate(InbuiltFunctionEvaluator.java:106) ~[pinot-segment-local-0.13.0-dev-868.jar:0.13.0-dev-868-0362ad369db15b696b733038d16f3a129585b660]
	at org.apache.pinot.segment.local.recordtransformer.FilterTransformer.transform(FilterTransformer.java:59) ~[pinot-segment-local-0.13.0-dev-868.jar:0.13.0-dev-868-0362ad369db15b696b733038d16f3a129585b660]
	... 7 more
```

**Comment by Jackie-Jiang** [comment]
Related to #9641 
As the long term fix, we need to support function overloading
For the short term workaround, you may add a scalar function `notEqualsStr(String v1, String v2)` and explicitly use it to filter the values (`notEqualsStr(type, 'VIDEO')`)

**Comment by saurabhd336** [comment]
`statusInt != 1 OR strCmp(type, 'VIDEO') = 0` can be used as an alternative

**Comment by UOETianleZhang** [comment]
Sounds like strcmp can be a perfect short term solution and we can directly work on the long term fix.
