### ISSUE TITLE
[multistage]: IllegalStateException for the numeric comparison in WHERE clause

### ISSUE THREAD

**Issue by abhioncbr** [apache/pinot#10661]
We are ignoring the below numeric [comparison query](https://github.com/apache/pinot/blob/master/pinot-query-runtime/src/test/resources/queries/Comparisons.json#L126) in the test because it fails with the `IllegalStateException`

`SELECT * FROM {tbl} WHERE i1 >= i2`

Here is the stacktrace
```
java.lang.IllegalStateException: null
	at org.apache.pinot.core.operator.dociditerators.ExpressionScanDocIdIterator.processProjectionBlock(ExpressionScanDocIdIterator.java:207) ~[classes/:?]
	at org.apache.pinot.core.operator.dociditerators.ExpressionScanDocIdIterator.next(ExpressionScanDocIdIterator.java:89) ~[classes/:?]
	at org.apache.pinot.core.operator.DocIdSetOperator.getNextBlock(DocIdSetOperator.java:75) ~[classes/:?]
	at org.apache.pinot.core.operator.DocIdSetOperator.getNextBlock(DocIdSetOperator.java:39) ~[classes/:?]
	at org.apache.pinot.core.operator.BaseOperator.nextBlock(BaseOperator.java:43) ~[classes/:?]
	at org.apache.pinot.core.operator.ProjectionOperator.getNextBlock(ProjectionOperator.java:70) ~[classes/:?]
	at org.apache.pinot.core.operator.ProjectionOperator.getNextBlock(ProjectionOperator.java:37) ~[classes/:?]
	at org.apache.pinot.core.operator.BaseOperator.nextBlock(BaseOperator.java:43) ~[classes/:?]
	at org.apache.pinot.core.operator.query.SelectionOnlyOperator.getNextBlock(SelectionOnlyOperator.java:97) ~[classes/:?]
	at org.apache.pinot.core.operator.query.SelectionOnlyOperator.getNextBlock(SelectionOnlyOperator.java:41) ~[classes/:?]
	at org.apache.pinot.core.operator.BaseOperator.nextBlock(BaseOperator.java:43) ~[classes/:?]
	at org.apache.pinot.core.operator.combine.BaseSingleBlockCombineOperator.processSegments(BaseSingleBlockCombineOperator.java:102) ~[classes/:?]
	at org.apache.pinot.core.operator.combine.BaseCombineOperator$1.runJob(BaseCombineOperator.java:107) [classes/:?]
	at org.apache.pinot.core.util.trace.TraceRunnable.run(TraceRunnable.java:40) [classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
09:38:17.739 ERROR [BaseCombineOperator] [query_worker_on_55282_port-1-thread-1] Caught exception while processing query: QueryContext{_tableName='numerics_comp_tbl_OFFLINE', _subquery=null, _selectExpressions=[i1, i2, ts], _aliasList=[null, null, null], _filter=minus(i1,i2) >= '0', _groupByExpressions=null, _havingFilter=null, _orderByExpressions=null, _limit=10000000, _offset=0, _queryOptions={pinot.query.runner.broker.request.timeout.ms=10000, timeoutMs=10000, pinot.query.runner.broker.request.id=4422342673632965003}, _expressionOverrideHints={}, _explain=false}
java.lang.IllegalStateException: null
	at org.apache.pinot.core.operator.dociditerators.ExpressionScanDocIdIterator.processProjectionBlock(ExpressionScanDocIdIterator.java:207) ~[classes/:?]
	at org.apache.pinot.core.operator.dociditerators.ExpressionScanDocIdIterator.next(ExpressionScanDocIdIterator.java:89) ~[classes/:?]
	at org.apache.pinot.core.operator.DocIdSetOperator.getNextBlock(DocIdSetOperator.java:75) ~[classes/:?]
	at org.apache.pinot.core.operator.DocIdSetOperator.getNextBlock(DocIdSetOperator.java:39) ~[classes/:?]
	at org.apache.pinot.core.operator.BaseOperator.nextBlock(BaseOperator.java:43) ~[classes/:?]
	at org.apache.pinot.core.operator.ProjectionOperator.getNextBlock(ProjectionOperator.java:70) ~[classes/:?]
	at org.apache.pinot.core.operator.ProjectionOperator.getNextBlock(ProjectionOperator.java:37) ~[classes/:?]
	at org.apache.pinot.core.operator.BaseOperator.nextBlock(BaseOperator.java:43) ~[classes/:?]
	at org.apache.pinot.core.operator.query.SelectionOnlyOperator.getNextBlock(SelectionOnlyOperator.java:97) ~[classes/:?]
	at org.apache.pinot.core.operator.query.SelectionOnlyOperator.getNextBlock(SelectionOnlyOperator.java:41) ~[classes/:?]
	at org.apache.pinot.core.operator.BaseOperator.nextBlock(BaseOperator.java:43) ~[classes/:?]
	at org.apache.pinot.core.operator.combine.BaseSingleBlockCombineOperator.processSegments(BaseSingleBlockCombineOperator.java:102) ~[classes/:?]
	at org.apache.pinot.core.operator.combine.BaseCombineOperator$1.runJob(BaseCombineOperator.java:107) [classes/:?]
	at org.apache.pinot.core.util.trace.TraceRunnable.run(TraceRunnable.java:40) [classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

cc @ankitsultana @walterddr

**Comment by abhioncbr** [comment]
We can close this issue. Thanks.
