### ISSUE TITLE
[multistage] Window Function Error with aggregation function

### ISSUE THREAD

**Issue by siddharthteotia** [apache/pinot#10677]
Creating this to track an issue received in user feedback. Yet to take a look

Query

```
SET useMultistageEngine=true;
select orderID, max(cast(updatedTime as DOUBLE)) over(partition by orderID) from foodOrderFact;
```

Broker Exception

```
[
  {
    "message": "QueryExecutionError:\njava.lang.RuntimeException: Received error query execution result block: {1000=Incompatible selection result data schema:  Expected: [orderID(STRING),EXPR$1(DOUBLE)]. Actual: [max_cast(updatedTime,'DOUBLE')(DOUBLE)]\njava.lang.IllegalStateException: Incompatible selection result data schema:  Expected: [orderID(STRING),EXPR$1(DOUBLE)]. Actual: [max_cast(updatedTime,'DOUBLE')(DOUBLE)]\n\tat org.apache.pinot.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:444)\n\tat org.apache.pinot.query.runtime.operator.LeafStageTransferableBlockOperator.composeAggregationTransferableBlock(LeafStageTransferableBlockOperator.java:185)\n\tat org.apache.pinot.query.runtime.operator.LeafStageTransferableBlockOperator.composeTransferableBlock(LeafStageTransferableBlockOperator.java:125)",
    "errorCode": 200
  }
]
```

Server Exception:

```
(OpChain{7_1}): Completed erroneously (7_1) Queued Count: 2, Executing Time: 0ms, Queued Time: 16ms {1000=Incompatible selection result data schema:  Expected: [orderID(STRING),EXPR$1(DOUBLE)]. Actual: [max_cast(updatedTime,'DOUBLE')(DOUBLE)]
java.lang.IllegalStateException: Incompatible selection result data schema:  Expected: [orderID(STRING),EXPR$1(DOUBLE)]. Actual: [max_cast(updatedTime,'DOUBLE')(DOUBLE)]
    at org.apache.pinot.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:444)
    at org.apache.pinot.query.runtime.operator.LeafStageTransferableBlockOperator.composeAggregationTransferableBlock(LeafStageTransferableBlockOperator.java:185)
    at org.apache.pinot.query.runtime.operator.LeafStageTransferableBlockOperator.composeTransferableBlock(LeafStageTransferableBlockOperator.java:125)
    at org.apache.pinot.query.runtime.operator.LeafStageTransferableBlockOperator.getNextBlock(LeafStageTransferableBlockOperator.java:97)}
```

**Comment by siddharthteotia** [comment]
cc @somandal  - please comment here once for me to assign to you

**Comment by somandal** [comment]
I can take a look at this issue

**Comment by somandal** [comment]
I've requested more information from the user. Need details about the schema for the fields they used and the relevant index configs. User mentioned the type for updatedTime is TIMESTAMP.

Tried a few queries (not using TIMESTAMP but using CAST) which seem to work:

```
SET useMultistageEngine=true;
SELECT col1, col2, MAX(CAST(col3 AS DOUBLE)) OVER(PARTITION BY col1)  from TestTable WHERE col3 = 1000 OR col3 = 1024 AND col1 < 2845947 LIMIT 10000
```
In the above col3 is a LONG type column.

**Comment by somandal** [comment]
The user mentioned they are using release 0.12.1, which doesn't seem to have window function support based on release notes: https://docs.pinot.apache.org/basics/releases/0.12.0-1 (need to check more on this). That might explain the weird cast issues.

**Comment by somandal** [comment]
The user confirmed that this issue is fixed on master (i.e. window support for this query is working as expected). This issue can be closed
