### ISSUE TITLE
[multistage] Pinot connection doesn't handle join routing parsing

### ISSUE THREAD

**Issue by walterddr** [apache/pinot#10688]
see:
```
09:57:38.796 ERROR [Connection] [main] Cannot parse table name from query: select D_YEAR, S_NATION, P_CATEGORY, sum(LO_REVENUE - LO_SUPPLYCOST) as profit
from lineorder, dates, customer, supplier, part where LO_CUSTKEY = C_CUSTKEY
and LO_SUPPKEY = S_SUPPKEY and LO_PARTKEY = P_PARTKEY and LO_ORDERDATE = D_DATEKEY
and C_REGION = 'AMERICA' and S_REGION = 'AMERICA' and (D_YEAR = 1997 or D_YEAR = 1998)
and (P_MFGR = 'MFGR#1' or P_MFGR = 'MFGR#2') group by D_YEAR, S_NATION, P_CATEGORY
order by D_YEAR, S_NATION, P_CATEGORY;

java.lang.IllegalStateException: Unsupported join type: COMMA
	at org.apache.pinot.sql.parsers.CalciteSqlParser.compileToJoin(CalciteSqlParser.java:552) ~[classes/:?]
	at org.apache.pinot.sql.parsers.CalciteSqlParser.compileToDataSource(CalciteSqlParser.java:528) ~[classes/:?]
	at org.apache.pinot.sql.parsers.CalciteSqlParser.compileSqlNodeToPinotQuery(CalciteSqlParser.java:475) ~[classes/:?]
	at org.apache.pinot.sql.parsers.CalciteSqlParser.compileToPinotQuery(CalciteSqlParser.java:244) ~[classes/:?]
	at org.apache.pinot.sql.parsers.CalciteSqlParser.compileToPinotQuery(CalciteSqlParser.java:239) ~[classes/:?]
	at org.apache.pinot.sql.parsers.CalciteSqlCompiler.compileToBrokerRequest(CalciteSqlCompiler.java:32) ~[classes/:?]
	at org.apache.pinot.client.Connection.resolveTableName(Connection.java:189) [classes/:?]
	at org.apache.pinot.client.Connection.execute(Connection.java:119) [classes/:?]
	at org.apache.pinot.client.Connection.execute(Connection.java:94) [classes/:?]
	at org.apache.pinot.integration.tests.SSBQueryIntegrationTest.testQueriesValidateAgainstH2(SSBQueryIntegrationTest.java:112) [test-classes/:?]
	at org.apache.pinot.integration.tests.SSBQueryIntegrationTest.testSSBQueries(SSBQueryIntegrationTest.java:106) [test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108) [testng-6.11.jar:?]
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661) [testng-6.11.jar:?]
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869) [testng-6.11.jar:?]
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193) [testng-6.11.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126) [testng-6.11.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109) [testng-6.11.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:744) [testng-6.11.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:602) [testng-6.11.jar:?]
```

this is b/c the Connection code path doesn't go through the v2 engine (which only calls `CalciteSqlParser` for leaf stages, not `CalciteSqlCompiler` for the overall query

**Comment by walterddr** [comment]
solution:

instead of making `Connection.resolveTableName` call into 
```
  private static String resolveTableName(String query) {
    try {
      return CalciteSqlCompiler.compileToBrokerRequest(query).querySource.tableName;
      ...
```
we should switch to 
```
    SqlNode sqlNode = CalciteSqlParser.extractSqlNodeAndOptions(query);
    return CalciteSqlParser.extractTableNamesFromNode(sqlNode);
```

**Comment by abhioncbr** [comment]
Please assign it to me. Thanks.

**Comment by abhioncbr** [comment]
Question:
`extractTableNamesFromNode` returns the List of the table names; what should we do for `_brokerSelector.selectBroker`? Since the current implementation returns the broker address on which the table is hosted, but in case of a JOIN query, tables can be hosted on different brokers. right?

For testing purpose, I passed the first table name to get the broker address but later the query execution failed with following error
```
org.apache.pinot.spi.utils.retry.AttemptsExceededException: Operation failed after 3 attempts
	at org.apache.pinot.spi.utils.retry.BaseRetryPolicy.attempt(BaseRetryPolicy.java:65) ~[classes/:?]
	at org.apache.pinot.common.utils.fetcher.BaseSegmentFetcher.fetchSegmentToLocal(BaseSegmentFetcher.java:73) ~[classes/:?]
	at org.apache.pinot.common.utils.fetcher.SegmentFetcherFactory.fetchSegmentToLocalInternal(SegmentFetcherFactory.java:157) ~[classes/:?]
	at org.apache.pinot.common.utils.fetcher.SegmentFetcherFactory.fetchSegmentToLocal(SegmentFetcherFactory.java:151) ~[classes/:?]
	at org.apache.pinot.common.utils.fetcher.SegmentFetcherFactory.fetchAndDecryptSegmentToLocalInternal(SegmentFetcherFactory.java:198) ~[classes/:?]
	at org.apache.pinot.common.utils.fetcher.SegmentFetcherFactory.fetchAndDecryptSegmentToLocal(SegmentFetcherFactory.java:186) ~[classes/:?]
	at org.apache.pinot.core.data.manager.BaseTableDataManager.downloadAndDecrypt(BaseTableDataManager.java:565) ~[classes/:?]
	at org.apache.pinot.core.data.manager.BaseTableDataManager.downloadSegmentFromDeepStore(BaseTableDataManager.java:528) ~[classes/:?]
	at org.apache.pinot.core.data.manager.BaseTableDataManager.downloadSegment(BaseTableDataManager.java:512) ~[classes/:?]
	at org.apache.pinot.core.data.manager.BaseTableDataManager.addOrReplaceSegment(BaseTableDataManager.java:472) ~[classes/:?]
	at org.apache.pinot.server.starter.helix.HelixInstanceDataManager.addOrReplaceSegment(HelixInstanceDataManager.java:482) ~[classes/:?]
	at org.apache.pinot.server.starter.helix.SegmentOnlineOfflineStateModelFactory$SegmentOnlineOfflineStateModel.onBecomeOnlineFromOffline(SegmentOnlineOfflineStateModelFactory.java:166) [classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.apache.helix.messaging.handling.HelixStateTransitionHandler.invoke(HelixStateTransitionHandler.java:350) [helix-core-1.0.4.jar:1.0.4]
	at org.apache.helix.messaging.handling.HelixStateTransitionHandler.handleMessage(HelixStateTransitionHandler.java:278) [helix-core-1.0.4.jar:1.0.4]
	at org.apache.helix.messaging.handling.HelixTask.call(HelixTask.java:97) [helix-core-1.0.4.jar:1.0.4]
	at org.apache.helix.messaging.handling.HelixTask.call(HelixTask.java:49) [helix-core-1.0.4.jar:1.0.4]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by walterddr** [comment]
This is a good question for how the routing is handling I would suggest check out here the controller  logic. In https://github.com/apache/pinot/pull/10336 . 

In fact the logic is so generic I think we should factor it to a utility. 
CC @ankitsultana @tibrewalpratik17

**Comment by abhioncbr** [comment]
Yes, I was thinking the same about moving to some utility class.

Right now, the code is sitting in `PinotQueryResource` [getCommonBrokerTenant](https://github.com/apache/pinot/blob/master/pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotQueryResource.java#L272), which requires `tableConfigs` and indirectly `HelixResourceManger`. 

I can give it a shot to move the functionality to some util class.

**Comment by ankitsultana** [comment]
@walterddr : Any approach works for me. Long term though I wanted to move the parsing code out to a separate dedicated module, similar to how Presto has presto-parser.

cc: @Jackie-Jiang for his thoughts as well.

**Comment by Jackie-Jiang** [comment]
I think we need to make sure the broker picked is hosting all the tables within the JOIN, essentially do an intersection of multiple broker lists

**Comment by abhioncbr** [comment]
We can close this issue. Thanks
