### ISSUE TITLE
[multistage] Error with Self Join

### ISSUE THREAD

**Issue by rahul8383** [apache/pinot#10736]
The below query worked with 0.12.1 release but is not working in master branch deployment
Query:
```
SET useMultistageEngine=true;
SELECT   COUNT(fof.orderId) AS numOrdersNew
FROM     foodOrderFact      AS fof
JOIN
         (
                  SELECT   orderId,
                           MAX(CAST(updatedTime AS DOUBLE) ) AS maxUpdatedTime
                  FROM     foodOrderFact
                  GROUP BY (orderId)
         ) AS self
ON       fof.orderId = self.orderId
AND      CAST(fof.updatedTime AS DOUBLE) = self.maxUpdatedTime
WHERE    fof.orderState='NEW'
GROUP BY (cityID, countryID)
```
Exception:
```
Caught exception while processing post request
java.lang.ClassCastException: class org.apache.calcite.sql.SqlSelect cannot be cast to class org.apache.calcite.sql.SqlIdentifier (org.apache.calcite.sql.SqlSelect and org.apache.calcite.sql.SqlIdentifier are in unnamed module of loader 'app')
	at org.apache.pinot.sql.parsers.CalciteSqlParser.extractTableNamesFromNode(CalciteSqlParser.java:175) ~[pinot-all-0.13.0-SNAPSHOT-jar-with-dependencies.jar:0.13.0-SNAPSHOT-b190599cf1ac2a16fc3ab43320dd7fde092dd734]
	at org.apache.pinot.sql.parsers.CalciteSqlParser.extractTableNamesFromNode(CalciteSqlParser.java:159) ~[pinot-all-0.13.0-SNAPSHOT-jar-with-dependencies.jar:0.13.0-SNAPSHOT-b190599cf1ac2a16fc3ab43320dd7fde092dd734]
	at org.apache.pinot.controller.api.resources.PinotQueryResource.getMultiStageQueryResponse(PinotQueryResource.java:176) ~[pinot-all-0.13.0-SNAPSHOT-jar-with-dependencies.jar:0.13.0-SNAPSHOT-b190599cf1ac2a16fc3ab43320dd7fde092dd734]
	at org.apache.pinot.controller.api.resources.PinotQueryResource.executeSqlQuery(PinotQueryResource.java:143) ~[pinot-all-0.13.0-SNAPSHOT-jar-with-dependencies.jar:0.13.0-SNAPSHOT-b190599cf1ac2a16fc3ab43320dd7fde092dd734]
	at org.apache.pinot.controller.api.resources.PinotQueryResource.handlePostSql(PinotQueryResource.java:109) ~[pinot-all-0.13.0-SNAPSHOT-jar-with-dependencies.jar:0.13.0-SNAPSHOT-b190599cf1ac2a16fc3ab43320dd7fde092dd734]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[pinot-all-0.13.0-SNAPSHOT-jar-with-dependencies.jar:0.13.0-SNAPSHOT-b190599cf1ac2a16fc3ab43320dd7fde092dd734]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124) [pinot-all-0.13.0-SNAPSHOT-jar-with-dependencies.jar:0.13.0-SNAPSHOT-b190599cf1ac2a16fc3ab43320dd7fde092dd734]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167) [pinot-all-0.13.0-SNAPSHOT-jar-with-dependencies.jar:0.13.0-SNAPSHOT-b190599cf1ac2a16fc3ab43320dd7fde092dd734]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219) [pinot-all-0.13.0-SNAPSHOT-jar-with-dependencies.jar:0.13.0-SNAPSHOT-b190599cf1ac2a16fc3ab43320dd7fde092dd734]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79) [pinot-all-0.13.0-SNAPSHOT-jar-with-dependencies.jar:0.13.0-SNAPSHOT-b190599cf1ac2a16fc3ab43320dd7fde092dd734]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:475) [pinot-all-0.13.0-SNAPSHOT-jar-with-dependencies.jar:0.13.0-SNAPSHOT-b190599cf1ac2a16fc3ab43320dd7fde092dd734]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:397) [pinot-all-0.13.0-SNAPSHOT-jar-with-dependencies.jar:0.13.0-SNAPSHOT-b190599cf1ac2a16fc3ab43320dd7fde092dd734]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81) [pinot-all-0.13.0-SNAPSHOT-jar-with-dependencies.jar:0.13.0-SNAPSHOT-b190599cf1ac2a16fc3ab43320dd7fde092dd734]
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255) [pinot-all-0.13.0-SNAPSHOT-jar-with-dependencies.jar:0.13.0-SNAPSHOT-b190599cf1ac2a16fc3ab43320dd7fde092dd734]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) [pinot-all-0.13.0-SNAPSHOT-jar-with-dependencies.jar:0.13.0-SNAPSHOT-b190599cf1ac2a16fc3ab43320dd7fde092dd734]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) [pinot-all-0.13.0-SNAPSHOT-jar-with-dependencies.jar:0.13.0-SNAPSHOT-b190599cf1ac2a16fc3ab43320dd7fde092dd734]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) [pinot-all-0.13.0-SNAPSHOT-jar-with-dependencies.jar:0.13.0-SNAPSHOT-b190599cf1ac2a16fc3ab43320dd7fde092dd734]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) [pinot-all-0.13.0-SNAPSHOT-jar-with-dependencies.jar:0.13.0-SNAPSHOT-b190599cf1ac2a16fc3ab43320dd7fde092dd734]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244) [pinot-all-0.13.0-SNAPSHOT-jar-with-dependencies.jar:0.13.0-SNAPSHOT-b190599cf1ac2a16fc3ab43320dd7fde092dd734]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) [pinot-all-0.13.0-SNAPSHOT-jar-with-dependencies.jar:0.13.0-SNAPSHOT-b190599cf1ac2a16fc3ab43320dd7fde092dd734]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234) [pinot-all-0.13.0-SNAPSHOT-jar-with-dependencies.jar:0.13.0-SNAPSHOT-b190599cf1ac2a16fc3ab43320dd7fde092dd734]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684) [pinot-all-0.13.0-SNAPSHOT-jar-with-dependencies.jar:0.13.0-SNAPSHOT-b190599cf1ac2a16fc3ab43320dd7fde092dd734]
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:356) [pinot-all-0.13.0-SNAPSHOT-jar-with-dependencies.jar:0.13.0-SNAPSHOT-b190599cf1ac2a16fc3ab43320dd7fde092dd734]
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:200) [pinot-all-0.13.0-SNAPSHOT-jar-with-dependencies.jar:0.13.0-SNAPSHOT-b190599cf1ac2a16fc3ab43320dd7fde092dd734]
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569) [pinot-all-0.13.0-SNAPSHOT-jar-with-dependencies.jar:0.13.0-SNAPSHOT-b190599cf1ac2a16fc3ab43320dd7fde092dd734]
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549) [pinot-all-0.13.0-SNAPSHOT-jar-with-dependencies.jar:0.13.0-SNAPSHOT-b190599cf1ac2a16fc3ab43320dd7fde092dd734]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```
Schema:
```
{
  "schemaName": "foodOrderFact",
  "dimensionFieldSpecs": [
    {
      "name": "orderID",
      "dataType": "STRING"
    },
    {
      "name": "orderState",
      "dataType": "STRING"
    },
    {
      "name": "cityID",
      "dataType": "LONG"
    },
    {
      "name": "countryID",
      "dataType": "LONG"
    }
  ],
  "metricFieldSpecs": [],
  "dateTimeFieldSpecs": [
    {
      "name": "createdTime",
      "dataType": "TIMESTAMP",
      "format": "1:MILLISECONDS:TIMESTAMP",
      "granularity": "1:MILLISECONDS"
    },
    {
      "name": "updatedTime",
      "dataType": "TIMESTAMP",
      "format": "1:MILLISECONDS:TIMESTAMP",
      "granularity": "1:MILLISECONDS"
    }
  ]
}
```

**Comment by abhioncbr** [comment]
I was trying to determine the reason for the issue and found a minor issue. Raised the PR for the [fix](https://github.com/apache/pinot/pull/10739). Thanks

**Comment by abhioncbr** [comment]
We can close this issue. Thanks

**Comment by navina** [comment]
@walterddr : please close this issue
