### ISSUE TITLE
[multistage]: Fix json data type transform functions 

### ISSUE THREAD

**Issue by abhioncbr** [apache/pinot#10767]
With `json` data type[ support in multistage](https://github.com/apache/pinot/pull/10765), two transform functions related to `json` aren't working as expected.

1. [jsonextractkey](https://docs.pinot.apache.org/configuration-reference/functions/jsonextractkey): Not erroring out but the response  from the example query isn't useful
<img width="1153" alt="Screen Shot 2023-05-14 at 11 52 32 AM" src="https://github.com/apache/pinot/assets/1076944/5556b0f9-37de-484a-b280-a92c50d33cf3">

2. [jsonextractscalar](https://docs.pinot.apache.org/configuration-reference/functions/jsonextractscalar): Erroring out for the example query, 
```
select id, jsonextractscalar(repo, '$.name', 'STRING') AS name
from githubEvents 
WHERE id = 7044874109

(OpChain{12_0_1}): Completed erroneously (12_0_1) Queued Count: 0, Executing Time: 1ms, Queued Time: 0ms {1000=class java.lang.String cannot be cast to class org.apache.pinot.spi.utils.ByteArray (java.lang.String is in module java.base of loader 'bootstrap'; org.apache.pinot.spi.utils.ByteArray is in unnamed module of loader 'app')
java.lang.ClassCastException: class java.lang.String cannot be cast to class org.apache.pinot.spi.utils.ByteArray (java.lang.String is in module java.base of loader 'bootstrap'; org.apache.pinot.spi.utils.ByteArray is in unnamed module of loader 'app')
        at org.apache.pinot.common.utils.DataSchema$ColumnDataType.convert(DataSchema.java:350)
        at org.apache.pinot.query.runtime.operator.LeafStageTransferableBlockOperator.canonicalizeRow(LeafStageTransferableBlockOperator.java:319)
        at org.apache.pinot.query.runtime.operator.LeafStageTransferableBlockOperator.composeDirectTransferableBlock(LeafStageTransferableBlockOperator.java:280)
        at org.apache.pinot.query.runtime.operator.LeafStageTransferableBlockOperator.composeSelectTransferableBlock(LeafStageTransferableBlockOperator.java:242)}
query execution failed
java.lang.RuntimeException: Error executing query: [0]@192.168.2.187:60357 MAIL_RECEIVE(RANDOM_DISTRIBUTED)
└── [1]@192.168.2.187:60381 MAIL_SEND(RANDOM_DISTRIBUTED)->{[0]@192.168.2.187@{60357,60357}|[0]}
   └── [1]@192.168.2.187:60381 PROJECT
      └── [1]@192.168.2.187:60381 FILTER
         └── [1]@192.168.2.187:60381 TABLE SCAN (githubEvents) null

        at org.apache.pinot.query.service.dispatch.QueryDispatcher.submitAndReduce(QueryDispatcher.java:99) ~[pinot-all-0.13.0-SNAPSHOT-jar-with-dependencies.jar:0.13.0-SNAPSHOT-7977aaf9da0456ba94b2e16181bef2c6ce3feb56]
        at org.apache.pinot.broker.requesthandler.MultiStageBrokerRequestHandler.handleRequest(MultiStageBrokerRequestHandler.java:210) ~[pinot-all-0.13.0-SNAPSHOT-jar-with-dependencies.jar:0.13.0-SNAPSHOT-7977aaf9da0456ba94b2e16181bef2c6ce3feb56]
        at org.apache.pinot.broker.requesthandler.MultiStageBrokerRequestHandler.handleRequest(MultiStageBrokerRequestHandler.java:138) ~[pinot-all-0.13.0-SNAPSHOT-jar-with-dependencies.jar:0.13.0-SNAPSHOT-7977aaf9da0456ba94b2e16181bef2c6ce3feb56]
        at org.apache.pinot.broker.requesthandler.BrokerRequestHandler.handleRequest(BrokerRequestHandler.java:47) ~[pinot-all-0.13.0-SNAPSHOT-jar-with-dependencies.jar:0.13.0-SNAPSHOT-7977aaf9da0456ba94b2e16181bef2c6ce3feb56]
        at org.apache.pinot.broker.requesthandler.BrokerRequestHandlerDelegate.handleRequest(BrokerRequestHandlerDelegate.java:104) ~[pinot-all-0.13.0-SNAPSHOT-jar-with-dependencies.jar:0.13.0-SNAPSHOT-7977aaf9da0456ba94b2e16181bef2c6ce3feb56]
        at org.apache.pinot.broker.api.resources.PinotClientRequest.executeSqlQuery(PinotClientRequest.java:232) ~[pinot-all-0.13.0-SNAPSHOT-jar-with-dependencies.jar:0.13.0-SNAPSHOT-7977aaf9da0456ba94b2e16181bef2c6ce3feb56]
        at org.apache.pinot.broker.api.resources.PinotClientRequest.processSqlQueryPost(PinotClientRequest.java:149) ~[pinot-all-0.13.0-SNAPSHOT-jar-with-dependenMay 14, 2023 11:45:35 A.M. io.grpc.internal.ServerCallImpl internalClose
WARNING: Cancelling the stream with status Status{code=INTERNAL, description=Completed without a response, cause=null}
cies.jar:0.13.0-SNAPSHOT-7977aaf9da0456ba94b2e16181bef2c6ce3feb56]
```

I will work on this. Thanks

**Comment by abhioncbr** [comment]
PR to fix the problem https://github.com/apache/pinot/pull/10790

**Comment by abhioncbr** [comment]
With this PR https://github.com/apache/pinot/pull/11048, it's now working.
