### ISSUE TITLE
[flaky test] query with pipeline breaker seems unstable

### ISSUE THREAD

**Issue by walterddr** [apache/pinot#10829]
see: https://github.com/apache/pinot/actions/runs/5147527036/jobs/9268030409

```
2023-06-01T18:30:47.9165106Z [ERROR] org.apache.pinot.query.runtime.queries.ResourceBasedQueriesTest.testQueryTestCasesWithH2[hint_option_queries, SELECT /*+ joinOptions(join_strategy='dynamic_broadcast', is_colocated_by_join_keys='true') */ hint_option_queries_tbl1.num, hint_option_queries_tbl1.name FROM hint_option_queries_tbl1 WHERE hint_option_queries_tbl1.num IN (SELECT hint_option_queries_tbl2.num FROM hint_option_queries_tbl2 WHERE hint_option_queries_tbl2.val IN ('xxx', 'yyy')), SELECT /*+ joinOptions(join_strategy='dynamic_broadcast', is_colocated_by_join_keys='true') */ hint_option_queries_tbl1.num, hint_option_queries_tbl1.name FROM hint_option_queries_tbl1 WHERE hint_option_queries_tbl1.num IN (SELECT hint_option_queries_tbl2.num FROM hint_option_queries_tbl2 WHERE hint_option_queries_tbl2.val IN ('xxx', 'yyy')), null, false](226)  Time elapsed: 0.216 s  <<< FAILURE!
2023-06-01T18:30:47.9166403Z java.lang.RuntimeException: 
2023-06-01T18:30:47.9166782Z Received error query execution result block: {1000=Cancelled by sender with exception: Query was cancelled!
2023-06-01T18:30:47.9167262Z java.lang.RuntimeException: Cancelled by sender with exception: Query was cancelled!
2023-06-01T18:30:47.9167741Z 	at org.apache.pinot.query.mailbox.GrpcSendingMailbox.cancel(GrpcSendingMailbox.java:84)
2023-06-01T18:30:47.9168305Z 	at org.apache.pinot.query.runtime.operator.exchange.BlockExchange.cancel(BlockExchange.java:173)
2023-06-01T18:30:47.9168904Z 	at org.apache.pinot.query.runtime.operator.MailboxSendOperator.cancel(MailboxSendOperator.java:182)
2023-06-01T18:30:47.9169494Z 	at org.apache.pinot.query.runtime.operator.OpChain.cancel(OpChain.java:79)
2023-06-01T18:30:47.9169820Z ...
2023-06-01T18:30:47.9170098Z Caused by: java.lang.InterruptedException: Query was cancelled!
2023-06-01T18:30:47.9170598Z 	at org.apache.pinot.query.runtime.executor.OpChainSchedulerService$1.runJob(OpChainSchedulerService.java:88)
2023-06-01T18:30:47.9171039Z 	... 6 more}
2023-06-01T18:30:47.9171479Z 	at org.apache.pinot.query.service.dispatch.QueryDispatcher.reduceMailboxReceive(QueryDispatcher.java:223)
2023-06-01T18:30:47.9172105Z 	at org.apache.pinot.query.service.dispatch.QueryDispatcher.runReducer(QueryDispatcher.java:204)
2023-06-01T18:30:47.9172681Z 	at org.apache.pinot.query.runtime.QueryRunnerTestBase.queryRunner(QueryRunnerTestBase.java:125)
2023-06-01T18:30:47.9173300Z 	at org.apache.pinot.query.runtime.queries.ResourceBasedQueriesTest.runQuery(ResourceBasedQueriesTest.java:298)
2023-06-01T18:30:47.9174026Z 	at org.apache.pinot.query.runtime.queries.ResourceBasedQueriesTest.testQueryTestCasesWithH2(ResourceBasedQueriesTest.java:223)
2023-06-01T18:30:47.9174641Z 	at jdk.internal.reflect.GeneratedMethodAccessor31.invoke(Unknown Source)
2023-06-01T18:30:47.9175181Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-06-01T18:30:47.9175667Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2023-06-01T18:30:47.9176121Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
2023-06-01T18:30:47.9176582Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
2023-06-01T18:30:47.9193016Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
2023-06-01T18:30:47.9193519Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
2023-06-01T18:30:47.9193997Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
2023-06-01T18:30:47.9194470Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
2023-06-01T18:30:47.9194867Z 	at org.testng.TestRunner.privateRun(TestRunner.java:744)
2023-06-01T18:30:47.9195208Z 	at org.testng.TestRunner.run(TestRunner.java:602)
2023-06-01T18:30:47.9195547Z 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
2023-06-01T18:30:47.9195922Z 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
2023-06-01T18:30:47.9196307Z 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
2023-06-01T18:30:47.9196658Z 	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
2023-06-01T18:30:47.9197033Z 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
2023-06-01T18:30:47.9197429Z 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
2023-06-01T18:30:47.9197815Z 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
2023-06-01T18:30:47.9198347Z 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
2023-06-01T18:30:47.9198683Z 	at org.testng.TestNG.runSuites(TestNG.java:1144)
2023-06-01T18:30:47.9198992Z 	at org.testng.TestNG.run(TestNG.java:1115)
2023-06-01T18:30:47.9199392Z 	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:136)
2023-06-01T18:30:47.9199990Z 	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
2023-06-01T18:30:47.9200654Z 	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
2023-06-01T18:30:47.9201205Z 	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:145)
2023-06-01T18:30:47.9201808Z 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
2023-06-01T18:30:47.9202332Z 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
2023-06-01T18:30:47.9202797Z 	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
2023-06-01T18:30:47.9203253Z 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
```

seems like there are some distributed deadlock? will investigate if i can find another example.

CC @Jackie-Jiang

**Comment by walterddr** [comment]
was able to consistently reproduce with high concurrency on cluster. looking into why

**Comment by ege-st** [comment]
This bug is also affecting the tests on this PR: https://github.com/apache/pinot/actions/runs/5180339556/jobs/9338571616?pr=10835

**Comment by walterddr** [comment]
this is still flaky. see:
https://github.com/apache/pinot/actions/runs/5192571154/jobs/9366737060

**Comment by walterddr** [comment]
found another race-condition --> 
1. when pipeline breaker returns it is side-cart loading the result map materialized from the PipelineBreakerOperator --> which returns immediately after the mailbox receives the final block. 
2. however, while the mailbox received the final block, it will return the EOS back to the opChainScheduler, then OpChainScheduler deregister/close the opChain properly. 
    - once the opChain close properly, the leaf stage can then be registered 

if the opChain was closed after the leaf stage opChain being registered, it throws:
```
2023-06-07T01:27:12.8609939Z [INFO] Running org.apache.pinot.query.runtime.queries.ResourceBasedQueriesTest
2023-06-07T01:27:28.3251491Z 01:27:28.203 ERROR [QueryRunner] [QueryServerTest_Server-2-thread-3] Error executing leaf stage for: -7077425705764084110:2
2023-06-07T01:27:28.3255009Z java.lang.IllegalStateException: Tried to re-register op-chain: -7077425705764084110_0_2
2023-06-07T01:27:28.3255606Z 	at com.google.common.base.Preconditions.checkState(Preconditions.java:510) ~[guava-30.1.1-jre.jar:?]
2023-06-07T01:27:28.3256318Z 	at org.apache.pinot.query.runtime.executor.RoundRobinScheduler.register(RoundRobinScheduler.java:146) ~[classes/:?]
2023-06-07T01:27:28.3257063Z 	at org.apache.pinot.query.runtime.executor.OpChainSchedulerService.register(OpChainSchedulerService.java:135) ~[classes/:?]
2023-06-07T01:27:28.3257752Z 	at org.apache.pinot.query.runtime.QueryRunner.processQuery(QueryRunner.java:167) ~[classes/:?]
2023-06-07T01:27:28.3258481Z 	at org.apache.pinot.query.QueryServerEnclosure.lambda$processQuery$1(QueryServerEnclosure.java:135) ~[test-classes/:?]
2023-06-07T01:27:28.3259318Z 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
2023-06-07T01:27:28.3259904Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
2023-06-07T01:27:28.3260431Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
2023-06-07T01:27:28.3260991Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
2023-06-07T01:27:28.3261444Z 	at java.lang.Thread.run(Thread.java:829) [?:?]
2023-06-07T01:27:28.3262254Z 01:27:28.312 ERROR [OpChainSchedulerService] [query_intermediate_worker_on_41325_port-5-thread-2] (OpChain{-7077425705764084110_0_1}): Failed to execute operator chain! (-7077425705764084110_0_1) Queued Count: 3, Executing Time: 0ms, Queued Time: 128ms
2023-06-07T01:27:28.3262881Z java.lang.InterruptedException: Query was cancelled!
2023-06-07T01:27:28.3263472Z 	at org.apache.pinot.query.runtime.executor.OpChainSchedulerService$1.runJob(OpChainSchedulerService.java:88) [classes/:?]
2023-06-07T01:27:28.3264560Z 	at org.apache.pinot.core.util.trace.TraceRunnable.run(TraceRunnable.java:40) [pinot-core-0.13.0-SNAPSHOT.jar:0.13.0-SNAPSHOT-3b2e31cfad6d327ca41021e091812f0f7e17e453]
2023-06-07T01:27:28.3265217Z 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
2023-06-07T01:27:28.3265689Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
2023-06-07T01:27:28.3266195Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
2023-06-07T01:27:28.3266738Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
2023-06-07T01:27:28.3267166Z 	at java.lang.Thread.run(Thread.java:829) [?:?]
```
