### ISSUE TITLE
Is pinot possible to support batch Ingestion with Upsert?

### ISSUE THREAD

**Issue by shuitai** [apache/pinot#10896]

**Comment by tibrewalpratik17** [comment]
@atris and I are working on the design doc for this and will create an issue for this soon.

**Comment by Jackie-Jiang** [comment]
This should be straight forward because real-time table supports all operations in offline table. We may move the upsert handling logic into the `BaseTableDataManager` so that it can be shared for both table types.

**Comment by chenboat** [comment]
@Jackie-Jiang I do not understand the full context here. @shuitai You may need to explain more. Does batch ingestion mean Pinot offline table batch ingestion? If it is so, Pinot offline table update is done through segment upload. You can already overwrite an existing segment. Why do we need extra feature here?

**Comment by rohityadav1993** [comment]
Tried to upload segments to an upsert table and faced with the following challenges based on this previous [discussion doc](https://docs.google.com/document/d/1STYxZsUYGcYrzHdmOBymQ1NkpxuEzLa4OTiw4mGHiKk/edit#heading=h.2nui75aa5u6b):

1. Generate a segment using `simple` name generator strategy to create a segment using IngestionUtils and upload:
    There are checks in place which expect the segment to be named as a LLC segment:
```
    j.l.IllegalArgumentException: Invalid LLC segment name: testtable_1695407400000_1695414594000_0_1
        at c.g.common.base.Preconditions.checkArgument(Preconditions.java:210)
        at o.a.p.c.utils.LLCSegmentName.<init>(LLCSegmentName.java:42)
        at o.a.p.c.u.PeerServerSegmentFinder.getPeerServerURIs(PeerServerSegmentFinder.java:64)
        at o.a.p.c.d.m.r.RealtimeTableDataManager.downloadSegmentFromPeer(RealtimeTableDataManager.java:604)
        ... 15 common frames omitted
    Wrapped by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Invalid LLC segment name: testtable_1695407400000_1695414594000_0_1
        at o.a.p.c.d.m.r.RealtimeTableDataManager.downloadSegmentFromPeer(RealtimeTableDataManager.java:612)
        at o.a.p.c.d.m.r.RealtimeTableDataManager.downloadAndReplaceSegment(RealtimeTableDataManager.java:539)
        at o.a.p.c.d.m.r.RealtimeTableDataManager.addSegment(RealtimeTableDataManager.java:420)
        at o.a.p.s.s.h.HelixInstanceDataManager.addRealtimeSegment(HelixInstanceDa...
```
2. Use `fixed` name generator strategy and name segment as LLC name:
```
Got invalid segment metadata when adding segment: rta_rider_sessions_test_REALTIME__0__0__19700101T0000Z for table: testtable_REALTIME, reason: New uploaded LLC segment must have start/end offset in the segment metadata
```

We may have to solve this by considering below options:

1. Allow offline segments like names in real-time table
2. Allow LLC segment like names for uploaded segment without enforcement of offset metadata. (the client needs to manage segment name conflicts)

**Comment by shuitai** [comment]
@chenboat 

If there are duplicated records in batch ingestion, upsert feature could dedup them. 
If overwriting batch data,  the client needs to dedup by spark, flink or other tools. 
The upsert is the most advantage of pinot compared to druid, if do upsert in pinot, it could help customer save ETL costs.
So upsert feature in batch is also very useful.

**Comment by Jackie-Jiang** [comment]
In order to update offline segments to upsert table, they need to be partitioned.
@chenboat Could you please share the steps of bootstrapping an upsert table with offline segments?

**Comment by rohityadav1993** [comment]
The segments are partitioned similarly how the stream is pre-partitioned during realtime ingestion. The challenge is validations that are in place, segments have to follow a naming convention for reatime tables and there needs to be offset info present when loading the segment.

Should we create a new type for segments which implies externally uploaded segments for realtime tables and have separate validations for them in addSegment flow?

**Comment by Jackie-Jiang** [comment]
@rohityadav1993 That shouldn't be the case if you have explicit partitioning enabled. Take a look at this [example](https://docs.pinot.apache.org/basics/data-import/upsert#example), specifically the `segmentPartitionConfig`.

**Comment by rohityadav1993** [comment]
@Jackie-Jiang 
`segmentPartitionConfig` makes sense. The problem is at a different place.

If we upload an offline segment (Controller identifies this from offline segment naming convention `testtable_1695407400000_1695414594000_0_1`) it is able to figure out the partition from name and assign to right server. The server fails to load the segment due the LLCSegment name validation.

If we create a segment name following the LLCSegment naming convention, the controller tries to add it to upsert table but fails it during metadata validation essentially failing the upload. 

I believe we will have to refine the validations to make backfills to upsert tables work.
It can also be useful to discuss if we want to allow offline segment names for realtime upsert table or introduce a new naming convention which can have its own validation.

**Comment by Jackie-Jiang** [comment]
Actually the exception was thrown by `RealtimeTableDataManager.downloadSegmentFromPeer()` which shouldn't be invoked at all. I guess what have happened is some other exception was thrown when `downloadSegmentFromDeepStore()`, and then it somehow fallback to the peer download which is not possible for offline segments. Can you search for log of `Download segment {} from deepstore uri {} failed.`?
