### ISSUE TITLE
Integration Test Failure in BaseRawIntSingleColumnDistinctExecutor

### ISSUE THREAD

**Issue by ankitsultana** [apache/pinot#10917]
Saw this integration test failure: https://github.com/apache/pinot/actions/runs/5273083250/jobs/9536095285

This assertion seems to be failing in `BaseRawIntSingleColumnDistinctExecutor`

```
    assert records.size() <= _limit;
```

(I haven't take a deeper look into this)

cc: @walterddr 

```
00:04:38.767 ERROR [BaseCombineOperator] [query_leaf_worker_on_46807_port-2-thread-3] Caught serious error while processing query: QueryContext{_tableName='mytable_OFFLINE', _subquery=null, _selectExpressions=[distinct(ActualElapsedTime)], _aliasList=[null], _filter=null, _groupByExpressions=null, _havingFilter=null, _orderByExpressions=null, _limit=2147483647, _offset=0, _queryOptions={pinot.query.runner.broker.request.timeout.ms=60000, useMultistageEngine=true, timeoutMs=60000, pinot.query.runner.broker.request.id=1650621113000000191, responseFormat=sql, groupByMode=sql}, _expressionOverrideHints={}, _explain=false}
java.lang.AssertionError: null
	at org.apache.pinot.core.query.distinct.raw.BaseRawIntSingleColumnDistinctExecutor.getResult(BaseRawIntSingleColumnDistinctExecutor.java:73) ~[classes/:?]
Jun 15, 2023 12:04:38 AM io.grpc.internal.ServerCallImpl internalClose
	at org.apache.pinot.core.query.distinct.raw.RawIntSingleColumnDistinctOnlyExecutor.getResult(RawIntSingleColumnDistinctOnlyExecutor.java:29) ~[classes/:?]
WARNING: Cancelling the stream with status Status{code=INTERNAL, description=Completed without a response, cause=null}
	at org.apache.pinot.core.operator.query.DistinctOperator.getNextBlock(DistinctOperator.java:66) ~[classes/:?]
	at org.apache.pinot.core.operator.query.DistinctOperator.getNextBlock(DistinctOperator.java:38) ~[classes/:?]
	at org.apache.pinot.core.operator.BaseOperator.nextBlock(BaseOperator.java:43) ~[classes/:?]
	at org.apache.pinot.core.operator.combine.BaseSingleBlockCombineOperator.processSegments(BaseSingleBlockCombineOperator.java:102) ~[classes/:?]
	at org.apache.pinot.core.operator.combine.BaseCombineOperator$1.runJob(BaseCombineOperator.java:108) [classes/:?]
	at org.apache.pinot.core.util.trace.TraceRunnable.run(TraceRunnable.java:40) [classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
00:04:38.769 ERROR [OpChainSchedulerService] [query_intermediate_worker_on_46807_port-1-thread-3] (OpChain{1650621113000000191_0_3}): Completed erroneously (1650621113000000191_0_3) Queued Count: 1, Executing Time: 23ms, Queued Time: 0ms {200=QueryExecutionError:
java.lang.AssertionError
	at org.apache.pinot.core.query.distinct.raw.BaseRawIntSingleColumnDistinctExecutor.getResult(BaseRawIntSingleColumnDistinctExecutor.java:73)
	at org.apache.pinot.core.query.distinct.raw.RawIntSingleColumnDistinctOnlyExecutor.getResult(RawIntSingleColumnDistinctOnlyExecutor.java:29)
	at org.apache.pinot.core.operator.query.DistinctOperator.getNextBlock(DistinctOperator.java:66)
	at org.apache.pinot.core.operator.query.DistinctOperator.getNextBlock(DistinctOperator.java:38)}
00:04:38.770 ERROR [OpChainSchedulerService] [query_intermediate_worker_on_46807_port-1-thread-3] (OpChain{1650621113000000191_0_2}): Completed erroneously (1650621113000000191_0_2) Queued Count: 2, Executing Time: 0ms, Queued Time: 24ms {200=QueryExecutionError:
java.lang.AssertionError
	at org.apache.pinot.core.query.distinct.raw.BaseRawIntSingleColumnDistinctExecutor.getResult(BaseRawIntSingleColumnDistinctExecutor.java:73)
	at org.apache.pinot.core.query.distinct.raw.RawIntSingleColumnDistinctOnlyExecutor.getResult(RawIntSingleColumnDistinctOnlyExecutor.java:29)
	at org.apache.pinot.core.operator.query.DistinctOperator.getNextBlock(DistinctOperator.java:66)
	at org.apache.pinot.core.operator.query.DistinctOperator.getNextBlock(DistinctOperator.java:38)}
00:04:38.770 ERROR [OpChainSchedulerService] [query_intermediate_worker_on_46807_port-1-thread-3] (OpChain{1650621113000000191_0_1}): Completed erroneously (1650621113000000191_0_1) Queued Count: 2, Executing Time: 0ms, Queued Time: 25ms {200=QueryExecutionError:
java.lang.AssertionError
	at org.apache.pinot.core.query.distinct.raw.BaseRawIntSingleColumnDistinctExecutor.getResult(BaseRawIntSingleColumnDistinctExecutor.java:73)
	at org.apache.pinot.core.query.distinct.raw.RawIntSingleColumnDistinctOnlyExecutor.getResult(RawIntSingleColumnDistinctOnlyExecutor.java:29)
	at org.apache.pinot.core.operator.query.DistinctOperator.getNextBlock(DistinctOperator.java:66)
	at org.apache.pinot.core.operator.query.DistinctOperator.getNextBlock(DistinctOperator.java:38)}
```

**Comment by Jackie-Jiang** [comment]
Should be fixed by #10887. We can reopen it if it happens again
