### ISSUE TITLE
Failing local execution of Pinot.

### ISSUE THREAD

**Issue by abhioncbr** [apache/pinot#10980]
The local startup of Pinot(built from the `master` branch) using the command `./bin/pinot-admin.sh QuickStart -type batch` is failing with the following exception.

```
TargetExternalViewCalcWorker thread interrupted
java.lang.InterruptedException: null
	at java.lang.Object.wait0(Native Method) ~[?:?]
	at java.lang.Object.wait(Object.java:366) ~[?:?]
	at java.lang.Object.wait(Object.java:339) ~[?:?]
	at org.apache.helix.common.DedupEventBlockingQueue.take(DedupEventBlockingQueue.java:102) ~[pinot-all-0.13.0-SNAPSHOT-jar-with-dependencies.jar:0.13.0-SNAPSHOT-a2086072545fc67a35f5d6756c3b9efc97d15641]
	at org.apache.helix.common.DedupEventProcessor.run(DedupEventProcessor.java:60) [pinot-all-0.13.0-SNAPSHOT-jar-with-dependencies.jar:0.13.0-SNAPSHOT-a2086072545fc67a35f5d6756c3b9efc97d15641]
END TargetExternalViewCalcWorker thread for cluster QuickStartCluster
Closing zkclient uid:7, zk:State:CONNECTED Timeout:30000 sessionid:0x100182998ad0006 local:/[0:0:0:0:0:0:0:1]:64643 remoteserver:localhost/[0:0:0:0:0:0:0:1]:2123 lastZxid:48 xid:4 sent:6 recv:6 queuedpkts:0 pendingresp:0 queuedevents:0
Session: 0x100182998ad0006 closed
Closed zkclient with uid:7
EventThread shut down for session: 0x100182998ad0006

```

cc: @Jackie-Jiang

**Comment by Jackie-Jiang** [comment]
This doesn't seem to be the root cause of the failure. All these classes are `Helix` classes, not Pinot classes. Can you check if there are other error logs before this, or if there are existing instances already running (e.g. ZK)

**Comment by abhioncbr** [comment]
Got it working after some cleanup. Thanks for the help.

**Comment by kmakwana** [comment]
@abhioncbr I am facing the same issue. Can you please explain in detail what cleanup process you did & how?
