### ISSUE TITLE
Starting Zookeeper throws java.lang.InterruptedException: null

### ISSUE THREAD

**Issue by kmakwana** [apache/pinot#11031]
I am trying to start Zookeeper with docker. Below is the content of docker file.
```
FROM openjdk:11

WORKDIR /app

ENV PINOT_VERSION=0.12.1

RUN wget https://archive.apache.org/dist/pinot/apache-pinot-$PINOT_VERSION/apache-pinot-$PINOT_VERSION-bin.tar.gz
RUN tar -zxvf apache-pinot-$PINOT_VERSION-bin.tar.gz

RUN chmod -R 777 apache-pinot-$PINOT_VERSION-bin/

EXPOSE 9000
```

- Building docker file

`docker build . -t pinot-test-5 `

- Running docker

`docker run -p 9000:9000 -it pinot-test-5 /bin/bash`

- Starting Zookeeper

`./apache-pinot-0.12.1-bin/bin/pinot-admin.sh StartZookeeper &`

Below is the exception faced:
```
java.lang.InterruptedException: null
        at java.lang.Object.wait(Native Method) ~[?:?]
        at java.lang.Object.wait(Object.java:328) ~[?:?]
        at org.apache.helix.zookeeper.zkclient.callback.ZkAsyncCallbacks$DefaultCallback.waitForSuccess(ZkAsyncCallbacks.java:248) [pinot-all-0.12.1-jar-with-dependencies.jar:0.12.1-6e235a4ec2a16006337da04e118a435b5bb8f6d8]
        at org.apache.helix.zookeeper.zkclient.ZkClient.issueSync(ZkClient.java:1616) [pinot-all-0.12.1-jar-with-dependencies.jar:0.12.1-6e235a4ec2a16006337da04e118a435b5bb8f6d8]
        at org.apache.helix.zookeeper.zkclient.ZkClient.access$300(ZkClient.java:85) [pinot-all-0.12.1-jar-with-dependencies.jar:0.12.1-6e235a4ec2a16006337da04e118a435b5bb8f6d8]
        at org.apache.helix.zookeeper.zkclient.ZkClient$4.run(ZkClient.java:1642) [pinot-all-0.12.1-jar-with-dependencies.jar:0.12.1-6e235a4ec2a16006337da04e118a435b5bb8f6d8]
        at org.apache.helix.zookeeper.zkclient.ZkEventThread.run(ZkEventThread.java:99) [pinot-all-0.12.1-jar-with-dependencies.jar:0.12.1-6e235a4ec2a16006337da04e118a435b5bb8f6d8]
zkclient 0, sycnOnNewSession with sessionID 100032985bb0000 async return code: OK and proceeds
Closing zkclient uid:0, zk:State:CONNECTED Timeout:30000 sessionid:0x100032985bb0000 local:/127.0.0.1:52804 remoteserver:localhost/127.0.0.1:2181 lastZxid:5 xid:2 sent:2 recv:2 queuedpkts:0 pendingresp:0 queuedevents:0
Session: 0x100032985bb0000 closed
Closed zkclient with uid:0
EventThread shut down for session: 0x100032985bb0000
Start zookeeper at localhost:2181 in thread main
```
Complete logs attached
[zookeeper.log](https://github.com/apache/pinot/files/11954045/zookeeper.log)

**Comment by abhioncbr** [comment]
As per the logs and command, zookeeper is running as the background process. It's not failing. Check `lsof` for 2181 port.

**Comment by kmakwana** [comment]
Closing this issue as Zookeeper is running in the background & getting no problem so far
