### ISSUE TITLE
Adding new table throws java.lang.NullPointerException

### ISSUE THREAD

**Issue by kmakwana** [apache/pinot#11038]
Below is the content of docker file
```
FROM openjdk:11

WORKDIR /app

ENV PINOT_VERSION=0.12.1

RUN wget https://archive.apache.org/dist/pinot/apache-pinot-$PINOT_VERSION/apache-pinot-$PINOT_VERSION-bin.tar.gz
RUN tar -zxvf apache-pinot-$PINOT_VERSION-bin.tar.gz

RUN chmod -R 777 apache-pinot-$PINOT_VERSION-bin/

EXPOSE 9000
```
- Building docker file
```
docker build . -t pinot-test-5 
```
- Running docker
```
docker run -p 9000:9000 -it pinot-test-5 /bin/bash
```
- Starting Zookeeper
```
./apache-pinot-0.12.1-bin/bin/pinot-admin.sh StartZookeeper &

```
- Starting Controller
```
./apache-pinot-0.12.1-bin/bin/pinot-admin.sh StartController &
```
- Starting Broker
```
./apache-pinot-0.12.1-bin/bin/pinot-admin.sh StartBroker &
```
- Starting Server
```
./apache-pinot-0.12.1-bin/bin/pinot-admin.sh StartServer &
```
- Adding Schema
```
./apache-pinot-0.12.1-bin/bin/pinot-admin.sh AddSchema -schemaFile ./apache-pinot-0.12.1-bin/examples/batch/baseballStats/baseballStats_schema.json -exec
```
- Adding Table
```
./apache-pinot-0.12.1-bin/bin/pinot-admin.sh AddTable -tableConfig ./apache-pinot-0.12.1-bin/examples/batch/baseballStats/baseballStats_offline_table_config.json -exec
```
Got below the error at the time of adding table:
```
Executing command: AddTable -tableConfigFile ../examples/batch/baseballStats/baseballStats_offline_table_config.json -offlineTableConfigFile null -realtimeTableConfigFilenull -schemaFile null -controllerProtocol http -controllerHost 172.17.0.2 -controllerPort 9000 -user null -password [hidden] -exec
Failed reading schema null
java.lang.NullPointerException: null
        at java.io.File.<init>(File.java:278) ~[?:?]
        at org.apache.pinot.tools.admin.command.AddTableCommand.lambda$execute$3(AddTableCommand.java:251) ~[pinot-all-0.12.1-jar-with-dependencies.jar:0.12.1-6e235a4ec2a16006337da04e118a435b5bb8f6d8]
        at org.apache.pinot.tools.admin.command.AddTableCommand.attempt(AddTableCommand.java:264) [pinot-all-0.12.1-jar-with-dependencies.jar:0.12.1-6e235a4ec2a16006337da04e118a435b5bb8f6d8]
        at org.apache.pinot.tools.admin.command.AddTableCommand.execute(AddTableCommand.java:251) [pinot-all-0.12.1-jar-with-dependencies.jar:0.12.1-6e235a4ec2a16006337da04e118a435b5bb8f6d8]
        at org.apache.pinot.tools.Command.call(Command.java:33) [pinot-all-0.12.1-jar-with-dependencies.jar:0.12.1-6e235a4ec2a16006337da04e118a435b5bb8f6d8]
        at org.apache.pinot.tools.Command.call(Command.java:29) [pinot-all-0.12.1-jar-with-dependencies.jar:0.12.1-6e235a4ec2a16006337da04e118a435b5bb8f6d8]
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953) [pinot-all-0.12.1-jar-with-dependencies.jar:0.12.1-6e235a4ec2a16006337da04e118a435b5bb8f6d8]
        at picocli.CommandLine.access$1300(CommandLine.java:145) [pinot-all-0.12.1-jar-with-dependencies.jar:0.12.1-6e235a4ec2a16006337da04e118a435b5bb8f6d8]
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352) [pinot-all-0.12.1-jar-with-dependencies.jar:0.12.1-6e235a4ec2a16006337da04e118a435b5bb8f6d8]
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2346) [pinot-all-0.12.1-jar-with-dependencies.jar:0.12.1-6e235a4ec2a16006337da04e118a435b5bb8f6d8]
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2311) [pinot-all-0.12.1-jar-with-dependencies.jar:0.12.1-6e235a4ec2a16006337da04e118a435b5bb8f6d8]
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179) [pinot-all-0.12.1-jar-with-dependencies.jar:0.12.1-6e235a4ec2a16006337da04e118a435b5bb8f6d8]
        at picocli.CommandLine.execute(CommandLine.java:2078) [pinot-all-0.12.1-jar-with-dependencies.jar:0.12.1-6e235a4ec2a16006337da04e118a435b5bb8f6d8]
        at org.apache.pinot.tools.admin.PinotAdministrator.execute(PinotAdministrator.java:171) [pinot-all-0.12.1-jar-with-dependencies.jar:0.12.1-6e235a4ec2a16006337da04e118a435b5bb8f6d8]
        at org.apache.pinot.tools.admin.PinotAdministrator.main(PinotAdministrator.java:202) [pinot-all-0.12.1-jar-with-dependencies.jar:0.12.1-6e235a4ec2a16006337da04e118a435b5bb8f6d8]
java.lang.IllegalStateException: java.lang.NullPointerException
        at org.apache.pinot.tools.admin.command.AddTableCommand.attempt(AddTableCommand.java:267)
        at org.apache.pinot.tools.admin.command.AddTableCommand.execute(AddTableCommand.java:251)
        at org.apache.pinot.tools.Command.call(Command.java:33)
        at org.apache.pinot.tools.Command.call(Command.java:29)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at org.apache.pinot.tools.admin.PinotAdministrator.execute(PinotAdministrator.java:171)
        at org.apache.pinot.tools.admin.PinotAdministrator.main(PinotAdministrator.java:202)
Caused by: java.lang.NullPointerException
        at java.base/java.io.File.<init>(File.java:278)
        at org.apache.pinot.tools.admin.command.AddTableCommand.lambda$execute$3(AddTableCommand.java:251)
        at org.apache.pinot.tools.admin.command.AddTableCommand.attempt(AddTableCommand.java:264)
        ... 12 more
```
Complete logs attached
[table_error.log](https://github.com/apache/pinot/files/11965781/table_error.log)

**Comment by Jackie-Jiang** [comment]
I think there is a missing space after `-realtimeTableConfigFile`

**Comment by kmakwana** [comment]
I am applying below command in which I don't specify _-realtimeTableConfigFile_
`./apache-pinot-0.12.1-bin/bin/pinot-admin.sh AddTable -tableConfig ./apache-pinot-0.12.1-bin/examples/batch/baseballStats/baseballStats_offline_table_config.json -exec`

**Comment by Jackie-Jiang** [comment]
Checked the code. When adding a table, schema file must also be provided. Can you try skipping the `AddSchema` step, and add `-schemaFile ./apache-pinot-0.12.1-bin/examples/batch/baseballStats/baseballStats_schema.json` to the `AddTable` step?

Do you find the above steps in the Pinot docs? If so, we should update the docs accordingly.

**Comment by kmakwana** [comment]
I got the reference from https://www.youtube.com/watch?v=9B6MCv0uC1s
Found out I've to specify schema while adding table with AddSchema -schemaFile command. If the schema is already existed then it will throw schema already exist error.
