### ISSUE TITLE
[multistage] [bug] unable to resolve table names for COMMA join 

### ISSUE THREAD

**Issue by xiangfu0** [apache/pinot#11065]
The query is executable, but unable to resolve the table names.
You can reproduce this from SSBQueryIntegrationTest.
```
14:40:52.934 ERROR [Connection] [main] Cannot parse table name from query: select sum(CAST(LO_EXTENDEDPRICE AS DOUBLE) * LO_DISCOUNT) as revenue
from lineorder, dates where LO_ORDERDATE = D_DATEKEY and D_YEARMONTHNUM = 199401
and LO_DISCOUNT between 4 and 6 and LO_QUANTITY between 26 and 35;
. Fallback to broker selector default.
java.lang.IllegalStateException: Unsupported join type: COMMA
	at org.apache.pinot.sql.parsers.CalciteSqlParser.compileToJoin(CalciteSqlParser.java:498) ~[classes/:?]
	at org.apache.pinot.sql.parsers.CalciteSqlParser.compileToDataSource(CalciteSqlParser.java:474) ~[classes/:?]
	at org.apache.pinot.sql.parsers.CalciteSqlParser.compileSqlNodeToPinotQuery(CalciteSqlParser.java:421) ~[classes/:?]
	at org.apache.pinot.client.Connection.resolveTableName(Connection.java:195) [classes/:?]
	at org.apache.pinot.client.Connection.execute(Connection.java:118) [classes/:?]
	at org.apache.pinot.client.Connection.execute(Connection.java:93) [classes/:?]
	at org.apache.pinot.integration.tests.SSBQueryIntegrationTest.testQueriesValidateAgainstH2(SSBQueryIntegrationTest.java:109) [test-classes/:?]
	at org.apache.pinot.integration.tests.SSBQueryIntegrationTest.testSSBQueries(SSBQueryIntegrationTest.java:103) [test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108) [testng-6.11.jar:?]
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661) [testng-6.11.jar:?]
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869) [testng-6.11.jar:?]
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193) [testng-6.11.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126) [testng-6.11.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109) [testng-6.11.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:744) [testng-6.11.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:602) [testng-6.11.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380) [testng-6.11.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375) [testng-6.11.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340) [testng-6.11.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:289) [testng-6.11.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) [testng-6.11.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86) [testng-6.11.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301) [testng-6.11.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226) [testng-6.11.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:1144) [testng-6.11.jar:?]
	at org.testng.TestNG.run(TestNG.java:1115) [testng-6.11.jar:?]
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66) [testng-rt.jar:?]
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105) [testng-rt.jar:?]
```

**Comment by xiangfu0** [comment]
cc: @walterddr @tibrewalpratik17 @abhioncbr

**Comment by abhioncbr** [comment]
I am working on the fix. Thanks

**Comment by xiangfu0** [comment]
https://github.com/apache/pinot/pull/11069

**Comment by xiangfu0** [comment]
> I am working on the fix. Thanks
Ah sorry missed your message, can you take a look the above pr.

**Comment by walterddr** [comment]
was wondering if we should always use calcite tool to extract tables. b/c the controller query resource is meant for adhoc query and can bear a bit of slowness. but this fix also works
