### ISSUE TITLE
Flaky LLCRealtimeClusterIntegrationTest.testAddRemoveDictionaryAndInvertedIndex

### ISSUE THREAD

**Issue by Jackie-Jiang** [apache/pinot#11084]
```
Error:  Tests run: 14, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 266.581 s <<< FAILURE! - in org.apache.pinot.integration.tests.LLCRealtimeClusterIntegrationTest
Error:  org.apache.pinot.integration.tests.LLCRealtimeClusterIntegrationTest.testDictionaryBasedQueries  Time elapsed: 3.169 s
Error:  org.apache.pinot.integration.tests.LLCRealtimeClusterIntegrationTest.testGeneratedQueries  Time elapsed: 29.548 s
Error:  org.apache.pinot.integration.tests.LLCRealtimeClusterIntegrationTest.testHardcodedQueries  Time elapsed: 9.748 s
Error:  org.apache.pinot.integration.tests.LLCRealtimeClusterIntegrationTest.testInstanceShutdown  Time elapsed: 0.336 s
Error:  org.apache.pinot.integration.tests.LLCRealtimeClusterIntegrationTest.testQueriesFromQueryFile  Time elapsed: 53.782 s
Error:  org.apache.pinot.integration.tests.LLCRealtimeClusterIntegrationTest.testQueryExceptions  Time elapsed: 0.041 s
Error:  org.apache.pinot.integration.tests.LLCRealtimeClusterIntegrationTest.testAddHLCTableShouldFail  Time elapsed: 0.012 s
Error:  org.apache.pinot.integration.tests.LLCRealtimeClusterIntegrationTest.testAddRemoveDictionaryAndInvertedIndex  Time elapsed: 0.018 s  <<< FAILURE!
java.lang.AssertionError: expected [231090] but found [231083]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:283)
	at org.testng.Assert.assertEquals(Assert.java:293)
	at org.apache.pinot.integration.tests.LLCRealtimeClusterIntegrationTest.testAddRemoveDictionaryAndInvertedIndex(LLCRealtimeClusterIntegrationTest.java:274)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:136)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:145)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)

Error:  org.apache.pinot.integration.tests.LLCRealtimeClusterIntegrationTest.testConsumerDirectoryExists  Time elapsed: 0 s
Error:  org.apache.pinot.integration.tests.LLCRealtimeClusterIntegrationTest.testForceCommit  Time elapsed: 2.819 s
Error:  org.apache.pinot.integration.tests.LLCRealtimeClusterIntegrationTest.testHardcodedServerPartitionedSqlQueries  Time elapsed: 0.609 s
Error:  org.apache.pinot.integration.tests.LLCRealtimeClusterIntegrationTest.testReload  Time elapsed: 9.115 s
Error:  org.apache.pinot.integration.tests.LLCRealtimeClusterIntegrationTest.testReset  Time elapsed: 6.662 s
Error:  org.apache.pinot.integration.tests.LLCRealtimeClusterIntegrationTest.testSegmentFlushSize  Time elapsed: 0.012 s
```

**Comment by shenyu0127** [comment]
Taking a look.

**Comment by shenyu0127** [comment]
@Jackie-Jiang helped me identify the root cause.

The realtime segments are created non-deterministically because the Kafka partitioning is using the system time ([ref](https://github.com/apache/pinot/blob/8171cfb000e68c40f08bd69a9c1f84e99b7c38c4/pinot-integration-test-base/src/test/java/org/apache/pinot/integration/tests/ClusterIntegrationTestUtils.java#L366)). There is a small chance some segments do not have the `ActualElapsedTime = -9999` record and gets pruned, so the `numEntriesScannedInFilter` is smaller than `numTotalDocs`, and the assert fails.

I am able to reproduce the bug by playing with the Kafka partition key generation:

totalDocs = 230546, numEntriesScannedInFilter = 230545
![Screenshot 2023-07-12 at 18 41 53](https://github.com/apache/pinot/assets/6668780/7c615e4b-8050-4e72-b6e8-082d95c95ec2)

This is because we have a consuming segment that has only 1 record which is not `ActualElapsedTime = -9999` and gets pruned.

![Screenshot 2023-07-12 at 18 40 58](https://github.com/apache/pinot/assets/6668780/e433f5ba-c0fd-4ecb-8d94-078981ffd7a6)

![Screenshot 2023-07-12 at 18 47 09](https://github.com/apache/pinot/assets/6668780/23770dd6-fd28-45d7-80ef-66e0256b2fd8)
