### ISSUE TITLE
[Flaky Test] ValueReaderComparisonTest.testUtf8Comparison

### ISSUE THREAD

**Issue by Jackie-Jiang** [apache/pinot#11108]
```
Error:  org.apache.pinot.segment.local.segment.index.readerwriter.ValueReaderComparisonTest.testUtf8Comparison[RandomBytesTextTestCase BIG_ENDIAN variable width](11)  Time elapsed: 0.033 s  <<< FAILURE!
java.lang.AssertionError: TpX���n��K��X=�K^o�y�􏺮ĄD����T����.����ѳ�ʃ�P�P�F)�8)	�� TpX���n��K��X=�K^o�y�??ĄD����T����.����ѳ�ʃ�P�P�F)�8)	�� expected [-1] but found [1]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:388)
	at org.apache.pinot.segment.local.segment.index.readerwriter.ValueReaderComparisonTest.assertUtf8Comparison(ValueReaderComparisonTest.java:316)
	at org.apache.pinot.segment.local.segment.index.readerwriter.ValueReaderComparisonTest$TextTestCase.testSuperiorPrefixes(ValueReaderComparisonTest.java:149)
	at org.apache.pinot.segment.local.segment.index.readerwriter.ValueReaderComparisonTest.testUtf8Comparison(ValueReaderComparisonTest.java:301)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:136)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:145)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
```

**Comment by Jackie-Jiang** [comment]
Another failure:
```
Error:  org.apache.pinot.segment.local.segment.index.readerwriter.ValueReaderComparisonTest.testUtf8Comparison[RandomBytesTextTestCase LITTLE_ENDIAN fixed width](7)  Time elapsed: 0.045 s  <<< FAILURE!
java.lang.AssertionError: 
q�5��V[y��)��1�"]����nA�}Oww��#�{��KlQ�s�4y>e�a�X��^�43�w􏾯��{���zX#�ys���v
ف�4LcD�	�s#�g5����"%0� q�5��V[y��)��1�"]����nA�}Oww��#�{��KlQ�s�4y>e�a�X��^�43�w??��{���zX#�ys���v
ف�4LcD�	�s#�g5����"%0� expected [-1] but found [1]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:388)
	at org.apache.pinot.segment.local.segment.index.readerwriter.ValueReaderComparisonTest.assertUtf8Comparison(ValueReaderComparisonTest.java:316)
	at org.apache.pinot.segment.local.segment.index.readerwriter.ValueReaderComparisonTest$TextTestCase.testSuperiorPrefixes(ValueReaderComparisonTest.java:149)
	at org.apache.pinot.segment.local.segment.index.readerwriter.ValueReaderComparisonTest.testUtf8Comparison(ValueReaderComparisonTest.java:301)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:136)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:145)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
```

**Comment by Jackie-Jiang** [comment]
@richardstartin Could you please help take a look?

**Comment by richardstartin** [comment]
Sure I can take a look

**Comment by xiangfu0** [comment]
https://github.com/apache/pinot/pull/11681
