### ISSUE TITLE
OnHeapDictionariesTest is flaky

### ISSUE THREAD

**Issue by shenyu0127** [apache/pinot#11221]
The failure is coming from lines introduced in https://github.com/apache/pinot/pull/10990: `at org.apache.commons.lang.StringEscapeUtils.unescapeJava(StringEscapeUtils.java:337)`

https://github.com/apache/pinot/actions/runs/5698525330/job/15446506008?pr=11188
```
Error:  org.apache.pinot.segment.local.segment.creator.OnHeapDictionariesTest.setup  Time elapsed: 1.349 s  <<< FAILURE!
org.apache.commons.lang.exception.NestableRuntimeException: Unable to parse unicode value: eM~>
	at org.apache.commons.lang.StringEscapeUtils.unescapeJava(StringEscapeUtils.java:337)
	at org.apache.commons.lang.StringEscapeUtils.unescapeJava(StringEscapeUtils.java:287)
	at org.apache.pinot.segment.spi.index.metadata.ColumnMetadataImpl.fromPropertiesConfiguration(ColumnMetadataImpl.java:254)
	at org.apache.pinot.segment.spi.index.metadata.SegmentMetadataImpl.init(SegmentMetadataImpl.java:233)
	at org.apache.pinot.segment.spi.index.metadata.SegmentMetadataImpl.<init>(SegmentMetadataImpl.java:132)
	at org.apache.pinot.segment.local.segment.index.converter.SegmentV1V2ToV3FormatConverter.convert(SegmentV1V2ToV3FormatConverter.java:77)
	at org.apache.pinot.segment.local.segment.creator.impl.SegmentIndexCreationDriverImpl.convertFormatIfNecessary(SegmentIndexCreationDriverImpl.java:376)
	at org.apache.pinot.segment.local.segment.creator.impl.SegmentIndexCreationDriverImpl.handlePostCreation(SegmentIndexCreationDriverImpl.java:309)
	at org.apache.pinot.segment.local.segment.creator.impl.SegmentIndexCreationDriverImpl.build(SegmentIndexCreationDriverImpl.java:261)
	at org.apache.pinot.segment.local.segment.creator.OnHeapDictionariesTest.buildSegment(OnHeapDictionariesTest.java:199)
	at org.apache.pinot.segment.local.segment.creator.OnHeapDictionariesTest.setup(OnHeapDictionariesTest.java:83)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:166)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:136)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:145)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
Caused by: java.lang.NumberFormatException: For input string: "eM~>" under radix 16
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:665)
	at org.apache.commons.lang.StringEscapeUtils.unescapeJava(StringEscapeUtils.java:331)
	... 38 more
```

@abhioncbr could you take a look?

**Comment by abhioncbr** [comment]
Thanks for mentioning, I will try to run the test in my local. 
We are working on the fix, https://github.com/apache/pinot/pull/11218.
