### ISSUE TITLE
ClassCastException while parsing the query/extracting table name

### ISSUE THREAD

**Issue by abhioncbr** [apache/pinot#11313]
While analyzing the [integration test run ](https://github.com/apache/pinot/actions/runs/5815928578/job/15768265482?pr=11312), found issue related to `ClassCastException`
```
02:50:03.078 ERROR [Connection] [main] Cannot parse table name from query: select
  s_acctbal,
  s_name,
  n_name,
  p_partkey,
  p_mfgr,
  s_address,
  s_phone,
  s_comment
from
  part,
  supplier,
  partsupp,
  nation,
  region
where
  p_partkey = ps_partkey
  and s_suppkey = ps_suppkey
  and p_size = 15
  and p_type like '%BRASS'
  and s_nationkey = n_nationkey
  and n_regionkey = r_regionkey
  and r_name = 'EUROPE'
  and ps_supplycost = (
    select
      min(ps_supplycost)
    from
      partsupp,
      supplier,
      nation,
      region
    where
      p_partkey = ps_partkey
      and s_suppkey = ps_suppkey
      and s_nationkey = n_nationkey
      and n_regionkey = r_regionkey
      and r_name = 'EUROPE'
  )
order by
  s_acctbal desc,
  n_name,
  s_name,
  p_partkey;
. Fallback to broker selector default.
java.lang.ClassCastException: class org.apache.calcite.sql.SqlSelect cannot be cast to class org.apache.calcite.sql.SqlBasicCall (org.apache.calcite.sql.SqlSelect and org.apache.calcite.sql.SqlBasicCall are in unnamed module of loader 'app')
	at org.apache.pinot.sql.parsers.CalciteSqlParser.toExpression(CalciteSqlParser.java:747) ~[classes/:?]
	at org.apache.pinot.sql.parsers.CalciteSqlParser.compileFunctionExpression(CalciteSqlParser.java:809) ~[classes/:?]
	at org.apache.pinot.sql.parsers.CalciteSqlParser.toExpression(CalciteSqlParser.java:747) ~[classes/:?]
	at org.apache.pinot.sql.parsers.CalciteSqlParser.compileAndExpression(CalciteSqlParser.java:931) ~[classes/:?]
	at org.apache.pinot.sql.parsers.CalciteSqlParser.compileFunctionExpression(CalciteSqlParser.java:758) ~[classes/:?]
	at org.apache.pinot.sql.parsers.CalciteSqlParser.toExpression(CalciteSqlParser.java:747) ~[classes/:?]
	at org.apache.pinot.sql.parsers.CalciteSqlParser.compileSqlNodeToPinotQuery(CalciteSqlParser.java:457) ~[classes/:?]
	at org.apache.pinot.client.Connection.resolveTableName(Connection.java:194) [classes/:?]
	at org.apache.pinot.client.Connection.execute(Connection.java:118) [classes/:?]
	at org.apache.pinot.client.Connection.execute(Connection.java:93) [classes/:?]
	at org.apache.pinot.integration.tests.TPCHQueryIntegrationTest.testQueriesSucceed(TPCHQueryIntegrationTest.java:117) [test-classes/:?]
	at org.apache.pinot.integration.tests.TPCHQueryIntegrationTest.testTPCHQueries(TPCHQueryIntegrationTest.java:113) [test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108) [testng-6.11.jar:?]
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661) [testng-6.11.jar:?]
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869) [testng-6.11.jar:?]
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193) [testng-6.11.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126) [testng-6.11.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109) [testng-6.11.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:744) [testng-6.11.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:602) [testng-6.11.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380) [testng-6.11.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375) [testng-6.11.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340) [testng-6.11.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:289) [testng-6.11.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) [testng-6.11.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86) [testng-6.11.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301) [testng-6.11.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226) [testng-6.11.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:1144) [testng-6.11.jar:?]
	at org.testng.TestNG.run(TestNG.java:1115) [testng-6.11.jar:?]
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:136) [surefire-testng-3.0.0-M5.jar:3.0.0-M5]
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112) [surefire-testng-3.0.0-M5.jar:3.0.0-M5]
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99) [surefire-testng-3.0.0-M5.jar:3.0.0-M5]
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:145) [surefire-testng-3.0.0-M5.jar:3.0.0-M5]
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428) [surefire-booter-3.0.0-M5.jar:3.0.0-M5]
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162) [surefire-booter-3.0.0-M5.jar:3.0.0-M5]
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562) [surefire-booter-3.0.0-M5.jar:3.0.0-M5]
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548) [surefire-booter-3.0.0-M5.jar:3.0.0-M5]
```
I will try to look into it.

**Comment by Jackie-Jiang** [comment]
Good catch. We should not compile SqlNode to PinotQuery because PinotQuery doesn't support all multi-stage engines. We should either directly extract table names from SqlNode or compile it as multi-stage query

**Comment by xiangfu0** [comment]
+1 to directly extract table names.

This is used to extract table names to ensure all the queried tables are in the same tenant, then route query to the corresponding broker tenant.

**Comment by avshenuk** [comment]
Getting this same error in Java client when using multi-stage engine-only queries e.g. `select from (select)` or `with (select) select`.

Is there any workaround or how can one run complex queries like that with Pinot?

**Comment by avshenuk** [comment]
> Is there any workaround

Ah, I guess the table name can be provided explicitly in the `execute` method.

**Comment by navneet-surana** [comment]
@avshenuk How to provide multiple table names in case of join queries? For example:

 ```
     WITH catalog_stats AS (
        SELECT catalog_id, COUNT(*) AS orders
        FROM sis_supplier_order_details_pinot_poc
        WHERE supplier_id = :supplierId
          AND order_date BETWEEN :startDate AND :endDate
        GROUP BY catalog_id
      )
      (SELECT supplier_id,
              sai.catalog_id as catalog_id,
              alert_type,
              alert_active_status,
              alert_visible_in_highlights,
              cs.orders as alert_priority
       FROM sis_supplier_alerts_pinot_poc sai
                LEFT JOIN catalog_stats cs ON sai.catalog_id = cs.catalog_id
       WHERE sai.supplier_id = :supplierId
         AND sai.alert_type = 'low_ratings'
         AND sai.alert_active_status = true
       ORDER BY cs.orders DESC
       LIMIT 20
      )
```

Calcite execute function don't have capability to provide multiple table names. Implementation seems to be buggy.

selectBroker supports multiple table where as out function doesn't. Is this intentional?

```
 public ResultSetGroup execute(@Nullable String tableName, String query) throws PinotClientException {
        String[] tableNames = tableName == null ? resolveTableName(query) : new String[]{tableName};
        String brokerHostPort = this._brokerSelector.selectBroker(tableNames);
        if (brokerHostPort == null) {
            String var10002 = tableNames == null ? "with no tables" : "for table(s): " + Arrays.asList(tableNames);
            throw new PinotClientException("Could not find broker to query " + var10002);
        } else {
            BrokerResponse response = this._transport.executeQuery(brokerHostPort, query);
            if (response.hasExceptions() && this._failOnExceptions) {
                throw new PinotClientException("Query had processing exceptions: \n" + response.getExceptions());
            } else {
                return new ResultSetGroup(response);
            }
        }
    }
```

**Comment by avshenuk** [comment]
Yeah, I agree.
Don’t see why multiple table names could not be allowed there. At least as a workaround until this is properly fixed.
