### ISSUE TITLE
Batch ingestion job with zstd parquet files

### ISSUE THREAD

**Issue by geekboood** [apache/pinot#11333]
With current parquet library, running batch ingestion job with zstd compression will lead to exception (without installing hadoop)
```
Caused by: java.lang.RuntimeException: native zStandard library not available: this version of libhadoop was built without zstd support.                                 
        at org.apache.hadoop.io.compress.ZStandardCodec.checkNativeCodeLoaded(ZStandardCodec.java:65)                                                                            at org.apache.hadoop.io.compress.ZStandardCodec.getDecompressorType(ZStandardCodec.java:211)                                                                     
        at org.apache.hadoop.io.compress.CodecPool.getDecompressor(CodecPool.java:181)                                                                                           at org.apache.pinot.shaded.org.apache.parquet.hadoop.CodecFactory$HeapBytesDecompressor.<init>(CodecFactory.java:98)                                             
        at org.apache.pinot.shaded.org.apache.parquet.hadoop.CodecFactory.createDecompressor(CodecFactory.java:210)                                                              at org.apache.pinot.shaded.org.apache.parquet.hadoop.CodecFactory.getDecompressor(CodecFactory.java:199)                                                         
        at org.apache.pinot.shaded.org.apache.parquet.hadoop.CodecFactory.getDecompressor(CodecFactory.java:42)                                                                  at org.apache.pinot.shaded.org.apache.parquet.hadoop.ParquetFileReader$Chunk.readAllPages(ParquetFileReader.java:1287)                                           
        at org.apache.pinot.shaded.org.apache.parquet.hadoop.ParquetFileReader.readNextRowGroup(ParquetFileReader.java:856)        at org.apache.pinot.plugin.inputformat.parquet.ParquetNativeRecordReader.init(ParquetNativeRecordReader.java:75)                                                 
        at org.apache.pinot.spi.data.readers.RecordReaderFactory.getRecordReaderByClass(RecordReaderFactory.java:148)                                                            at org.apache.pinot.segment.local.segment.creator.impl.SegmentIndexCreationDriverImpl.getRecordReader(SegmentIndexCreationDriverImpl.java:125)                   
        at org.apache.pinot.segment.local.segment.creator.impl.SegmentIndexCreationDriverImpl.init(SegmentIndexCreationDriverImpl.java:101)                                      at org.apache.pinot.plugin.ingestion.batch.common.SegmentGenerationTaskRunner.run(SegmentGenerationTaskRunner.java:112)                                          
        at org.apache.pinot.plugin.ingestion.batch.standalone.SegmentGenerationJobRunner.lambda$submitSegmentGenTask$1(SegmentGenerationJobRunner.java:265)        ... 5 more
```
Upgrading to parquet.version 1.12.0 could solve this. [https://issues.apache.org/jira/browse/PARQUET-1866](url)

**Comment by abhioncbr** [comment]
Fix https://github.com/apache/pinot/pull/11337
