### ISSUE TITLE
Server: OutOfMemoryError does not shutdown process

### ISSUE THREAD

**Issue by pjpringle** [apache/pinot#11361]
Server can become stuck on OutOfMemoryError.

Seems the throwable is caught somewhere in HelixStateTransitionHandler and does not cause the JVM to exit but it is logged out.
Throwables/Errors should not be caught.

` [HelixStateTransitionHandler]: Exception while executing a state transition task <segmentName>
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.GeneratedMethodAccessor61.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.apache.helix.messaging.handling.HelixStateTransitionHandler.invoke(HelixStateTransitionHandler.java:350) ~[pinot-all-0.12.0-jar-with-dependencies.jar:0.12.0-118f5e065cb258c171d97a586183759fbc61e2bf]
	at org.apache.helix.messaging.handling.HelixStateTransitionHandler.handleMessage(HelixStateTransitionHandler.java:278) [pinot-all-0.12.0-jar-with-dependencies.jar:0.12.0-118f5e065cb258c171d97a586183759fbc61e2bf]
	at org.apache.helix.messaging.handling.HelixTask.call(HelixTask.java:97) [pinot-all-0.12.0-jar-with-dependencies.jar:0.12.0-118f5e065cb258c171d97a586183759fbc61e2bf]
	at org.apache.helix.messaging.handling.HelixTask.call(HelixTask.java:49) [pinot-all-0.12.0-jar-with-dependencies.jar:0.12.0-118f5e065cb258c171d97a586183759fbc61e2bf]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.OutOfMemoryError: Java heap space`

**Comment by Jackie-Jiang** [comment]
Agree in regular case we should not catch throwable, but in the above stack trace, the throwable is caught within a `Thread`, and we intentionally catch it so that the thread doesn't die silently (it won't be able to propagate it back to the main thread even if we don't catch it). The best practice is to add JVM flag `ExitOnOutOfMemoryError` or `CrashOnOutOfMemoryError` so that it can exit regardless of where the error is triggered
