### ISSUE TITLE
Skipping realtime table when pinot restarted

### ISSUE THREAD

**Issue by skyb92** [apache/pinot#1138]
good morning sir, I'm new to pinot, I want to develop pinot into production, can you give me an example of things I should do?( like a few of server , broker and controller, on one cluster and the diagram) btw I use kafka for the input. Which one is better, real-time only or hybrid?

**Comment by mcvsubbu** [comment]
Hello skyb92,

Welcome to the pinot community.

Depending on the scale of things, you should have appropriate number of machines for servers, brokers and controllers. I suggest experimenting by generating a pinot segment, estimating how many segments you will need at any given time, what your replication factor is, and set up number of servers depending on the memory requirement. Pinot segments are stored in memory, so this is a start. You may need more servers to improve query throughput (or less, if your query rate is low, you may just MMAP the segments).

Having more than one controller and more than one broker is always a good idea in production.

It is your choice whether you want to use Hybrid or real-time-only solution. Hybrid may work better (at this time) if your retention is larger than a few days. 

-Subbu

**Comment by skyb92** [comment]
Hello @mcvsubbu ,

Thank you for your advice.  I'll post my progress soon.
Pinot is awesome!!

 -Skyb

**Comment by skyb92** [comment]
I got this error message when I restarted pinot, any suggestions?


Caught exception while processing resource mmcloud_facebook_akun_stat_REALTIME, skipping.
java.lang.NullPointerException
        at com.linkedin.pinot.controller.helix.core.realtime.PinotRealtimeSegmentManager.assignRealtimeSegmentsToServerInstancesIfNe
cessary(PinotRealtimeSegmentManager.java:207)
        at com.linkedin.pinot.controller.helix.core.realtime.PinotRealtimeSegmentManager.processPropertyStoreChange(PinotRealtimeSeg
mentManager.java:291)
        at com.linkedin.pinot.controller.helix.core.realtime.PinotRealtimeSegmentManager.access$000(PinotRealtimeSegmentManager.java
:66)
        at com.linkedin.pinot.controller.helix.core.realtime.PinotRealtimeSegmentManager$1.onControllerChange(PinotRealtimeSegmentMa
nager.java:105)
        at org.apache.helix.manager.zk.CallbackHandler.invoke(CallbackHandler.java:209)
        at org.apache.helix.manager.zk.CallbackHandler.init(CallbackHandler.java:324)
        at org.apache.helix.manager.zk.CallbackHandler.<init>(CallbackHandler.java:114)
        at org.apache.helix.manager.zk.ZKHelixManager.addListener(ZKHelixManager.java:317)
        at org.apache.helix.manager.zk.ZKHelixManager.addControllerListener(ZKHelixManager.java:426)
        at com.linkedin.pinot.controller.helix.core.realtime.PinotRealtimeSegmentManager.start(PinotRealtimeSegmentManager.java:102)
        at com.linkedin.pinot.controller.ControllerStarter.start(ControllerStarter.java:133)
        at com.linkedin.pinot.tools.admin.command.StartControllerCommand.execute(StartControllerCommand.java:155)
        at com.linkedin.pinot.tools.admin.PinotAdministrator.execute(PinotAdministrator.java:113)
        at com.linkedin.pinot.tools.admin.PinotAdministrator.main(PinotAdministrator.java:125)

**Comment by mcvsubbu** [comment]
We need the complete exception stack to say better, but this looks like
some entries in zookeeper are not correct. I suggest you drop the table
(wait for external view to clear out) and re-create it afresh.

Also,  make sure your helix instances are tagged correctly.

-Subbu

**Comment by skyb92** [comment]
Thank you @mcvsubbu it really helps.
