### ISSUE TITLE
Failed to query string column in noDictionaryColumns

### ISSUE THREAD

**Issue by rohityadav1993** [apache/pinot#11704]
A simple select * query leads to query failure with following. This happens only for a few rows and only in offline segments. The column is single value string with raw forward encoding
```
...
...
      "noDictionaryColumns": [
        "compressed_data_string"
      ]
    },
    "fieldConfigList": [
      {
        "name": "compressed_data_string",
        "encodingType": "RAW",
        "indexTypes": [],
        "properties": {
          "deriveNumDocsPerChunkForRawIndex": "true",
          "rawIndexWriterVersion": "3"
        }
      }
    ]
```

Error trace:
```
Caught exception while processing query
java.io.IOException: FAILED_TO_UNCOMPRESS(5)
	at org.xerial.snappy.SnappyNative.throw_error(SnappyNative.java:112)
	at org.xerial.snappy.SnappyNative.rawUncompress(SnappyNative.java)
	at org.xerial.snappy.Snappy.uncompress(Snappy.java:551)
	at o.a.p.s.l.i.c.SnappyDecompressor.decompress(SnappyDecompressor.java:40)
	at o.a.p.s.l.s.i.r.f.BaseChunkForwardIndexReader.decompressChunk(BaseChunkForwardIndexReader.java:140)
	... 25 common frames omitted
Wrapped by: java.lang.RuntimeException: java.io.IOException: FAILED_TO_UNCOMPRESS(5)
	at o.a.p.s.l.s.i.r.f.BaseChunkForwardIndexReader.decompressChunk(BaseChunkForwardIndexReader.java:143)
	at o.a.p.s.l.s.i.r.f.BaseChunkForwardIndexReader.getChunkBuffer(BaseChunkForwardIndexReader.java:121)
	at o.a.p.s.l.s.i.r.f.VarByteChunkSVForwardIndexReader.getStringCompressed(VarByteChunkSVForwardIndexReader.java:79)
	at o.a.p.s.l.s.i.r.f.VarByteChunkSVForwardIndexReader.getString(VarByteChunkSVForwardIndexReader.java:68)
	at o.a.p.s.l.s.i.r.f.VarByteCh...
```

**Comment by Jackie-Jiang** [comment]
Do you have the raw data used to generate the segment? From what I can tell from the stack trace, it might hit some bug in snappy library. Do you have special character in your data?

**Comment by rohityadav1993** [comment]
I do have the raw string that is being persisted. Is there a way to figure out which special character could be causing this?

**Comment by Jackie-Jiang** [comment]
Unfortunately I cannot tell what is causing the decompression failure by the stack trace itself.
To debug the issue, we need to dig into the problematic segment and find the chunk that cannot be decompressed. To find the bad segment, you may add filter on virtual column `$segmentName` and find which segment is causing the exception
After that, you may download the segment and load the segment with class `ImmutableSegmentLoader`, then debug the forward index `BaseChunkForwardIndexReader`.
