### ISSUE TITLE
[Flaky-test] PinotInstanceRestletResourceTest

### ISSUE THREAD

**Issue by Jackie-Jiang** [apache/pinot#11719]
```
Error:  org.apache.pinot.controller.api.PinotInstanceRestletResourceTest.instanceRetagHappyPathTest  Time elapsed: 0.023 s  <<< FAILURE!
java.io.IOException: org.apache.pinot.common.exception.HttpErrorStatusException: Got error status code: 404 (Not Found) with reason: "Instance broker_999 not found" while sending request: http://localhost:18998/instances/broker_999 to controller: fv-az590-486.wplo2yftg53erdu2vm2f1fqbde.bx.internal.cloudapp.net, version: Unknown
	at org.apache.pinot.controller.helix.ControllerTest.sendGetRequest(ControllerTest.java:780)
	at org.apache.pinot.controller.helix.ControllerTest.sendGetRequest(ControllerTest.java:770)
	at org.apache.pinot.controller.api.PinotInstanceRestletResourceTest.getInstanceTags(PinotInstanceRestletResourceTest.java:291)
	at org.apache.pinot.controller.api.PinotInstanceRestletResourceTest.getCurrentInstanceTagsMap(PinotInstanceRestletResourceTest.java:282)
	at org.apache.pinot.controller.api.PinotInstanceRestletResourceTest.instanceRetagHappyPathTest(PinotInstanceRestletResourceTest.java:211)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:284)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
Caused by: org.apache.pinot.common.exception.HttpErrorStatusException: Got error status code: 404 (Not Found) with reason: "Instance broker_999 not found" while sending request: http://localhost:18998/instances/broker_999 to controller: fv-az590-486.wplo2yftg53erdu2vm2f1fqbde.bx.internal.cloudapp.net, version: Unknown
	at org.apache.pinot.common.utils.http.HttpClient.wrapAndThrowHttpException(HttpClient.java:448)
	at org.apache.pinot.controller.helix.ControllerTest.sendGetRequest(ControllerTest.java:777)
	... 31 more

Error:  org.apache.pinot.controller.api.PinotInstanceRestletResourceTest.instanceRetagServerDeficiencyTest  Time elapsed: 0.025 s  <<< FAILURE!
java.io.IOException: org.apache.pinot.common.exception.HttpErrorStatusException: Got error status code: 404 (Not Found) with reason: "Instance broker_999 not found" while sending request: http://localhost:18998/instances/broker_999 to controller: fv-az590-486.wplo2yftg53erdu2vm2f1fqbde.bx.internal.cloudapp.net, version: Unknown
	at org.apache.pinot.controller.helix.ControllerTest.sendGetRequest(ControllerTest.java:780)
	at org.apache.pinot.controller.helix.ControllerTest.sendGetRequest(ControllerTest.java:770)
	at org.apache.pinot.controller.api.PinotInstanceRestletResourceTest.getInstanceTags(PinotInstanceRestletResourceTest.java:291)
	at org.apache.pinot.controller.api.PinotInstanceRestletResourceTest.getCurrentInstanceTagsMap(PinotInstanceRestletResourceTest.java:282)
	at org.apache.pinot.controller.api.PinotInstanceRestletResourceTest.instanceRetagServerDeficiencyTest(PinotInstanceRestletResourceTest.java:237)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:284)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
Caused by: org.apache.pinot.common.exception.HttpErrorStatusException: Got error status code: 404 (Not Found) with reason: "Instance broker_999 not found" while sending request: http://localhost:18998/instances/broker_999 to controller: fv-az590-486.wplo2yftg53erdu2vm2f1fqbde.bx.internal.cloudapp.net, version: Unknown
	at org.apache.pinot.common.utils.http.HttpClient.wrapAndThrowHttpException(HttpClient.java:448)
	at org.apache.pinot.controller.helix.ControllerTest.sendGetRequest(ControllerTest.java:777)
	... 31 more

Error:  org.apache.pinot.controller.api.PinotInstanceRestletResourceTest.testInstanceListingAndCreation  Time elapsed: 0.006 s  <<< FAILURE!
java.lang.AssertionError: expected [8] but found [9]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:388)
	at org.testng.Assert.assertEquals(Assert.java:398)
	at org.apache.pinot.controller.api.PinotInstanceRestletResourceTest.checkNumInstances(PinotInstanceRestletResourceTest.java:163)
	at org.apache.pinot.controller.api.PinotInstanceRestletResourceTest.testInstanceListingAndCreation(PinotInstanceRestletResourceTest.java:74)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:284)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
```

**Comment by Jackie-Jiang** [comment]
Duplicate of #11329
