### ISSUE TITLE
ScalarTransformFunctionWrapper throws exception for Object return type

### ISSUE THREAD

**Issue by abhioncbr** [apache/pinot#11743]
`ScalarTransformFunctionWrapper` throws an exception for any transformation function with `Object` return type. for example, `casewhen` or `cast`

Here is one such stack trace:
```bash
java.lang.IllegalStateException: Cannot convert ColumnDataType: OBJECT to DataType

	at org.apache.pinot.common.utils.DataSchema$ColumnDataType.toDataType(DataSchema.java:311)
	at org.apache.pinot.core.operator.transform.function.ScalarTransformFunctionWrapper.<init>(ScalarTransformFunctionWrapper.java:69)
	at org.apache.pinot.core.operator.transform.function.TransformFunctionFactory.get(TransformFunctionFactory.java:316)
	at org.apache.pinot.core.operator.transform.function.TransformFunctionFactory.get(TransformFunctionFactory.java:347)

```
this was introduced with the [PR](https://github.com/apache/pinot/pull/11453), [specific code change](https://github.com/apache/pinot/commit/6c69be463fea9ba9c0fe0103215f47581d41f8d4#diff-689152b23aca017e750b7828a4f12e3dad5e5deb523e423bb53a3b933aca77c2R68)

**Comment by Jackie-Jiang** [comment]
Good catch!

IMO we should not include `ColumnDataType.OBJECT` into `FunctionUtils.COLUMN_DATA_TYPE_MAP` (introduced in #8608) because `OBJECT` is just a placeholder column data type for intermediate aggregation result, and should not be exposed to the data schema. @walterddr Can you also double check if we can remove it?

**Comment by walterddr** [comment]
good point. let me double check and see if the planner side have any side effect if we remove.
