### ISSUE TITLE
Using Pinot from computer without network access gives exception.

### ISSUE THREAD

**Issue by soumyajitsamanta** [apache/pinot#11825]
Issue found:
Hi I have a computer which does not have internet connection and I wanted to used Pinot to analyse data generated on it and found there is uncaught exception which is caused by internet liveness check implemented in NetUtils:41.
The exception is mentioned everywhere but never caught and handled.

All other components when started through pinot-server.sh like controller, broker and zookeeper, they had to be given host config to avoid this problem there. But in this server start it is somewhere able to go through hoops and call internet. 
It did not take `-serverHost` as before server something else tries to perform NetUtils:41.

How to replicate:
1. Disconnect the computer from internet for real.
2. Try starting the server or any other component without any parameter like Controller, Zookeeper, Broker, etc.
3. It should try connect to internet to determine it is offline.
4. And exit with stacktrace because it cannot connect to internet.

Here is a stack trace:

```
java.io.UncheckedIOException: java.net.SocketException: Network is unreachable
	at sun.nio.ch.DatagramSocketAdaptor.connect(DatagramSocketAdaptor.java:120) ~[?:?]
	at java.net.DatagramSocket.connect(DatagramSocket.java:474) ~[?:?]
	at o.a.p.spi.utils.NetUtils.getHostAddress(NetUtils.java:41)
                   ~[pinot-all-1.0.0-jar-with-dependencies.jar:1.0.0-b6bdf6c9686b286a149d2d1aea4a385ee98f3e79]
	at o.a.p.tools.utils.PinotConfigUtils.generateControllerConf(PinotConfigUtils.java:65) 
	at o.a.p.tools.admin.command.StartServiceManagerCommand.getDefaultConfig(StartServiceManagerCommand.java:217) 
	at o.a.p.tools.admin.command.StartServiceManagerCommand.execute(StartServiceManagerCommand.java:190)
	at o.a.p.tools.Command.call(Command.java:33)
	at o.a.p.tools.Command.call(Command.java:29)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at o.a.p.tools.admin.PinotAdministrator.execute(PinotAdministrator.java:171)
	at o.a.p.tools.admin.PinotAdministrator.main(PinotAdministrator.java:202) 
Caused by: java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:579) ~[?:?]
	at sun.nio.ch.DatagramChannelImpl.connect(DatagramChannelImpl.java:1249) ~[?:?]
	at sun.nio.ch.DatagramSocketAdaptor.connectInternal(DatagramSocketAdaptor.java:91) ~[?:?]
	at sun.nio.ch.DatagramSocketAdaptor.connect(DatagramSocketAdaptor.java:118) ~[?:?]
	... 16 more
```

**Comment by Jackie-Jiang** [comment]
Which command did you use to start the node? `StartServiceManagerCommand` itself does not take host name, so host name is always read from the network and will error out when disconnected from network. If you use `StartControllerCommand` it should be able to pick the `-controllerHost` as the hostname without looking up the network

**Comment by soumyajitsamanta** [comment]
I had used 'StartService'.

**Comment by Jackie-Jiang** [comment]
Can you try using `StartControllerCommand` etc and see if the problem can be solved?

**Comment by soumyajitsamanta** [comment]
Yes from there I can run and get the cluster started. Had to provide hostname to all the scripts which are:
- start-broker.sh
- start-controller.sh
- start-server.sh
- start-service-manager.sh

Else they would try connect to IP and fail.

**Comment by Jackie-Jiang** [comment]
This is expected. When hostname is not provided, component has to find its public IP so that other components can find it

**Comment by soumyajitsamanta** [comment]
Closing since resolved.
