### ISSUE TITLE
UnsupportedOperationException when querying a converted dictionary -> noDictionary column

### ISSUE THREAD

**Issue by jadami10** [apache/pinot#11893]
We got to this error by
- initially creating a table and ingestion GB/TBs of data
- months later, we added a Json column and reloaded all segments
- months after that, we added the Json column to `noDictionaryColumns`

Now, any queries that hit that json column on segments that were created before the column existed see
```
QueryExecutionError:
  java.lang.UnsupportedOperationException
at org.apache.pinot.segment.spi.index.reader.ForwardIndexReader.getInt(ForwardIndexReader.java:372)
at org.apache.pinot.core.common.DataFetcher$ColumnValueReader.readStringValues(DataFetcher.java:576)
at org.apache.pinot.core.common.DataFetcher.fetchStringValues(DataFetcher.java:239)
at org.apache.pinot.core.common.DataBlockCache.getStringValuesForSVColumn(DataBlockCache.java:277)
```

If you query the table with `where <json_column> is NOT NULL`, then the queries do succeed. So there is at least a workaround.

This cluster is on a version of master from May 2023. I didn't see any issues/fixes related searching for elements in this stack trace.

**Comment by Jackie-Jiang** [comment]
From the stack trace, seems like it is caused by the index mismatching the segment metadata, where metadata stores the column as INT type, but the actual index is in a different type. Can you try doing a binary search on the segments (by applying filter on `$segmentName`) and see if this exception is thrown from all segments or just a few segments. Then we can find a bad segment, and try to find the mismatched column

**Comment by jadami10** [comment]
It's not all segments, just the ones where the column did not exist before it was added. I have an example of a server + segment. And I can clearly see in the `index_map` that `.dictionary.startOffset` and `.dictionary.size` are set. Reloading the segment doesn't change it. And `forceDownload` doesn't work because it's not supported for REALTIME tables.

**Comment by jadami10** [comment]
What's interesting is a new server that came online failed to similarly download the segment from deepstore. but resetting the segment then fixed it
```
[2023-10-31 15:05:01.898548] ERROR [SegmentOnlineOfflineStateModelFactory$SegmentOnlineOfflineStateModel] [HelixTaskExecutor-message_handle_thread_23:28] Caught exception in state transition from OFFLINE -> ONLINE for resource: <table_name>, partition: <segment_name>
[2023-10-31 15:05:01.898586] java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: Caught exception while adding segment: <segment_name>, table: <table_name>
[2023-10-31 15:05:01.898905] 	at org.apache.pinot.core.data.manager.realtime.RealtimeTableDataManager.downloadSegmentFromDeepStore(RealtimeTableDataManager.java:598) ~[pinot-all-0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-jar-with-dependencies.jar:0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-f4e5f3de37ca02168579691d45303db1129cb4a6]
[2023-10-31 15:05:01.898941] 	at org.apache.pinot.core.data.manager.realtime.RealtimeTableDataManager.downloadAndReplaceSegment(RealtimeTableDataManager.java:564) ~[pinot-all-0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-jar-with-dependencies.jar:0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-f4e5f3de37ca02168579691d45303db1129cb4a6]
[2023-10-31 15:05:01.898967] 	at org.apache.pinot.core.data.manager.realtime.RealtimeTableDataManager.addSegment(RealtimeTableDataManager.java:418) ~[pinot-all-0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-jar-with-dependencies.jar:0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-f4e5f3de37ca02168579691d45303db1129cb4a6]
[2023-10-31 15:05:01.898995] 	at org.apache.pinot.server.starter.helix.HelixInstanceDataManager.addRealtimeSegment(HelixInstanceDataManager.java:219) ~[pinot-all-0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-jar-with-dependencies.jar:0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-f4e5f3de37ca02168579691d45303db1129cb4a6]
[2023-10-31 15:05:01.899027] 	at org.apache.pinot.server.starter.helix.SegmentOnlineOfflineStateModelFactory$SegmentOnlineOfflineStateModel.onBecomeOnlineFromOffline(SegmentOnlineOfflineStateModelFactory.java:168) ~[pinot-all-0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-jar-with-dependencies.jar:0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-f4e5f3de37ca02168579691d45303db1129cb4a6]
[2023-10-31 15:05:01.899041] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
[2023-10-31 15:05:01.899056] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
[2023-10-31 15:05:01.899071] 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
[2023-10-31 15:05:01.899083] 	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
[2023-10-31 15:05:01.899116] 	at org.apache.helix.messaging.handling.HelixStateTransitionHandler.invoke(HelixStateTransitionHandler.java:350) ~[pinot-all-0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-jar-with-dependencies.jar:0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-f4e5f3de37ca02168579691d45303db1129cb4a6]
[2023-10-31 15:05:01.899152] 	at org.apache.helix.messaging.handling.HelixStateTransitionHandler.handleMessage(HelixStateTransitionHandler.java:278) ~[pinot-all-0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-jar-with-dependencies.jar:0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-f4e5f3de37ca02168579691d45303db1129cb4a6]
[2023-10-31 15:05:01.899175] 	at org.apache.helix.messaging.handling.HelixTask.call(HelixTask.java:97) ~[pinot-all-0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-jar-with-dependencies.jar:0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-f4e5f3de37ca02168579691d45303db1129cb4a6]
[2023-10-31 15:05:01.899202] 	at org.apache.helix.messaging.handling.HelixTask.call(HelixTask.java:49) ~[pinot-all-0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-jar-with-dependencies.jar:0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-f4e5f3de37ca02168579691d45303db1129cb4a6]
[2023-10-31 15:05:01.899224] 	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
[2023-10-31 15:05:01.899237] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
[2023-10-31 15:05:01.899250] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
[2023-10-31 15:05:01.899261] 	at java.lang.Thread.run(Thread.java:829) [?:?]
[2023-10-31 15:05:01.899294] Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Caught exception while adding segment: <segment_name>, table: <table_name>
[2023-10-31 15:05:01.899326] 	at org.apache.pinot.core.data.manager.realtime.RealtimeTableDataManager.replaceLLSegment(RealtimeTableDataManager.java:676) ~[pinot-all-0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-jar-with-dependencies.jar:0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-f4e5f3de37ca02168579691d45303db1129cb4a6]
[2023-10-31 15:05:01.899354] 	at org.apache.pinot.core.data.manager.realtime.RealtimeTableDataManager.untarAndMoveSegment(RealtimeTableDataManager.java:617) ~[pinot-all-0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-jar-with-dependencies.jar:0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-f4e5f3de37ca02168579691d45303db1129cb4a6]
[2023-10-31 15:05:01.899383] 	at org.apache.pinot.core.data.manager.realtime.RealtimeTableDataManager.downloadSegmentFromDeepStore(RealtimeTableDataManager.java:595) ~[pinot-all-0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-jar-with-dependencies.jar:0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-f4e5f3de37ca02168579691d45303db1129cb4a6]
[2023-10-31 15:05:01.899389] 	... 16 more
[2023-10-31 15:05:01.899411] Caused by: java.lang.RuntimeException: Caught exception while adding segment: <segment_name>, table: <table_name>
[2023-10-31 15:05:01.899440] 	at org.apache.pinot.segment.local.upsert.BasePartitionUpsertMetadataManager.doAddSegment(BasePartitionUpsertMetadataManager.java:147) ~[pinot-all-0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-jar-with-dependencies.jar:0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-f4e5f3de37ca02168579691d45303db1129cb4a6]
[2023-10-31 15:05:01.899466] 	at org.apache.pinot.segment.local.upsert.BasePartitionUpsertMetadataManager.addSegment(BasePartitionUpsertMetadataManager.java:101) ~[pinot-all-0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-jar-with-dependencies.jar:0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-f4e5f3de37ca02168579691d45303db1129cb4a6]
[2023-10-31 15:05:01.899497] 	at org.apache.pinot.core.data.manager.realtime.RealtimeTableDataManager.handleUpsert(RealtimeTableDataManager.java:536) ~[pinot-all-0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-jar-with-dependencies.jar:0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-f4e5f3de37ca02168579691d45303db1129cb4a6]
[2023-10-31 15:05:01.899528] 	at org.apache.pinot.core.data.manager.realtime.RealtimeTableDataManager.addSegment(RealtimeTableDataManager.java:493) ~[pinot-all-0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-jar-with-dependencies.jar:0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-f4e5f3de37ca02168579691d45303db1129cb4a6]
[2023-10-31 15:05:01.899560] 	at org.apache.pinot.core.data.manager.BaseTableDataManager.addSegment(BaseTableDataManager.java:231) ~[pinot-all-0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-jar-with-dependencies.jar:0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-f4e5f3de37ca02168579691d45303db1129cb4a6]
[2023-10-31 15:05:01.899585] 	at org.apache.pinot.core.data.manager.realtime.RealtimeTableDataManager.replaceLLSegment(RealtimeTableDataManager.java:674) ~[pinot-all-0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-jar-with-dependencies.jar:0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-f4e5f3de37ca02168579691d45303db1129cb4a6]
[2023-10-31 15:05:01.899616] 	at org.apache.pinot.core.data.manager.realtime.RealtimeTableDataManager.untarAndMoveSegment(RealtimeTableDataManager.java:617) ~[pinot-all-0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-jar-with-dependencies.jar:0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-f4e5f3de37ca02168579691d45303db1129cb4a6]
[2023-10-31 15:05:01.899647] 	at org.apache.pinot.core.data.manager.realtime.RealtimeTableDataManager.downloadSegmentFromDeepStore(RealtimeTableDataManager.java:595) ~[pinot-all-0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-jar-with-dependencies.jar:0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-f4e5f3de37ca02168579691d45303db1129cb4a6]
[2023-10-31 15:05:01.899656] 	... 16 more
[2023-10-31 15:05:01.899669] Caused by: java.lang.UnsupportedOperationException
[2023-10-31 15:05:01.899703] 	at org.apache.pinot.segment.spi.index.reader.ForwardIndexReader.getInt(ForwardIndexReader.java:372) ~[pinot-all-0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-jar-with-dependencies.jar:0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-f4e5f3de37ca02168579691d45303db1129cb4a6]
[2023-10-31 15:05:01.899742] 	at org.apache.pinot.segment.local.segment.readers.PinotSegmentColumnReader.getValue(PinotSegmentColumnReader.java:111) ~[pinot-all-0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-jar-with-dependencies.jar:0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-f4e5f3de37ca02168579691d45303db1129cb4a6]
[2023-10-31 15:05:01.899766] 	at org.apache.pinot.segment.local.upsert.UpsertUtils.getValue(UpsertUtils.java:150) ~[pinot-all-0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-jar-with-dependencies.jar:0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-f4e5f3de37ca02168579691d45303db1129cb4a6]
[2023-10-31 15:05:01.899803] 	at org.apache.pinot.segment.local.upsert.UpsertUtils$PrimaryKeyReader.getPrimaryKey(UpsertUtils.java:127) ~[pinot-all-0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-jar-with-dependencies.jar:0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-f4e5f3de37ca02168579691d45303db1129cb4a6]
[2023-10-31 15:05:01.899832] 	at org.apache.pinot.segment.local.upsert.UpsertUtils$RecordInfoReader.getRecordInfo(UpsertUtils.java:101) ~[pinot-all-0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-jar-with-dependencies.jar:0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-f4e5f3de37ca02168579691d45303db1129cb4a6]
[2023-10-31 15:05:01.899857] 	at org.apache.pinot.segment.local.upsert.UpsertUtils$1.next(UpsertUtils.java:53) ~[pinot-all-0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-jar-with-dependencies.jar:0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-f4e5f3de37ca02168579691d45303db1129cb4a6]
[2023-10-31 15:05:01.899886] 	at org.apache.pinot.segment.local.upsert.UpsertUtils$1.next(UpsertUtils.java:43) ~[pinot-all-0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-jar-with-dependencies.jar:0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-f4e5f3de37ca02168579691d45303db1129cb4a6]
[2023-10-31 15:05:01.899925] 	at org.apache.pinot.segment.local.upsert.ConcurrentMapPartitionUpsertMetadataManager.addOrReplaceSegment(ConcurrentMapPartitionUpsertMetadataManager.java:80) ~[pinot-all-0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-jar-with-dependencies.jar:0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-f4e5f3de37ca02168579691d45303db1129cb4a6]
[2023-10-31 15:05:01.899954] 	at org.apache.pinot.segment.local.upsert.BasePartitionUpsertMetadataManager.addSegment(BasePartitionUpsertMetadataManager.java:172) ~[pinot-all-0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-jar-with-dependencies.jar:0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-f4e5f3de37ca02168579691d45303db1129cb4a6]
[2023-10-31 15:05:01.899982] 	at org.apache.pinot.segment.local.upsert.BasePartitionUpsertMetadataManager.doAddSegment(BasePartitionUpsertMetadataManager.java:144) ~[pinot-all-0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-jar-with-dependencies.jar:0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-f4e5f3de37ca02168579691d45303db1129cb4a6]
[2023-10-31 15:05:01.900020] 	at org.apache.pinot.segment.local.upsert.BasePartitionUpsertMetadataManager.addSegment(BasePartitionUpsertMetadataManager.java:101) ~[pinot-all-0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-jar-with-dependencies.jar:0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-f4e5f3de37ca02168579691d45303db1129cb4a6]
[2023-10-31 15:05:01.900057] 	at org.apache.pinot.core.data.manager.realtime.RealtimeTableDataManager.handleUpsert(RealtimeTableDataManager.java:536) ~[pinot-all-0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-jar-with-dependencies.jar:0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-f4e5f3de37ca02168579691d45303db1129cb4a6]
[2023-10-31 15:05:01.900089] 	at org.apache.pinot.core.data.manager.realtime.RealtimeTableDataManager.addSegment(RealtimeTableDataManager.java:493) ~[pinot-all-0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-jar-with-dependencies.jar:0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-f4e5f3de37ca02168579691d45303db1129cb4a6]
[2023-10-31 15:05:01.900120] 	at org.apache.pinot.core.data.manager.BaseTableDataManager.addSegment(BaseTableDataManager.java:231) ~[pinot-all-0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-jar-with-dependencies.jar:0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-f4e5f3de37ca02168579691d45303db1129cb4a6]
[2023-10-31 15:05:01.900149] 	at org.apache.pinot.core.data.manager.realtime.RealtimeTableDataManager.replaceLLSegment(RealtimeTableDataManager.java:674) ~[pinot-all-0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-jar-with-dependencies.jar:0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-f4e5f3de37ca02168579691d45303db1129cb4a6]
[2023-10-31 15:05:01.900178] 	at org.apache.pinot.core.data.manager.realtime.RealtimeTableDataManager.untarAndMoveSegment(RealtimeTableDataManager.java:617) ~[pinot-all-0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-jar-with-dependencies.jar:0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-f4e5f3de37ca02168579691d45303db1129cb4a6]
[2023-10-31 15:05:01.900214] 	at org.apache.pinot.core.data.manager.realtime.RealtimeTableDataManager.downloadSegmentFromDeepStore(RealtimeTableDataManager.java:595) ~[pinot-all-0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-jar-with-dependencies.jar:0.13.0-2023-07-21-f4e5f3de37-SNAPSHOT-f4e5f3de37ca02168579691d45303db1129cb4a6]
[2023-10-31 15:05:01.900220] 	... 16 more
```

**Comment by shounakmk219** [comment]
Hey @jadami10 , I tried to follow the mentioned steps with the latest master and was not able to reproduce the issue. 
Would like to get some more context on this. 

> And I can clearly see in the index_map that .dictionary.startOffset and .dictionary.size are set

From my observations the older segments which didn’t had the new column, end up having null value for that column and stay on the dictionary encoding as its marked as a sorted column. Changing to no dict will not have effect on such segments.

Regarding the error
```
QueryExecutionError:
  java.lang.UnsupportedOperationException
at org.apache.pinot.segment.spi.index.reader.ForwardIndexReader.getInt(ForwardIndexReader.java:372)
at org.apache.pinot.core.common.DataFetcher$ColumnValueReader.readStringValues(DataFetcher.java:576)
at org.apache.pinot.core.common.DataFetcher.fetchStringValues(DataFetcher.java:239)
at org.apache.pinot.core.common.DataBlockCache.getStringValuesForSVColumn(DataBlockCache.java:277)
```
[This code path](https://github.com/apache/pinot/blob/master/pinot-core/src/main/java/org/apache/pinot/core/common/DataFetcher.java#L391) should be taken when [dictionary is not enabled](https://github.com/apache/pinot/blob/master/pinot-core/src/main/java/org/apache/pinot/core/common/DataFetcher.java#L383) on a column so most probably this error log is coming while accessing the newer segments which have no dictionary on the column.

**Comment by jadami10** [comment]
unfortunately this issue is all the context I have as the table has long since retentioned any data that did not have that column

**Comment by shounakmk219** [comment]
I see. I will try to test out few hypothesis to repro this with the old code as well. 
Also wanted to confirm if this issue was seen on just one table or do you remember any reoccurrence with similar operations on other tables back then?

**Comment by jadami10** [comment]
we only saw it on this 1 table. So I've assumed it's somewhat tied to JSON columns
