### ISSUE TITLE
flaky test on org.apache.pinot.core.operator.combine.SelectionCombineOperatorTest

### ISSUE THREAD

**Issue by xiangfu0** [apache/pinot#11957]
```
Error:  Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 3.336 s <<< FAILURE! -- in org.apache.pinot.core.operator.combine.SelectionCombineOperatorTest
Error:  org.apache.pinot.core.operator.combine.SelectionCombineOperatorTest.testSelectionLimit0 -- Time elapsed: 0.736 s
Error:  org.apache.pinot.core.operator.combine.SelectionCombineOperatorTest.testSelectionOnly -- Time elapsed: 0.025 s
Error:  org.apache.pinot.core.operator.combine.SelectionCombineOperatorTest.testSelectionOrderBy -- Time elapsed: 0.030 s <<< FAILURE!
java.lang.AssertionError: expected [2] but found [1]
	at org.testng.Assert.fail(Assert.java:111)
	at org.testng.Assert.failNotEquals(Assert.java:1578)
	at org.testng.Assert.assertEqualsImpl(Assert.java:150)
	at org.testng.Assert.assertEquals(Assert.java:132)
	at org.testng.Assert.assertEquals(Assert.java:1419)
	at org.testng.Assert.assertEquals(Assert.java:1383)
	at org.testng.Assert.assertEquals(Assert.java:1429)
	at org.apache.pinot.core.operator.combine.SelectionCombineOperatorTest.testSelectionOrderBy(SelectionCombineOperatorTest.java:264)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at org.testng.TestRunner.privateRun(TestRunner.java:848)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
	at org.testng.SuiteRunner.run(SuiteRunner.java:336)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
	at org.testng.TestNG.runSuites(TestNG.java:1114)
	at org.testng.TestNG.run(TestNG.java:1082)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:155)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:102)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:91)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:137)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
```

https://github.com/apache/pinot/actions/runs/6778780506/job/18424808961?pr=11857
https://github.com/apache/pinot/actions/runs/6778780506/job/18424809481?pr=11857

**Comment by xiangfu0** [comment]
https://github.com/apache/pinot/actions/runs/6789919525/job/18458165173?pr=11961

**Comment by xiangfu0** [comment]
I feel this is introduced by: https://github.com/apache/pinot/pull/9122
You can add a for loop 1000 times for method `SelectionCombineOperatorTest.testSelectionOrderBy()` to reproduce this error.

@ravishankar15 @jackjlli @siddharthteotia

**Comment by xiangfu0** [comment]
fixed : https://github.com/apache/pinot/pull/11963
