### ISSUE TITLE
IndexOutOfBoundsException is thrown when gathering stats for previously compacted segment

### ISSUE THREAD

**Issue by robertzych** [apache/pinot#12301]
When the table config contains an empty `noDictionaryColumns` list, an `IndexOutOfBoundsException` is raised during compaction when gathering stats for a previously compacted segment. 

```
Caught exception while gathering stats
java.lang.IndexOutOfBoundsException: null
    at java.nio.Buffer.checkIndex(Buffer.java:687) ~[?:?]
    at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:269) ~[?:?]
    at org.apache.pinot.segment.spi.memory.PinotByteBuffer.getByte(PinotByteBuffer.java:71) ~[pinot-all-1.1.0-SNAPSHOT-jar-with-dependencies.jar:1.1.0-SNAPSHOT-f22de0a4be910af09556666df3aa44ae78d59187]
    at org.apache.pinot.segment.local.io.reader.impl.FixedBitIntReader$Bit3Reader.read(FixedBitIntReader.java:253) ~[pinot-all-1.1.0-SNAPSHOT-jar-with-dependencies.jar:1.1.0-SNAPSHOT-f22de0a4be910af09556666df
    at org.apache.pinot.segment.local.segment.index.readers.forward.FixedBitSVForwardIndexReaderV2.getDictId(FixedBitSVForwardIndexReaderV2.java:61) ~[pinot-all-1.1.0-SNAPSHOT-jar-with-dependencies.jar:1.1.0-
    at org.apache.pinot.segment.local.segment.readers.PinotSegmentColumnReader.getValue(PinotSegmentColumnReader.java:96) ~[pinot-all-1.1.0-SNAPSHOT-jar-with-dependencies.jar:1.1.0-SNAPSHOT-f22de0a4be910af095
    at org.apache.pinot.segment.local.segment.readers.PinotSegmentRecordReader.getRecord(PinotSegmentRecordReader.java:227) ~[pinot-all-1.1.0-SNAPSHOT-jar-with-dependencies.jar:1.1.0-SNAPSHOT-f22de0a4be910af0
    at org.apache.pinot.plugin.minion.tasks.upsertcompaction.UpsertCompactionTaskExecutor$CompactedRecordReader.hasNext(UpsertCompactionTaskExecutor.java:99) ~[pinot-all-1.1.0-SNAPSHOT-jar-with-dependencies.j
    at org.apache.pinot.segment.local.segment.creator.RecordReaderSegmentCreationDataSource.gatherStats(RecordReaderSegmentCreationDataSource.java:63) [pinot-all-1.1.0-SNAPSHOT-jar-with-dependencies.jar:1.1.0
    at org.apache.pinot.segment.local.segment.creator.RecordReaderSegmentCreationDataSource.gatherStats(RecordReaderSegmentCreationDataSource.java:37) [pinot-all-1.1.0-SNAPSHOT-jar-with-dependencies.jar:1.1.0
    at org.apache.pinot.segment.local.segment.creator.impl.SegmentIndexCreationDriverImpl.init(SegmentIndexCreationDriverImpl.java:188) [pinot-all-1.1.0-SNAPSHOT-jar-with-dependencies.jar:1.1.0-SNAPSHOT-f22de
    at org.apache.pinot.segment.local.segment.creator.impl.SegmentIndexCreationDriverImpl.init(SegmentIndexCreationDriverImpl.java:160) [pinot-all-1.1.0-SNAPSHOT-jar-with-dependencies.jar:1.1.0-SNAPSHOT-f22de
    at org.apache.pinot.plugin.minion.tasks.upsertcompaction.UpsertCompactionTaskExecutor.convert(UpsertCompactionTaskExecutor.java:165) [pinot-all-1.1.0-SNAPSHOT-jar-with-dependencies.jar:1.1.0-SNAPSHOT-f22d
    at org.apache.pinot.plugin.minion.tasks.BaseSingleSegmentConversionExecutor.executeTask(BaseSingleSegmentConversionExecutor.java:129) [pinot-all-1.1.0-SNAPSHOT-jar-with-dependencies.jar:1.1.0-SNAPSHOT-f22
    at org.apache.pinot.plugin.minion.tasks.BaseSingleSegmentConversionExecutor.executeTask(BaseSingleSegmentConversionExecutor.java:60) [pinot-all-1.1.0-SNAPSHOT-jar-with-dependencies.jar:1.1.0-SNAPSHOT-f22d
    at org.apache.pinot.minion.taskfactory.TaskFactoryRegistry$1.runInternal(TaskFactoryRegistry.java:157) [pinot-all-1.1.0-SNAPSHOT-jar-with-dependencies.jar:1.1.0-SNAPSHOT-f22de0a4be910af09556666df3aa44ae78
    at org.apache.pinot.minion.taskfactory.TaskFactoryRegistry$1.run(TaskFactoryRegistry.java:118) [pinot-all-1.1.0-SNAPSHOT-jar-with-dependencies.jar:1.1.0-SNAPSHOT-f22de0a4be910af09556666df3aa44ae78d59187]
    at org.apache.helix.task.TaskRunner.run(TaskRunner.java:75) [pinot-all-1.1.0-SNAPSHOT-jar-with-dependencies.jar:1.1.0-SNAPSHOT-f22de0a4be910af09556666df3aa44ae78d59187]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
    at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
    at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Comment by robertzych** [comment]
Resolved by #12329
