### ISSUE TITLE
[Flaky test] MultiStageEngineCustomTenantIntegrationTest.testGeneratedQueries()

### ISSUE THREAD

**Issue by Jackie-Jiang** [apache/pinot#12368]
```
Error:  org.apache.pinot.integration.tests.MultiStageEngineCustomTenantIntegrationTest.testGeneratedQueries -- Time elapsed: 14.29 s <<< FAILURE!
java.lang.AssertionError: 
Caught exception while testing query!
Pinot query: SELECT "ArrTime", "WheelsOff", "Cancelled" FROM mytable WHERE "OriginAirportID" > 12177 OR "TaxiIn" BETWEEN 47 AND 70 AND "FlightNum" = 1077 LIMIT 10000
H2 query: SELECT `ArrTime`, `WheelsOff`, `Cancelled` FROM mytable WHERE `OriginAirportID` > 12177 OR `TaxiIn` BETWEEN 47 AND 70 AND `FlightNum` = 1077 LIMIT 10000
	at org.testng.Assert.fail(Assert.java:99)
	at org.apache.pinot.integration.tests.ClusterIntegrationTestUtils.failure(ClusterIntegrationTestUtils.java:1076)
	at org.apache.pinot.integration.tests.ClusterIntegrationTestUtils.failure(ClusterIntegrationTestUtils.java:1060)
	at org.apache.pinot.integration.tests.ClusterIntegrationTestUtils.testQuery(ClusterIntegrationTestUtils.java:699)
	at org.apache.pinot.integration.tests.BaseClusterIntegrationTest.testQuery(BaseClusterIntegrationTest.java:739)
	at org.apache.pinot.integration.tests.BaseClusterIntegrationTestSet.testGeneratedQueries(BaseClusterIntegrationTestSet.java:485)
	at org.apache.pinot.integration.tests.MultiStageEngineIntegrationTest.testGeneratedQueries(MultiStageEngineIntegrationTest.java:132)
Caused by: org.apache.pinot.client.PinotClientException: Query had processing exceptions: 
[{"errorCode":200,"message":"QueryExecutionError:\nReceived error query execution result block: {450=InternalError:\njava.util.ConcurrentModificationException\n\tat java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1043)\n\tat java.base/java.util.ArrayList$Itr.next(ArrayList.java:997)\n\tat org.apache.pinot.core.operator.docidsets.AndDocIdSet.getNumEntriesScannedInFilter(AndDocIdSet.java:189)\n\tat org.apache.pinot.core.operator.docidsets.OrDocIdSet.getNumEntriesScannedInFilter(OrDocIdSet.java:131)}\norg.apache.pinot.query.service.dispatch.QueryDispatcher.getResultTable(QueryDispatcher.java:315)\norg.apache.pinot.query.service.dispatch.QueryDispatcher.runReducer(QueryDispatcher.java:255)\norg.apache.pinot.query.service.dispatch.QueryDispatcher.submitAndReduce(QueryDispatcher.java:99)\norg.apache.pinot.broker.requesthandler.MultiStageBrokerRequestHandler.handleRequest(MultiStageBrokerRequestHandler.java:191)\n"}]
	at org.apache.pinot.client.Connection.execute(Connection.java:103)
	at org.apache.pinot.client.Connection.execute(Connection.java:83)
	at org.apache.pinot.integration.tests.ClusterIntegrationTestUtils.testQueryInternal(ClusterIntegrationTestUtils.java:736)
	at org.apache.pinot.integration.tests.ClusterIntegrationTestUtils.testQuery(ClusterIntegrationTestUtils.java:696)
	... 36 more
```

**Comment by Jackie-Jiang** [comment]
Might be related to #11200. @jasperjiaguo Can you help take a look?
