### ISSUE TITLE
Flaky Test: PartialUpsertTableRebalanceIntegrationTest

### ISSUE THREAD

**Issue by ankitsultana** [apache/pinot#12412]
Seeing this occasionally. Maybe 60s is not enough for the rebalance to converge.

```
Error:  Tests run: 5, Failures: 1, Errors: 0, Skipped: 3, Time elapsed: 86.82 s <<< FAILURE! -- in org.apache.pinot.integration.tests.PartialUpsertTableRebalanceIntegrationTest
Error:  org.apache.pinot.integration.tests.PartialUpsertTableRebalanceIntegrationTest.testRebalance -- Time elapsed: 10.94 s
Error:  org.apache.pinot.integration.tests.PartialUpsertTableRebalanceIntegrationTest.afterMethod -- Time elapsed: 70.99 s <<< FAILURE!
java.lang.AssertionError: Failed to meet condition in 60000ms, error message: Failed to drop the segments
	at org.testng.Assert.fail(Assert.java:111)
	at org.apache.pinot.util.TestUtils.waitForCondition(TestUtils.java:111)
	at org.apache.pinot.util.TestUtils.waitForCondition(TestUtils.java:88)
	at org.apache.pinot.util.TestUtils.waitForCondition(TestUtils.java:93)
	at org.apache.pinot.integration.tests.PartialUpsertTableRebalanceIntegrationTest.afterMethod(PartialUpsertTableRebalanceIntegrationTest.java:192)
```

**Comment by Jackie-Jiang** [comment]
cc @KKcorps @klsince
