### ISSUE TITLE
TimeSegmentPruner exception based on query and schema datetime column format

### ISSUE THREAD

**Issue by jadami10** [apache/pinot#12721]
We have the following datetime column in our schema
```
date_time_field_specs:
- name: created
   data_type: TIMESTAMP
   format: 1:MILLISECONDS:EPOCH
   granularity: 1:HOURS
```
The pinot [schema docs](https://docs.pinot.apache.org/configuration-reference/schema) are vary confusing and vague, but this is seemingly an allowed way to configure the column.

When we try to query the table with the time pruner enabled and a `where created between '2024-03-22 16:18:51.000' and '2024-03-22 21:37:41.000'` clause, the broker fails with the following stacktrace.
```
java.lang.NumberFormatException: Character array is missing "e" notation exponential mark.
	at java.math.BigDecimal.<init>(BigDecimal.java:581) ~[?:?]
	at java.math.BigDecimal.<init>(BigDecimal.java:405) ~[?:?]
	at java.math.BigDecimal.<init>(BigDecimal.java:838) ~[?:?]
	at org.apache.pinot.spi.data.DateTimeFormatSpec.fromFormatToMillis(DateTimeFormatSpec.java:305) 
 	at org.apache.pinot.broker.routing.segmentpruner.TimeSegmentPruner.getFilterTimeIntervals(TimeSegmentPruner.java:281) 
 	at org.apache.pinot.broker.routing.segmentpruner.TimeSegmentPruner.getFilterTimeIntervals(TimeSegmentPruner.java:178) 
 	at org.apache.pinot.broker.routing.segmentpruner.TimeSegmentPruner.prune(TimeSegmentPruner.java:138) 
 	at org.apache.pinot.broker.routing.BrokerRoutingManager$RoutingEntry.calculateRouting(BrokerRoutingManager.java:788) 
 	at org.apache.pinot.broker.routing.BrokerRoutingManager.getRoutingTable(BrokerRoutingManager.java:612) 
 	at org.apache.pinot.broker.requesthandler.BaseBrokerRequestHandler.handleRequest(BaseBrokerRequestHandler.java:593) 
 	at org.apache.pinot.broker.requesthandler.BaseBrokerRequestHandler.handleRequest(BaseBrokerRequestHandler.java:263) 
 	at org.apache.pinot.broker.requesthandler.BrokerRequestHandlerDelegate.handleRequest(BrokerRequestHandlerDelegate.java:107) 
 	at org.apache.pinot.broker.api.resources.PinotClientRequest.executeSqlQuery(PinotClientRequest.java:317) 
 	at org.apache.pinot.broker.api.resources.PinotClientRequest.executeSqlQuery(PinotClientRequest.java:294) 
 	at org.apache.pinot.broker.api.resources.PinotClientRequest.processSqlQueryPost(PinotClientRequest.java:157) 
```

It seems related to the fact that `EPOCH` is parsed [one way](https://github.com/apache/pinot/blob/0a08a919ea6122212a1b2963de1f40cee84f6742/pinot-spi/src/main/java/org/apache/pinot/spi/data/DateTimeFormatSpec.java#L276-L277) and [timestamp](https://github.com/apache/pinot/blob/0a08a919ea6122212a1b2963de1f40cee84f6742/pinot-spi/src/main/java/org/apache/pinot/spi/data/DateTimeFormatSpec.java#L278-L279) a totally different way.

Changing the format to `1:MILLISECONDS:TIMESTAMP` allows the query to succeed.

Overall there's several issues here

- [ ] Failing timestamp parsing in the `TimeSegmentPruner` can fail the whole query. This should not be allowed for something that's supposed to be an optimization
- [ ] `1:MILLISECONDS:TIMESTAMP` is specifically allowed in code, but it's not documented anywhere. Should it be used? Is it valid? Is it what we want here?
- [x] `1:MILLISECONDS:EPOCH` cannot parse `yyyy-mm-dd hh:mm:ss[.fffffffff]` correctly
- [ ] I'm fairly certain `5:HOURS:TIMESTAMP` would be a valid format, but it just always ignore the `5`

**Comment by jadami10** [comment]
cc @Jackie-Jiang since you've touched a lot of the pruner code recently.

Does it make sense to have the pruner do
```
try {
  prune()
} catch {
  return null
}
```
or are there issues you foresee here? I do think it was extremely surprising for us to add the time pruner and suddenly see all queries fail.

**Comment by Jackie-Jiang** [comment]
It is documented here: https://docs.pinot.apache.org/configuration-reference/schema#datetimefieldspec
The root cause is that time value and format doesn't match. We cannot detect that upfront without having the values available, thus not able fail the schema validation. We can potentially not fail the query if the pruning logic throws exception, but it will still throw exception if this column is used as time column (not sure if it can fail in other places). For timestamp value, the format should be `TIMESTAMP`. We can add a validation for timestamp data type.

**Comment by jadami10** [comment]
between the new/old formats, https://docs.pinot.apache.org/configuration-reference/schema#new-datetime-formats, `1:MILLISECONDS:TIMESTAMP` isn't mentioned anywhere. Though if I read it correctly, just `TIMESTAMP` should work?

Interestingly, this was/is being used as the tables time column with no issue. Adding the time pruner was the first thing that broke. I can send out a PR to at least prevent the time pruner from failing the query.

**Comment by jadami10** [comment]
also to provide more concrete feedback for the schema docs, https://docs.pinot.apache.org/configuration-reference/schema, there are ~1700 words on that page and all of 1 schema with 6 columns worth of examples. The DateTimeFieldSpec documentation is over 1/2 of the content, and there's only 3 examples. It's hard to confidently put together a Pinot schema with only a description of the spec. Ideally there's a clear table with:
- here is the configuration
- this is the data format it's intended to support

**Comment by Jackie-Jiang** [comment]
@kelseiv Can you please take a look at the feedback from @jadami10 about the schema doc?
