### ISSUE TITLE
Fix Lucene text index realtime to offline conversion

### ISSUE THREAD

**Issue by SabrinaZhaozyf** [apache/pinot#13039]
We have observed `java.io.FileNotFoundException` after https://github.com/apache/pinot/pull/12744 when converting the mutable lucene text index. 

Specifically, the path generated by [getMutableIndexDir](https://github.com/apache/pinot/blob/087fca37d03bf18930ecaad55b2955ef5d20ecac/pinot-segment-local/src/main/java/org/apache/pinot/segment/local/segment/creator/impl/text/LuceneTextIndexCreator.java#L337) does not point to the existing mutable index.

```
ERROR [RealtimeSegmentDataManager_RealtimeFeatureTest1__0__0__20240423T1743Z] [RealtimeFeatureTest1__0__0__20240423T1743Z] [pinot-server] [] Could not build segment
java.lang.RuntimeException: Caught exception while instantiating the LuceneTextIndexCreator for column: textDim1
        at org.apache.pinot.segment.local.segment.creator.impl.text.LuceneTextIndexCreator.<init>(LuceneTextIndexCreator.java:147
...
Caused by: java.lang.RuntimeException: Failed to convert the mutable lucene index: java.io.FileNotFoundException: Directory '<path-to-dataDir>/dataDir/RealtimeFeatureTest1_REALTIME/consumers/RealtimeFeatureTest1__0__0__20240423T1743Z/textDim1.lucene.v9.index' does not exist.
    at org.apache.pinot.segment.local.segment.creator.impl.text.LuceneTextIndexCreator.convertMutableSegment(LuceneTextIndexCreator.java:190)
    at org.apache.pinot.segment.local.segment.creator.impl.text.LuceneTextIndexCreator.<init>(LuceneTextIndexCreator.java:137)
```

`getMutableIndexDir` works for [paths where there's no consumer dir configured](https://github.com/apache/pinot/blob/bf28a83958e069f868e794f4a5271328d5a5f525/pinot-core/src/main/java/org/apache/pinot/core/data/manager/realtime/RealtimeTableDataManager.java#L348). However, it does not work when consumer dir is configured. Ideally, the path should align with [getConsumerDir](https://github.com/apache/pinot/blob/bf28a83958e069f868e794f4a5271328d5a5f525/pinot-core/src/main/java/org/apache/pinot/core/data/manager/realtime/RealtimeTableDataManager.java#L340)

cc @itschrispeck @chenboat

**Comment by stationeros** [comment]
Can this be assigned to me ?

**Comment by itschrispeck** [comment]
Hey @stationeros - sorry, but I felt a bit responsible for introducing this bug and have raised a fix to unblock others.

**Comment by hpvd** [comment]
@SabrinaZhaozyf is the merged bugfix solving this issue for you?
