### ISSUE TITLE
not able to compile version 0.12.1 with java sdk 8

### ISSUE THREAD

**Issue by pankajagarwal** [apache/pinot#13194]
hi there,

I am trying to compile the pinot version 0.12.1 with java version 8 as AWS GLUE only supports java version 8.

i tried to compile the complete project which fails at pinot controller build with type script error like these.

`
[INFO] ERROR in /Users/redacted/Downloads/apache-pinot-0.12.1-src/pinot-controller/src/main/resources/node_modules/@types/node/crypto.d.ts
[INFO] [tsl] ERROR in /Users/redacted/Downloads/apache-pinot-0.12.1-src/pinot-controller/src/main/resources/node_modules/@types/node/crypto.d.ts(3568,17)
[INFO]       TS1110: Type expected.
[INFO] 
[INFO] ERROR in /Users/redacted/Downloads/apache-pinot-0.12.1-src/pinot-controller/src/main/resources/node_modules/@types/node/events.d.ts
[INFO] [tsl] ERROR in /Users/redacted/Downloads/apache-pinot-0.12.1-src/pinot-controller/src/main/resources/node_modules/@types/node/events.d.ts(84,28)
[INFO]       TS1005: ',' expected.
[INFO] 
[INFO] ERROR in /Users/redacted/Downloads/apache-pinot-0.12.1-src/pinot-controller/src/main/resources/node_modules/@types/node/test.d.ts
[INFO] [tsl] ERROR in /Users/redacted/Downloads/apache-pinot-0.12.1-src/pinot-controller/src/main/resources/node_modules/@types/node/test.d.ts(882,34)
[INFO]       TS1005: '?' expected.
[INFO] 
[INFO] ERROR in /Users/redacted/Downloads/apache-pinot-0.12.1-src/pinot-controller/src/main/resources/node_modules/@types/node/test.d.ts
[INFO] [tsl] ERROR in /Users/redacted/Downloads/apache-pinot-0.12.1-src/pinot-controller/src/main/resources/node_modules/@types/node/test.d.ts(882,63)
[INFO]       TS1005: ':' expected.
[INFO] 
[INFO] ERROR in /Users/redacted/Downloads/apache-pinot-0.12.1-src/pinot-controller/src/main/resources/node_modules/@types/node/test.d.ts
[INFO] [tsl] ERROR in /Users/redacted/Downloads/apache-pinot-0.12.1-src/pinot-controller/src/main/resources/node_modules/@types/node/test.d.ts(883,13)
[INFO]       TS1005: ',' expected.
[INFO] 
[INFO] ERROR in /Users/redacted/Downloads/apache-pinot-0.12.1-src/pinot-controller/src/main/resources/node_modules/@types/node/test.d.ts
[INFO] [tsl] ERROR in /Users/redacted/Downloads/apache-pinot-0.12.1-src/pinot-controller/src/main/resources/node_modules/@types/node/test.d.ts(885,34)
[INFO]       TS1005: '?' expected.
`
the command i used for above error is this ...

`mvn install package -DskipTests -Pbin-dist -DdownloadSources -DdownloadJavadocs -Djdk.version=8 -Dcheckstyle.skip  -Drat.numUnapprovedLicenses=1000`

I then tried to just compile the connectors using this command ..

`mvn -pl pinot-connectors -amd clean install package -DskipTests -Pbin-dist -Djdk.version=8`

that also is failing with this error ...

`
[INFO] 
[INFO]   last tree to typer: Ident(TableType)
[INFO]        tree position: line 149 of /Users/redacted/Downloads/apache-pinot-0.12.1-src/pinot-connectors/pinot-spark-connector/src/main/scala/org/apache/pinot/connector/spark/connector/PinotClusterClient.scala
[INFO]               symbol: <none>
[INFO]    symbol definition: <none> (a NoSymbol)
[INFO]       symbol package: <none>
[INFO]        symbol owners:
[INFO]            call site: method getRoutingTable in object PinotClusterClient in package connector
[INFO] 
[INFO] == Source file context for tree position ==
[INFO] 
[INFO]    146    */
[INFO]    147   def getRoutingTable(
[INFO]    148       brokerUrl: String,
[INFO]    149       generatedSQLs: GeneratedSQLs): Map[TableType, Map[String, List[String]]] = {
[INFO]    150     val routingTables =
[INFO]    151       if (generatedSQLs.isTableOffline) {
[INFO]    152         val offlineRoutingTable =
[ERROR] error: scala.reflect.internal.FatalError:
[INFO]   bad constant pool index: 0 at pos: 944
[INFO]      while compiling: /Users/redacted/Downloads/apache-pinot-0.12.1-src/pinot-connectors/pinot-spark-connector/src/main/scala/org/apache/pinot/connector/spark/connector/PinotClusterClient.scala
[INFO]         during phase: globalPhase=typer, enteringPhase=namer
[INFO]      library version: version 2.12.11
[INFO]     compiler version: version 2.12.11

[INFO]   last tree to typer: Ident(TableType)
[INFO]        tree position: line 149 of /Users/redacted/Downloads/apache-pinot-0.12.1-src/pinot-connectors/pinot-spark-connector/src/main/scala/org/apache/pinot/connector/spark/connector/PinotClusterClient.scala
[INFO]               symbol: <none>
[INFO]    symbol definition: <none> (a NoSymbol)
[INFO]       symbol package: <none>
[INFO]        symbol owners:
[INFO]            call site: method getRoutingTable in object PinotClusterClient in package connector
[INFO] 
[INFO] == Source file context for tree position ==
[INFO] 
[INFO]    146    */
[INFO]    147   def getRoutingTable(
[INFO]    148       brokerUrl: String,
[INFO]    149       generatedSQLs: GeneratedSQLs): Map[TableType, Map[String, List[String]]] = {
[INFO]    150     val routingTables =
[INFO]    151       if (generatedSQLs.isTableOffline) {
[INFO]    152         val offlineRoutingTable =
[INFO] 	at scala.reflect.internal.Reporting.abort(Reporting.scala:68)
[INFO] 	at scala.reflect.internal.Reporting.abort$(Reporting.scala:64)
[INFO] 	at scala.reflect.internal.SymbolTable.abort(SymbolTable.scala:28)
[ERROR] 	at scala.tools.nsc.symtab.classfile.ClassfileParser$ConstantPool.errorBadIndex(ClassfileParser.scala:384)
[ERROR] 	at scala.tools.nsc.symtab.classfile.ClassfileParser$ConstantPool.getExternalName(ClassfileParser.scala:248)
[ERROR] 	at scala.tools.nsc.symtab.classfile.ClassfileParser.readParamNames$1(ClassfileParser.scala:840)
[ERROR] 	at scala.tools.nsc.symtab.classfile.ClassfileParser.parseAttribute$1(ClassfileParser.scala:846)
[ERROR] 	at scala.tools.nsc.symtab.classfile.ClassfileParser.$anonfun$parseAttributes$7(ClassfileParser.scala:913)
[ERROR] 	at scala.tools.nsc.symtab.classfile.ClassfileParser.parseAttributes(ClassfileParser.scala:913)
[ERROR] 	at scala.tools.nsc.symtab.classfile.ClassfileParser.parseMethod(ClassfileParser.scala:620)
[ERROR] 	at scala.tools.nsc.symtab.classfile.ClassfileParser.$anonfun$parseClass$4(ClassfileParser.scala:533)
[ERROR] 	at scala.tools.nsc.symtab.classfile.ClassfileParser.parseClass(ClassfileParser.scala:533)
[ERROR] 	at scala.tools.nsc.symtab.classfile.ClassfileParser.$anonfun$parse$2(ClassfileParser.scala:161)
[ERROR] 	at scala.tools.nsc.symtab.classfile.ClassfileParser.$anonfun$parse$1(ClassfileParser.scala:146)
[ERROR] 	at scala.tools.nsc.symtab.classfile.ClassfileParser.parse(ClassfileParser.scala:129)
[ERROR] 	at scala.tools.nsc.symtab.SymbolLoaders$ClassfileLoader.doComplete(SymbolLoaders.scala:329)
[ERROR] 	at scala.tools.nsc.symtab.SymbolLoaders$SymbolLoader.complete(SymbolLoaders.scala:230)
[ERROR] 	at scala.tools.nsc.symtab.SymbolLoaders$SymbolLoader.load(SymbolLoaders.scala:249)
[ERROR] 	at scala.tools.nsc.typechecker.Typers$Typer.isStale(Typers.scala:525)
[ERROR] 	at scala.tools.nsc.typechecker.Typers$Typer.reallyExists(Typers.scala:516)
[ERROR] 	at scala.tools.nsc.typechecker.Typers$Typer.qualifies$1(Typers.scala:5170)
[ERROR] 	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$66(Typers.scala:5201)
[ERROR] 	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$66$adapted(Typers.scala:5201)
[ERROR] 	at scala.reflect.internal.Symbols$Symbol.filter(Symbols.scala:2001)
[ERROR] 	at scala.tools.nsc.typechecker.Contexts$SymbolLookup.apply(Contexts.scala:1243)
[ERROR] 	at scala.tools.nsc.typechecker.Contexts$Context.$anonfun$lookupSymbol$1(Contexts.scala:1047)
[ERROR] 	at scala.tools.nsc.typechecker.Contexts$Context.lookupSymbol(Contexts.scala:1047)
[ERROR] 	at scala.tools.nsc.typechecker.Typers$Typer.typedIdent$2(Typers.scala:5201)
[ERROR] 	at scala.tools.nsc.typechecker.Typers$Typer.typedIdentOrWildcard$1(Typers.scala:5251)
[ERROR] 	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5685)
[ERROR] 	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5733)
[ERROR] 	at scala.tools.nsc.typechecker.Typers$Typer.typedType(Typers.scala:5859)
[ERROR] 	at scala.tools.nsc.typechecker.Typers$Typer.typedHigherKindedType(Typers.scala:5866)
[ERROR] 	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$75(Typers.scala:5301)
[ERROR] 	at scala.tools.nsc.typechecker.Typers$Typer.typedAppliedTypeTree$1(Typers.scala:5290)
[ERROR] 	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5640)
[ERROR] 	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5733)
[ERROR] 	at scala.tools.nsc.typechecker.Typers$Typer.typedType(Typers.scala:5859)
[ERROR] 	at scala.tools.nsc.typechecker.Typers$Typer.typedType(Typers.scala:5862)
[ERROR] 	at scala.tools.nsc.typechecker.Namers$Namer.methodSig(Namers.scala:1322)
[ERROR] 	at scala.tools.nsc.typechecker.Namers$Namer.memberSig(Namers.scala:1898)
[ERROR] 	at scala.tools.nsc.typechecker.Namers$Namer.typeSig(Namers.scala:1864)
[ERROR] 	at scala.tools.nsc.typechecker.Namers$Namer$MonoTypeCompleter.completeImpl(Namers.scala:869)
[ERROR] 	at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete(Namers.scala:2061)
[ERROR] 	at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete$(Namers.scala:2059)
[ERROR] 	at scala.tools.nsc.typechecker.Namers$TypeCompleterBase.complete(Namers.scala:2054)
[ERROR] 	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1539)
[ERROR] 	at scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1696)
[ERROR] 	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5356)
[ERROR] 	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5733)
[ERROR] 	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5797)
[ERROR] 	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3357)
[ERROR] 	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3357)
[ERROR] 	at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:2017)
[ERROR] 	at scala.tools.nsc.typechecker.Typers$Typer.typedModuleDef(Typers.scala:1883)
[ERROR] 	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5654)
[ERROR] 	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5733)
[ERROR] 	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5797)
[ERROR] 	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3357)
[ERROR] 	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3357)
[ERROR] 	at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5363)
[ERROR] 	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5656)
[ERROR] 	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5733)
[ERROR] 	at scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.apply(Analyzer.scala:115)
[ERROR] 	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:451)
[ERROR] 	at scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.run(Analyzer.scala:104)
[ERROR] 	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1501)
[ERROR] 	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1485)
[ERROR] 	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1478)
[ERROR] 	at scala.tools.nsc.Global$Run.compile(Global.scala:1604)
[ERROR] 	at scala.tools.nsc.Driver.doCompile(Driver.scala:47)
[ERROR] 	at scala.tools.nsc.MainClass.doCompile(Main.scala:32)
[ERROR] 	at scala.tools.nsc.Driver.process(Driver.scala:67)
[ERROR] 	at scala.tools.nsc.Driver.main(Driver.scala:80)
[ERROR] 	at scala.tools.nsc.Main.main(Main.scala)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR] 	at scala_maven_executions.MainHelper.runMain(MainHelper.java:164)
[ERROR] 	at scala_maven_executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
`

Can someone share their experience and what am i missing here ?

**Comment by Jackie-Jiang** [comment]
From what I can tell seems the error is from scala files, so you might want to check the scala version used to build the project. You might be able to get more help from the Slack troubleshooting channel.
FYI, starting with `1.0` we are dropping the support for java 8, and the minimum java version required is 11
