### ISSUE TITLE
BasePartitionUpsertMetadataManagerTest#testConsistencyModeSnapshot UT flakiness

### ISSUE THREAD

**Issue by tibrewalpratik17** [apache/pinot#13241]
Seeing this UT failure sometimes during builds.

```
Error:  Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 7.566 s <<< FAILURE! -- in org.apache.pinot.segment.local.upsert.BasePartitionUpsertMetadataManagerTest
Error:  org.apache.pinot.segment.local.upsert.BasePartitionUpsertMetadataManagerTest.testConsistencyModeSnapshot -- Time elapsed: 2.368 s <<< FAILURE!
java.lang.AssertionError: 1998 was less than expected expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:111)
	at org.testng.Assert.failNotEquals(Assert.java:1578)
	at org.testng.Assert.assertTrue(Assert.java:57)
	at org.apache.pinot.segment.local.upsert.BasePartitionUpsertMetadataManagerTest.testConsistencyModeSnapshot(BasePartitionUpsertMetadataManagerTest.java:384)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.testng.TestRunner.privateRun(TestRunner.java:739)
	at org.testng.TestRunner.run(TestRunner.java:614)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
	at org.testng.SuiteRunner.run(SuiteRunner.java:312)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
	at org.testng.TestNG.runSuites(TestNG.java:1112)
	at org.testng.TestNG.run(TestNG.java:1079)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:155)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:102)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:91)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:137)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
```

cc @klsince

**Comment by klsince** [comment]
Thanks for the report. Didn’t see this from Github builds or local runs before but will double check. Btw what the env was like when you built and saw this? If it’s a GH build, you may get a link to the failure

**Comment by tibrewalpratik17** [comment]
Saw it on GH build itself. Here's one recent sample link -- https://github.com/apache/pinot/actions/runs/9254859049/job/25457492488?pr=13103

**Comment by klsince** [comment]
Think I found why it's flaky. I was taking WLock for both sync/snapshot mode in this method BasePartitionUpsertMetadataManager.replaceDocId() updating two segments for simplicity, but later on I separated them as refinement. But I forgot to refine the test method for snapshot mode, as it just passed. Working on a fix for this.
