### ISSUE TITLE
Funnel Count Query Failing with predicate filters.

### ISSUE THREAD

**Issue by Jayesh-Asrani** [apache/pinot#13593]
1. We are trying to execute a Funnel Count Query as mentioned below 
 `select FUNNEL_COUNT(
    STEPS(
      event_name = 'A',
      event_name = 'B',
      event_name = 'C',
      event_name = 'D'
    ),
    CORRELATE_BY(user_id)
  ) AS counts
from events
where event_type in (
    'app_open',
    'catalog_opened',
    'add_to_cart_clicked',
    'buy_now_clicked'
  )
  and event_time >= 1719253800
  and event_time <= 1719340200`

2. The query fails with an NPE error 

> QueryExecutionError:
java.lang.NullPointerException: Cannot read field "_dictionary" because "dictIdsWrapper" is null
	at org.apache.pinot.core.query.aggregation.function.funnel.BitmapResultExtractionStrategy.extractIntermediateResult(BitmapResultExtractionStrategy.java:38)
	at org.apache.pinot.core.query.aggregation.function.funnel.BitmapResultExtractionStrategy.extractIntermediateResult(BitmapResultExtractionStrategy.java:29)
	at org.apache.pinot.core.query.aggregation.function.funnel.ResultExtractionStrategy.extractAggregationResult(ResultExtractionStrategy.java:41)
	at org.apache.pinot.core.query.aggregation.function.funnel.FunnelCountAggregationFunction.extractAggregationResult(FunnelCountAggregationFunction.java:139)

3. If we however remove the filter on the event_type predicate the query seems to be working as expected

**Comment by Jackie-Jiang** [comment]
cc @xiangfu0

**Comment by ApsTomar** [comment]
@Jayesh-Asrani @Jackie-Jiang Is this issue still reproducible? I ran a similar query with same predicate on a dataset and got the correct result, no error occurred. Please elaborate the issue reproduction conditions or steps if the it still persists.

**Comment by Jayesh-Asrani** [comment]
This seems to be resolved in the latest versions. We can close this
