### ISSUE TITLE
Pinot should run on ipv6 only env without issues

### ISSUE THREAD

**Issue by real-mj-song** [apache/pinot#13772]
## What needs to be done?
When `java.net.preferIPv6Addresses` property is set `true`, Pinot should only use ipv6 references (if any). Otherwise, fall back to ipv4

## Why the feature is needed (e.g. describing the use case).
With more data centers/services run on ipv6 only environment, Pinot should work with ipv6 only env without any issues.

## initial idea/proposal on how.
If there are any hard-coded ipv4 addresses, the references/values need to be updated to pick ipv4/6 dynamically based on system property.

### Existing issue(s)
On ipv6 only servers, [NetUtils.getHostAddress](https://github.com/apache/pinot/blob/master/pinot-spi/src/main/java/org/apache/pinot/spi/utils/NetUtils.java#L33-L47) throws exception because of ipv4 address usage. This fails broker to start up
```
Caused by: java.io.UncheckedIOException: java.net.SocketException: Network is unreachable
        at sun.nio.ch.DatagramSocketAdaptor.connect(DatagramSocketAdaptor.java:120) ~[?:?]
        at java.net.DatagramSocket.connect(DatagramSocket.java:474) ~[?:?]
        at org.apache.pinot.spi.utils.NetUtils.getHostAddress(NetUtils.java:41) ~[org.apache.pinot.pinot-spi-1.3.0-dev-1389.jar:1.3.0-dev-1389-dd8a6477c22e761a2a6dc3264b9c2a86c94427fd]
        at org.apache.pinot.broker.broker.helix.BaseBrokerStarter.init(BaseBrokerStarter.java:155) ~[org.apache.pinot.pinot-broker-1.3.0-dev-1389.jar:1.3.0-dev-1389-dd8a6477c22e761a2a6dc3264b9c2a86c94427fd]
        at org.apache.pinot.broker.broker.helix.HelixBrokerStarter.<init>(HelixBrokerStarter.java:42) ~[org.apache.pinot.pinot-broker-1.3.0-dev-1389.jar:1.3.0-dev-1389-dd8a6477c22e761a2a6dc3264b9c2a86c94427fd]
        ... 35 more
Caused by: java.net.SocketException: Network is unreachable
        at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
        at sun.nio.ch.Net.connect(Net.java:579) ~[?:?]
        at sun.nio.ch.DatagramChannelImpl.connect(DatagramChannelImpl.java:1249) ~[?:?]
        at sun.nio.ch.DatagramSocketAdaptor.connectInternal(DatagramSocketAdaptor.java:91) ~[?:?]
        at sun.nio.ch.DatagramSocketAdaptor.connect(DatagramSocketAdaptor.java:118) ~[?:?]
        at java.net.DatagramSocket.connect(DatagramSocket.java:474) ~[?:?]
        at org.apache.pinot.spi.utils.NetUtils.getHostAddress(NetUtils.java:41) ~[org.apache.pinot.pinot-spi-1.3.0-dev-1389.jar:1.3.0-dev-1389-dd8a6477c22e761a2a6dc3264b9c2a86c94427fd]
        at org.apache.pinot.broker.broker.helix.BaseBrokerStarter.init(BaseBrokerStarter.java:155) ~[org.apache.pinot.pinot-broker-1.3.0-dev-1389.jar:1.3.0-dev-1389-dd8a6477c22e761a2a6dc3264b9c2a86c94427fd]
        at org.apache.pinot.broker.broker.helix.HelixBrokerStarter.<init>(HelixBrokerStarter.java:42) ~[org.apache.pinot.pinot-broker-1.3.0-dev-1389.jar:1.3.0-dev-1389-dd8a6477c22e761a2a6dc3264b9c2a86c94427fd]
        ... 35 more

```

**Comment by real-mj-song** [comment]
@Jackie-Jiang I'm drafting a PR to update `NetUtils` class to take into account `java.net.preferIPv6Addresses` property. If more issues discovered regarding ipv6 only env, I will link them here. cc @siddharthteotia

**Comment by Jackie-Jiang** [comment]
Since the PR is merged, shall we close this issue?

**Comment by real-mj-song** [comment]
@Jackie-Jiang I didn't have a chance to fully test the new version in our prod environment yet. Let me update here next week

**Comment by real-mj-song** [comment]
Confirmed all components (server/broker/minion/controller) start on ipv6 only & dual stack envs ✅
