### ISSUE TITLE
NPE at DistinctCountHLLAggregationFunction.extractFinalResult()

### ISSUE THREAD

**Issue by deepix** [apache/pinot#13815]
We are seeing an NPE in Pinot. We run Pinot 1.0.0 on Kubernetes via statefulsets.

This happened when we were trying to increase disk space for Pinot, we made the change and then restarted the statefulset.

We had about ~2k occurrences of this NPE.

Exception trace from the application (client) side:
```
Encountered exception: {'errorCode': 200,  'message': 'QueryExecutionError: '             'Received error query execution result block: {1000=null '             'java.lang.NullPointerException '             '\tat '             'org.apache.pinot.core.query.aggregation.function.DistinctCountHLLAggregationFunction.extractFinalResult(DistinctCountHLLAggregationFunction.java:363) '             '\tat '             'org.apache.pinot.core.query.aggregation.function.DistinctCountHLLAggregationFunction.extractFinalResult(DistinctCountHLLAggregationFunction.java:41) '             '\tat '             'org.apache.pinot.query.runtime.operator.MultistageAggregationExecutor.getResult(MultistageAggregationExecutor.java:107) '             '\tat '             'org.apache.pinot.query.runtime.operator.AggregateOperator.produceAggregatedBlock(AggregateOperator.java:204)} '             'org.apache.pinot.query.service.dispatch.QueryDispatcher.getResultTable(QueryDispatcher.java:268) '             'org.apache.pinot.query.service.dispatch.QueryDispatcher.runReducer(QueryDispatcher.java:207) '             'org.apache.pinot.query.service.dispatch.QueryDispatcher.submitAndReduce(QueryDispatcher.java:96) '             'org.apache.pinot.broker.requesthandler.MultiStageBrokerRequestHandler.handleRequest(MultiStageBrokerRequestHandler.java:179) '}
```

This is the server-side logs for the corresponding time:

```

Aug 07 13:14:02.220
Caught exception executing request 2028772242000657384:

Aug 07 13:14:02.220
SELECT DISTINCTCOUNTHLL(doc_id) total,

Aug 07 13:14:02.220
DISTINCTCOUNTHLL(doc_id) FILTER (

Aug 07 13:14:02.220
WHERE created_at_by_hr > 478623

Aug 07 13:14:02.220
) current_period,

Aug 07 13:14:02.220
DISTINCTCOUNTHLL(doc_id) FILTER (

Aug 07 13:14:02.220
WHERE created_at_by_hr

Aug 07 13:14:02.220
> 478617

Aug 07 13:14:02.220
AND created_at_by_hr <= 478623

Aug 07 13:14:02.220
) previous_period

Aug 07 13:14:02.220
FROM doc_metadata

Aug 07 13:14:02.220
WHERE

Aug 07 13:14:02.220
arrayToMv(channels) = '2b20d8d0-17d6-442a-8aa0-0765fe2e6036-twitter-api'

Aug 07 13:14:02.220
AND message_type = 'metadata-social'

Aug 07 13:14:02.220
AND created_at_by_hr >= 478604

Aug 07 13:14:02.220
AND created_at_by_hr < 478629

Aug 07 13:14:02.220
;

Aug 07 13:14:02.220
, Received error query execution result block: {1000=null

Aug 07 13:14:02.220
java.lang.NullPointerException

Aug 07 13:14:02.220
at org.apache.pinot.core.query.aggregation.function.DistinctCountHLLAggregationFunction.extractFinalResult(DistinctCountHLLAggregationFunction.java:363)

Aug 07 13:14:02.220
at org.apache.pinot.core.query.aggregation.function.DistinctCountHLLAggregationFunction.extractFinalResult(DistinctCountHLLAggregationFunction.java:41)

Aug 07 13:14:02.220
at org.apache.pinot.query.runtime.operator.MultistageAggregationExecutor.getResult(MultistageAggregationExecutor.java:107)

Aug 07 13:14:02.220
at org.apache.pinot.query.runtime.operator.AggregateOperator.produceAggregatedBlock(AggregateOperator.java:204)}

Aug 07 13:14:02.220
org.apache.pinot.query.service.dispatch.QueryDispatcher.getResultTable(QueryDispatcher.java:268)

Aug 07 13:14:02.220
org.apache.pinot.query.service.dispatch.QueryDispatcher.runReducer(QueryDispatcher.java:207)

Aug 07 13:14:02.220
org.apache.pinot.query.service.dispatch.QueryDispatcher.submitAndReduce(QueryDispatcher.java:96)

Aug 07 13:14:02.220
org.apache.pinot.broker.requesthandler.MultiStageBrokerRequestHandler.handleRequest(MultiStageBrokerRequestHandler.java:179)

Aug 07 13:14:02.220
Caught exception executing request 2028772242000657385:

Aug 07 13:14:02.220
SELECT DISTINCTCOUNTHLL(doc_id) total,

Aug 07 13:14:02.220
DISTINCTCOUNTHLL(doc_id) FILTER (

Aug 07 13:14:02.220
WHERE created_at_by_hr > 478623

Aug 07 13:14:02.220
) current_period,

Aug 07 13:14:02.220
DISTINCTCOUNTHLL(doc_id) FILTER (

Aug 07 13:14:02.220
WHERE created_at_by_hr

Aug 07 13:14:02.220
> 478617

Aug 07 13:14:02.220
AND created_at_by_hr <= 478623

Aug 07 13:14:02.220
) previous_period

Aug 07 13:14:02.220
FROM doc_metadata

Aug 07 13:14:02.220
WHERE

Aug 07 13:14:02.220
arrayToMv(channels) = '2b20d8d0-17d6-442a-8aa0-0765fe2e6036-twitter-api'

Aug 07 13:14:02.220
AND message_type = 'metadata-news'

Aug 07 13:14:02.220
AND created_at_by_hr >= 478604

Aug 07 13:14:02.220
AND created_at_by_hr < 478629

Aug 07 13:14:02.220
;

Aug 07 13:14:02.221
, Received error query execution result block: {1000=null

Aug 07 13:14:02.221
java.lang.NullPointerException

Aug 07 13:14:02.221
at org.apache.pinot.core.query.aggregation.function.DistinctCountHLLAggregationFunction.extractFinalResult(DistinctCountHLLAggregationFunction.java:363)

Aug 07 13:14:02.221
at org.apache.pinot.core.query.aggregation.function.DistinctCountHLLAggregationFunction.extractFinalResult(DistinctCountHLLAggregationFunction.java:41)

Aug 07 13:14:02.221
at org.apache.pinot.query.runtime.operator.MultistageAggregationExecutor.getResult(MultistageAggregationExecutor.java:107)

Aug 07 13:14:02.221
at org.apache.pinot.query.runtime.operator.AggregateOperator.produceAggregatedBlock(AggregateOperator.java:204)}

Aug 07 13:14:02.221
org.apache.pinot.query.service.dispatch.QueryDispatcher.getResultTable(QueryDispatcher.java:268)

Aug 07 13:14:02.221
org.apache.pinot.query.service.dispatch.QueryDispatcher.runReducer(QueryDispatcher.java:207)

Aug 07 13:14:02.221
org.apache.pinot.query.service.dispatch.QueryDispatcher.submitAndReduce(QueryDispatcher.java:96)

Aug 07 13:14:02.221
org.apache.pinot.broker.requesthandler.MultiStageBrokerRequestHandler.handleRequest(MultiStageBrokerRequestHandler.java:179)

Aug 07 13:14:02.313
Failed to load LLC segment: doc_metadata__86__738__20240727T1641Z, downloading a new copy
```

**Comment by Jackie-Jiang** [comment]
Since `1.0` we have made a lot of improvements to multi-stage engine, and it is very hard to track a bug in `1.0`. Can you try to reproduce this with latest code and see if it gets fixed? We are in the process of releasing `1.2` right now in case you cannot directly pick the latest master.
