### ISSUE TITLE
Bump org.apache.datasketches:datasketches-java from 6.0.0 to 6.1.0

### ISSUE THREAD

**Issue by abhioncbr** [apache/pinot#14027]
Check the failures [here](https://github.com/apache/pinot/pull/14005)

**Comment by Jackie-Jiang** [comment]
Seems all the failures are with java 21

**Comment by Jackie-Jiang** [comment]
Seeing this exception. Seems java 21 is no longer supported.

```
2024-09-18T19:01:55.7652987Z Caused by: java.lang.IllegalArgumentException: Unsupported JDK Major Version. It must be one of 1.8, 8, 11, 17: 21.0.4
2024-09-18T19:01:55.7654805Z 	at org.apache.datasketches.memory.internal.ResourceImpl.checkJavaVersion(ResourceImpl.java:146)
2024-09-18T19:01:55.7656546Z 	at org.apache.datasketches.memory.internal.ResourceImpl.parseJavaVersion(ResourceImpl.java:383)
2024-09-18T19:01:55.7660195Z 	at org.apache.datasketches.memory.internal.ResourceImpl.<clinit>(ResourceImpl.java:87)
2024-09-18T19:01:55.7661248Z 	... 48 more
```

**Comment by Jackie-Jiang** [comment]
This is the related change that throws exception on java 21: https://github.com/apache/datasketches-memory/pull/209

**Comment by ilamhs** [comment]
Good to be closed with the upgrade dep bump done at https://github.com/apache/pinot/pull/14223
