### ISSUE TITLE
Loading the zookeeper browser page is failing with error

### ISSUE THREAD

**Issue by chrajeshbabu** [apache/pinot#14216]
zookeeper browser always giving blank page. When I dig deeper found the following error.

`main.js:17441 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'numChildren')
    at main.js:17441:59
    at Array.map (<anonymous>)
    at main.js:17435:19`

it's happening while forming the tree structure  with zookeeper data.

Here getting null, need to check how currentNodeListStat[pathName] could be null.
https://github.com/apache/pinot/blob/b067ae1924a532282229e0506188b9375f0ec6d2/pinot-controller/src/main/resources/app/utils/PinotMethodUtils.ts#L704

**Comment by Jackie-Jiang** [comment]
cc @jayeshchoudhary

**Comment by jayeshchoudhary** [comment]
@chrajeshbabu can you attach a video?
also which version are you using?

This might be related to new complex field we added ?
Ui fix - https://github.com/apache/pinot/pull/14245/files
