### ISSUE TITLE
Gracefully handle reading size for disabled table

### ISSUE THREAD

**Issue by piby180** [apache/pinot#14279]
When a table is disabled, we constantly see this error in broker logs. Since the log level is set to ERROR for this, this triggers our alarms. Can we set them to INFO or WARN?

```
2024/10/23 06:41:55.921 ERROR [CompletionServiceHelper] [pool-13-thread-6] Server: Server_pinot-server-0.pinot-server-headless.pinot-dev.svc.cluster.local_8098 returned error: 404, reason: Not Found for uri: http://pinot-server-0.pinot-server-headless.pinot-dev.svc.cluster.local:8097/table/test_mfrr_neg_capacity_price_data_OFFLINE/size
2024/10/23 06:41:55.922 ERROR [CompletionServiceHelper] [pool-13-thread-6] Server: Server_pinot-server-1.pinot-server-headless.pinot-dev.svc.cluster.local_8098 returned error: 404, reason: Not Found for uri: http://pinot-server-1.pinot-server-headless.pinot-dev.svc.cluster.local:8097/table/test_mfrr_neg_capacity_price_data_OFFLINE/size
2024/10/23 06:41:55.922 ERROR [CompletionServiceHelper] [pool-13-thread-6] Server: Server_pinot-server-2.pinot-server-headless.pinot-dev.svc.cluster.local_8098 returned error: 404, reason: Not Found for uri: http://pinot-server-2.pinot-server-headless.pinot-dev.svc.cluster.local:8097/table/test_mfrr_neg_capacity_price_data_OFFLINE/size
2024/10/23 06:41:56.023 ERROR [CompletionServiceHelper] [pool-13-thread-6] Server: Server_pinot-server-0.pinot-server-headless.pinot-dev.svc.cluster.local_8098 returned error: 404, reason: Not Found for uri: http://pinot-server-0.pinot-server-headless.pinot-dev.svc.cluster.local:8097/table/test_temperature_forecast_OFFLINE/size
2024/10/23 06:41:56.024 ERROR [CompletionServiceHelper] [pool-13-thread-6] Server: Server_pinot-server-1.pinot-server-headless.pinot-dev.svc.cluster.local_8098 returned error: 404, reason: Not Found for uri: http://pinot-server-1.pinot-server-headless.pinot-dev.svc.cluster.local:8097/table/test_temperature_forecast_OFFLINE/size
2024/10/23 06:41:56.024 ERROR [CompletionServiceHelper] [pool-13-thread-6] Server: Server_pinot-server-2.pinot-server-headless.pinot-dev.svc.cluster.local_8098 returned error: 404, reason: Not Found for uri: http://pinot-server-2.pinot-server-headless.pinot-dev.svc.cluster.local:8097/table/test_temperature_forecast_OFFLINE/size
2024/10/23 06:41:56.572 ERROR [CompletionServiceHelper] [pool-13-thread-6] Server: Server_pinot-server-0.pinot-server-headless.pinot-dev.svc.cluster.local_8098 returned error: 404, reason: Not Found for uri: http://pinot-server-0.pinot-server-headless.pinot-dev.svc.cluster.local:8097/table/test_feed_price_data_OFFLINE/size
2024/10/23 06:41:56.573 ERROR [CompletionServiceHelper] [pool-13-thread-6] Server: Server_pinot-server-2.pinot-server-headless.pinot-dev.svc.cluster.local_8098 returned error: 404, reason: Not Found for uri: http://pinot-server-2.pinot-server-headless.pinot-dev.svc.cluster.local:8097/table/test_feed_price_data_OFFLINE/size
2024/10/23 06:41:56.573 ERROR [CompletionServiceHelper] [pool-13-thread-6] Server: Server_pinot-server-1.pinot-server-headless.pinot-dev.svc.cluster.local_8098 returned error: 404, reason: Not Found for uri: http://pinot-server-1.pinot-server-headless.pinot-dev.svc.cluster.local:8097/table/test_feed_price_data_OFFLINE/size
2024/10/23 06:41:56.580 ERROR [CompletionServiceHelper] [pool-13-thread-6] Server: Server_pinot-server-0.pinot-server-headless.pinot-dev.svc.cluster.local_8098 returned error: 404, reason: Not Found for uri: http://pinot-server-0.pinot-server-headless.pinot-dev.svc.cluster.local:8097/table/test_afrr_pos_capacity_price_data_OFFLINE/size
2024/10/23 06:41:56.581 ERROR [CompletionServiceHelper] [pool-13-thread-6] Server: Server_pinot-server-1.pinot-server-headless.pinot-dev.svc.cluster.local_8098 returned error: 404, reason: Not Found for uri: http://pinot-server-1.pinot-server-headless.pinot-dev.svc.cluster.local:8097/table/test_afrr_pos_capacity_price_data_OFFLINE/size
2024/10/23 06:41:56.582 ERROR [CompletionServiceHelper] [pool-13-thread-6] Server: Server_pinot-server-2.pinot-server-headless.pinot-dev.svc.cluster.local_8098 returned error: 404, reason: Not Found for uri: http://pinot-server-2.pinot-server-headless.pinot-dev.svc.cluster.local:8097/table/test_afrr_pos_capacity_price_data_OFFLINE/size
2024/10/23 06:41:56.937 ERROR [CompletionServiceHelper] [pool-13-thread-6] Server: Server_pinot-server-0.pinot-server-headless.pinot-dev.svc.cluster.local_8098 returned error: 404, reason: Not Found for uri: http://pinot-server-0.pinot-server-headless.pinot-dev.svc.cluster.local:8097/table/test_system_imbalance_OFFLINE/size
2024/10/23 06:41:56.938 ERROR [CompletionServiceHelper] [pool-13-thread-6] Server: Server_pinot-server-1.pinot-server-headless.pinot-dev.svc.cluster.local_8098 returned error: 404, reason: Not Found for uri: http://pinot-server-1.pinot-server-headless.pinot-dev.svc.cluster.local:8097/table/test_system_imbalance_OFFLINE/size
2024/10/23 06:41:56.938 ERROR [CompletionServiceHelper] [pool-13-thread-6] Server: Server_pinot-server-2.pinot-server-headless.pinot-dev.svc.cluster.local_8098 returned error: 404, reason: Not Found for uri: http://pinot-server-2.pinot-server-headless.pinot-dev.svc.cluster.local:8097/table/test_system_imbalance_OFFLINE/size
2024/10/23 06:41:57.291 ERROR [CompletionServiceHelper] [pool-13-thread-6] Server: Server_pinot-server-0.pinot-server-headless.pinot-dev.svc.cluster.local_8098 returned error: 404, reason: Not Found for uri: http://pinot-server-0.pinot-server-headless.pinot-dev.svc.cluster.local:8097/table/test_spotprices_forecast_OFFLINE/size
2024/10/23 06:41:57.292 ERROR [CompletionServiceHelper] [pool-13-thread-6] Server: Server_pinot-server-1.pinot-server-headless.pinot-dev.svc.cluster.local_8098 returned error: 404, reason: Not Found for uri: http://pinot-server-1.pinot-server-headless.pinot-dev.svc.cluster.local:8097/table/test_spotprices_forecast_OFFLINE/size
2024/10/23 06:41:57.292 ERROR [CompletionServiceHelper] [pool-13-thread-6] Server: Server_pinot-server-2.pinot-server-headless.pinot-dev.svc.cluster.local_8098 returned error: 404, reason: Not Found for uri: http://pinot-server-2.pinot-server-headless.pinot-dev.svc.cluster.local:8097/table/test_spotprices_forecast_OFFLINE/size
2024/10/23 06:41:57.734 ERROR [CompletionServiceHelper] [pool-13-thread-6] Server: Server_pinot-server-0.pinot-server-headless.pinot-dev.svc.cluster.local_8098 returned error: 404, reason: Not Found for uri: http://pinot-server-0.pinot-server-headless.pinot-dev.svc.cluster.local:8097/table/test_consumption_OFFLINE/size
2024/10/23 06:41:57.735 ERROR [CompletionServiceHelper] [pool-13-thread-6] Server: Server_pinot-server-1.pinot-server-headless.pinot-dev.svc.cluster.local_8098 returned error: 404, reason: Not Found for uri: http://pinot-server-1.pinot-server-headless.pinot-dev.svc.cluster.local:8097/table/test_consumption_OFFLINE/size
2024/10/23 06:41:57.735 ERROR [CompletionServiceHelper] [pool-13-thread-6] Server: Server_pinot-server-2.pinot-server-headless.pinot-dev.svc.cluster.local_8098 returned error: 404, reason: Not Found for uri: http://pinot-server-2.pinot-server-headless.pinot-dev.svc.cluster.local:8097/table/test_consumption_OFFLINE/size
2024/10/23 06:41:57.862 ERROR [CompletionServiceHelper] [pool-13-thread-6] Server: Server_pinot-server-0.pinot-server-headless.pinot-dev.svc.cluster.local_8098 returned error: 404, reason: Not Found for uri: http://pinot-server-0.pinot-server-headless.pinot-dev.svc.cluster.local:8097/table/test_solar_power_forecast_ensemble_OFFLINE/size
2024/10/23 06:41:57.862 ERROR [CompletionServiceHelper] [pool-13-thread-6] Server: Server_pinot-server-1.pinot-server-headless.pinot-dev.svc.cluster.local_8098 returned error: 404, reason: Not Found for uri: http://pinot-server-1.pinot-server-headless.pinot-dev.svc.cluster.local:8097/table/test_solar_power_forecast_ensemble_OFFLINE/size
2024/10/23 06:41:57.862 ERROR [CompletionServiceHelper] [pool-13-thread-6] Server: Server_pinot-server-2.pinot-server-headless.pinot-dev.svc.cluster.local_8098 returned error: 404, reason: Not Found for uri: http://pinot-server-2.pinot-server-headless.pinot-dev.svc.cluster.local:8097/table/test_solar_power_forecast_ensemble_OFFLINE/size
2024/10/23 06:41:58.029 ERROR [CompletionServiceHelper] [pool-13-thread-6] Server: Server_pinot-server-0.pinot-server-headless.pinot-dev.svc.cluster.local_8098 returned error: 404, reason: Not Found for uri: http://pinot-server-0.pinot-server-headless.pinot-dev.svc.cluster.local:8097/table/test_wind_power_forecast_OFFLINE/size
2024/10/23 06:41:58.029 ERROR [CompletionServiceHelper] [pool-13-thread-6] Server: Server_pinot-server-1.pinot-server-headless.pinot-dev.svc.cluster.local_8098 returned error: 404, reason: Not Found for uri: http://pinot-server-1.pinot-server-headless.pinot-dev.svc.cluster.local:8097/table/test_wind_power_forecast_OFFLINE/size
2024/10/23 06:41:58.029 ERROR [CompletionServiceHelper] [pool-13-thread-6] Server: Server_pinot-server-2.pinot-server-headless.pinot-dev.svc.cluster.local_8098 returned error: 404, reason: Not Found for uri: http://pinot-server-2.pinot-server-headless.pinot-dev.svc.cluster.local:8097/table/test_wind_power_forecast_OFFLINE/size
2024/10/23 06:42:06.164 ERROR [CompletionServiceHelper] [pool-13-thread-6] Server: Server_pinot-server-0.pinot-server-headless.pinot-dev.svc.cluster.local_8098 returned error: 404, reason: Not Found for uri: http://pinot-server-0.pinot-server-headless.pinot-dev.svc.cluster.local:8097/table/test_consumption_ensemble_OFFLINE/size
2024/10/23 06:42:06.164 ERROR [CompletionServiceHelper] [pool-13-thread-6] Server: Server_pinot-server-1.pinot-server-headless.pinot-dev.svc.cluster.local_8098 returned error: 404, reason: Not Found for uri: http://pinot-server-1.pinot-server-headless.pinot-dev.svc.cluster.local:8097/table/test_consumption_ensemble_OFFLINE/size
2024/10/23 06:42:06.164 ERROR [CompletionServiceHelper] [pool-13-thread-6] Server: Server_pinot-server-2.pinot-server-headless.pinot-dev.svc.cluster.local_8098 returned error: 404, reason: Not Found for uri: http://pinot-server-2.pinot-server-headless.pinot-dev.svc.cluster.local:8097/table/test_consumption_ensemble_OFFLINE/size
2024/10/23 06:42:07.258 ERROR [CompletionServiceHelper] [pool-13-thread-6] Server: Server_pinot-server-0.pinot-server-headless.pinot-dev.svc.cluster.local_8098 returned error: 404, reason: Not Found for uri: http://pinot-server-0.pinot-server-headless.pinot-dev.svc.cluster.local:8097/table/test_normal_temperature_OFFLINE/size
2024/10/23 06:42:07.259 ERROR [CompletionServiceHelper] [pool-13-thread-6] Server: Server_pinot-server-1.pinot-server-headless.pinot-dev.svc.cluster.local_8098 returned error: 404, reason: Not Found for uri: http://pinot-server-1.pinot-server-headless.pinot-dev.svc.cluster.local:8097/table/test_normal_temperature_OFFLINE/size
2024/10/23 06:42:07.259 ERROR [CompletionServiceHelper] [pool-13-thread-6] Server: Server_pinot-server-2.pinot-server-headless.pinot-dev.svc.cluster.local_8098 returned error: 404, reason: Not Found for uri: http://pinot-server-2.pinot-server-headless.pinot-dev.svc.cluster.local:8097/table/test_normal_temperature_OFFLINE/size
2024/10/23 06:42:07.264 ERROR [CompletionServiceHelper] [pool-13-thread-6] Server: Server_pinot-server-0.pinot-server-headless.pinot-dev.svc.cluster.local_8098 returned error: 404, reason: Not Found for uri: http://pinot-server-0.pinot-server-headless.pinot-dev.svc.cluster.local:8097/table/greenfact_goo_trades_data_OFFLINE/size
2024/10/23 06:42:07.265 ERROR [CompletionServiceHelper] [pool-13-thread-6] Server: Server_pinot-server-1.pinot-server-headless.pinot-dev.svc.cluster.local_8098 returned error: 404, reason: Not Found for uri: http://pinot-server-1.pinot-server-headless.pinot-dev.svc.cluster.local:8097/table/greenfact_goo_trades_data_OFFLINE/size
2024/10/23 06:42:07.265 ERROR [CompletionServiceHelper] [pool-13-thread-6] Server: Server_pinot-server-2.pinot-server-headless.pinot-dev.svc.cluster.local_8098 returned error: 404, reason: Not Found for uri: http://pinot-server-2.pinot-server-headless.pinot-dev.svc.cluster.local:8097/table/greenfact_goo_trades_data_OFFLINE/size
2024/10/23 06:42:07.340 ERROR [CompletionServiceHelper] [pool-13-thread-6] Server: Server_pinot-server-0.pinot-server-headless.pinot-dev.svc.cluster.local_8098 returned error: 404, reason: Not Found for uri: http://pinot-server-0.pinot-server-headless.pinot-dev.svc.cluster.local:8097/table/test_hydrological_balance_actual_OFFLINE/size
2024/10/23 06:42:07.340 ERROR [CompletionServiceHelper] [pool-13-thread-6] Server: Server_pinot-server-2.pinot-server-headless.pinot-dev.svc.cluster.local_8098 returned error: 404, reason: Not Found for uri: http://pinot-server-2.pinot-server-headless.pinot-dev.svc.cluster.local:8097/table/test_hydrological_balance_actual_OFFLINE/size
2024/10/23 06:42:07.341 ERROR [CompletionServiceHelper] [pool-13-thread-6] Server: Server_pinot-server-1.pinot-server-headless.pinot-dev.svc.cluster.local_8098 returned error: 404, reason: Not Found for uri: http://pinot-server-1.pinot-server-headless.pinot-dev.svc.cluster.local:8097/table/test_hydrological_balance_actual_OFFLINE/size
2024/10/23 06:42:07.860 ERROR [CompletionServiceHelper] [pool-13-thread-6] Server: Server_pinot-server-0.pinot-server-headless.pinot-dev.svc.cluster.local_8098 returned error: 404, reason: Not Found for uri: http://pinot-server-0.pinot-server-headless.pinot-dev.svc.cluster.local:8097/table/test_exchange_tso_numbers_da_OFFLINE/size
2024/10/23 06:42:07.861 ERROR [CompletionServiceHelper] [pool-13-thread-6] Server: Server_pinot-server-1.pinot-server-headless.pinot-dev.svc.cluster.local_8098 returned error: 404, reason: Not Found for uri: http://pinot-server-1.pinot-server-headless.pinot-dev.svc.cluster.local:8097/table/test_exchange_tso_numbers_da_OFFLINE/size
2024/10/23 06:42:07.861 ERROR [CompletionServiceHelper] [pool-13-thread-6] Server: Server_pinot-server-2.pinot-server-headless.pinot-dev.svc.cluster.local_8098 returned error: 404, reason: Not Found for uri: http://pinot-server-2.pinot-server-headless.pinot-dev.svc.cluster.local:8097/table/test_exchange_tso_numbers_da_OFFLINE/size
2024/10/23 06:42:08.086 ERROR [CompletionServiceHelper] [pool-13-thread-6] Server: Server_pinot-server-0.pinot-server-headless.pinot-dev.svc.cluster.local_8098 returned error: 404, reason: Not Found for uri: http://pinot-server-0.pinot-server-headless.pinot-dev.svc.cluster.local:8097/table/test_volume_weighted_average_price_OFFLINE/size
2024/10/23 06:42:08.087 ERROR [CompletionServiceHelper] [pool-13-thread-6] Server: Server_pinot-server-2.pinot-server-headless.pinot-dev.svc.cluster.local_8098 returned error: 404, reason: Not Found for uri: http://pinot-server-2.pinot-server-headless.pinot-dev.svc.cluster.local:8097/table/test_volume_weighted_average_price_OFFLINE/size
2024/10/23 06:42:08.087 ERROR [CompletionServiceHelper] [pool-13-thread-6] Server: Server_pinot-server-1.pinot-server-headless.pinot-dev.svc.cluster.local_8098 returned error: 404, reason: Not Found for uri: http://pinot-server-1.pinot-server-headless.pinot-dev.svc.cluster.local:8097/table/test_volume_weighted_average_price_OFFLINE/size
2024/10/23 06:42:08.272 ERROR [CompletionServiceHelper] [pool-13-thread-6] Server: Server_pinot-server-0.pinot-server-headless.pinot-dev.svc.cluster.local_8098 returned error: 404, reason: Not Found for uri: http://pinot-server-0.pinot-server-headless.pinot-dev.svc.cluster.local:8097/table/test_residual_load_ensemble_OFFLINE/size
2024/10/23 06:42:08.272 ERROR [CompletionServiceHelper] [pool-13-thread-6] Server: Server_pinot-server-1.pinot-server-headless.pinot-dev.svc.cluster.local_8098 returned error: 404, reason: Not Found for uri: http://pinot-server-1.pinot-server-headless.pinot-dev.svc.cluster.local:8097/table/test_residual_load_ensemble_OFFLINE/size
2024/10/23 06:42:08.273 ERROR [CompletionServiceHelper] [pool-13-thread-6] Server: Server_pinot-server-2.pinot-server-headless.pinot-dev.svc.cluster.local_8098 returned error: 404, reason: Not Found for uri: http://pinot-server-2.pinot-server-headless.pinot-dev.svc.cluster.local:8097/table/test_residual_load_ensemble_OFFLINE/size
2024/10/23 06:43:09.340 ERROR [PinotHelixResourceManager] [grizzly-http-server-7] Failed to update the segment lineage during endReplaceSegments. (tableName = test_solar_power_forecast_ensemble_OFFLINE, segmentLineageEntryId = 74a53320-1c21-4503-b834-f678523affc3)
org.apache.pinot.spi.utils.retry.AttemptsExceededException: Operation failed after 5 attempts
	at org.apache.pinot.spi.utils.retry.BaseRetryPolicy.attempt(BaseRetryPolicy.java:65) ~[pinot-all-1.2.0-jar-with-dependencies.jar:1.2.0-cc33ac502a02e2fe830fe21e556234ee99351a7a]
	at org.apache.pinot.controller.helix.core.PinotHelixResourceManager.endReplaceSegments(PinotHelixResourceManager.java:3657) ~[pinot-all-1.2.0-jar-with-dependencies.jar:1.2.0-cc33ac502a02e2fe830fe21e556234ee99351a7a]
	at org.apache.pinot.controller.api.resources.PinotSegmentUploadDownloadRestletResource.endReplaceSegments(PinotSegmentUploadDownloadRestletResource.java:701) ~[pinot-all-1.2.0-jar-with-dependencies.jar:1.2.0-cc33ac502a02e2fe830fe21e556234ee99351a7a]
	at jdk.internal.reflect.GeneratedMethodAccessor410.invoke(Unknown Source) ~[?:?]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[pinot-all-1.2.0-jar-with-dependencies.jar:1.2.0-cc33ac502a02e2fe830fe21e556234ee99351a7a]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:146) [pinot-all-1.2.0-jar-with-dependencies.jar:1.2.0-cc33ac502a02e2fe830fe21e556234ee99351a7a]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:189) [pinot-all-1.2.0-jar-with-dependencies.jar:1.2.0-cc33ac502a02e2fe830fe21e556234ee99351a7a]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176) [pinot-all-1.2.0-jar-with-dependencies.jar:1.2.0-cc33ac502a02e2fe830fe21e556234ee99351a7a]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:93) [pinot-all-1.2.0-jar-with-dependencies.jar:1.2.0-cc33ac502a02e2fe830fe21e556234ee99351a7a]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478) [pinot-all-1.2.0-jar-with-dependencies.jar:1.2.0-cc33ac502a02e2fe830fe21e556234ee99351a7a]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400) [pinot-all-1.2.0-jar-with-dependencies.jar:1.2.0-cc33ac502a02e2fe830fe21e556234ee99351a7a]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81) [pinot-all-1.2.0-jar-with-dependencies.jar:1.2.0-cc33ac502a02e2fe830fe21e556234ee99351a7a]
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:256) [pinot-all-1.2.0-jar-with-dependencies.jar:1.2.0-cc33ac502a02e2fe830fe21e556234ee99351a7a]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) [pinot-all-1.2.0-jar-with-dependencies.jar:1.2.0-cc33ac502a02e2fe830fe21e556234ee99351a7a]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) [pinot-all-1.2.0-jar-with-dependencies.jar:1.2.0-cc33ac502a02e2fe830fe21e556234ee99351a7a]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) [pinot-all-1.2.0-jar-with-dependencies.jar:1.2.0-cc33ac502a02e2fe830fe21e556234ee99351a7a]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) [pinot-all-1.2.0-jar-with-dependencies.jar:1.2.0-cc33ac502a02e2fe830fe21e556234ee99351a7a]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244) [pinot-all-1.2.0-jar-with-dependencies.jar:1.2.0-cc33ac502a02e2fe830fe21e556234ee99351a7a]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) [pinot-all-1.2.0-jar-with-dependencies.jar:1.2.0-cc33ac502a02e2fe830fe21e556234ee99351a7a]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:235) [pinot-all-1.2.0-jar-with-dependencies.jar:1.2.0-cc33ac502a02e2fe830fe21e556234ee99351a7a]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684) [pinot-all-1.2.0-jar-with-dependencies.jar:1.2.0-cc33ac502a02e2fe830fe21e556234ee99351a7a]
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:356) [pinot-all-1.2.0-jar-with-dependencies.jar:1.2.0-cc33ac502a02e2fe830fe21e556234ee99351a7a]
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:200) [pinot-all-1.2.0-jar-with-dependencies.jar:1.2.0-cc33ac502a02e2fe830fe21e556234ee99351a7a]
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569) [pinot-all-1.2.0-jar-with-dependencies.jar:1.2.0-cc33ac502a02e2fe830fe21e556234ee99351a7a]
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549) [pinot-all-1.2.0-jar-with-dependencies.jar:1.2.0-cc33ac502a02e2fe830fe21e556234ee99351a7a]
	at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
```

**Comment by Jackie-Jiang** [comment]
Seems like the controller is reading segment size for all tables. Do you see this error when loading the controller UI?

**Comment by Jackie-Jiang** [comment]
IMO, the root problem is not the log level, but Pinot not able to gracefully handle reading size for disabled tables. I've updated the title to reflect this.

**Comment by DaniilRoman** [comment]
Hey there 👋 
I'm looking for an issue to tackle and this one kept my attention, but before jumping into it I wanted to clarify if I understand this right 

Even if this is a UI-related problem, the graceful handling should be done inside the Controller component, right?

The flow we have is the following: we run some job, which has a process step(which includes calling `table/{tableName}/size` endpoint) and a post-process step (which include calling `endReplaceSegments` method). When we get a 404 from `table/{tableName}/size` call, we probably skip it and on the post-process step we get an exception. 
Does it make sense for you? 🤔 
 

Might it all start in [SegmentStatusChecker#processTable](https://github.com/DaniilRoman/pinot/blob/5dd6f8ac565d3a5d45d0f85a974e1aebf6c7c437/pinot-controller/src/main/java/org/apache/pinot/controller/helix/SegmentStatusChecker.java#L118) method when we're calling [updateTableSizeMetrics(tableNameWithType)](https://github.com/DaniilRoman/pinot/blob/5dd6f8ac565d3a5d45d0f85a974e1aebf6c7c437/pinot-controller/src/main/java/org/apache/pinot/controller/helix/SegmentStatusChecker.java#L123)? 🤔

**Comment by Jackie-Jiang** [comment]
@jayeshchoudhary Can you help guid @DaniilRoman on this? Does this issue still exist?
