### ISSUE TITLE
Spark ingestion with yarn cluster mode expecting the spec file to be available across all the node manage nodes

### ISSUE THREAD

**Issue by chrajeshbabu** [apache/pinot#14527]
When we just define ingestion spec file at one place start a spark ingestion job getting spec file not found exception. The reason is the spec file is not is getting distributing as like other dependencies. It would be better to add the spec file to distributed dependencies cache or serialise the spec object and pass as a property to the job so that same can be deserialised at the the task level or execution level.

```
java.lang.RuntimeException: Unable to read ingestion job spec file [/opt/ingestionSpec.yaml]
	at org.apache.pinot.spi.ingestion.batch.IngestionJobLauncher.getSegmentGenerationJobSpec(IngestionJobLauncher.java:78)
	at org.apache.pinot.tools.admin.command.LaunchDataIngestionJobCommand.execute(LaunchDataIngestionJobCommand.java:112)
	at org.apache.pinot.tools.Command.call(Command.java:33)
	at org.apache.pinot.tools.Command.call(Command.java:29)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2045)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
	at picocli.CommandLine.execute(CommandLine.java:2174)
	at org.apache.pinot.tools.admin.command.LaunchDataIngestionJobCommand.main(LaunchDataIngestionJobCommand.java:164)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:757)
Caused by: java.io.FileNotFoundException: /opt/ingestionSpec.yaml (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
	at java.base/java.io.FileReader.<init>(FileReader.java:60)
	at org.apache.pinot.spi.ingestion.batch.IngestionJobLauncher.getSegmentGenerationJobSpec(IngestionJobLauncher.java:76)
	... 17 more
```

**Comment by chrajeshbabu** [comment]
It's an improvement and working on it other wise it's painful to add the spec file across the nodes when there are many node managers in the cluster because containers can be launched anywhere in the cluster.

**Comment by chrajeshbabu** [comment]
Making use of spark-submit to load the data start the LaunchDataIngestionJobCommand from any node because underlying YARN Application master APIs get used to start the command which can span the containers anywhere in the cluster.

After going through the existing commands found that making use of LaunchSparkDataIngestionJobCommand doesn't requires to have spec file across all the nodes. Here is the example which would be better to document where ever spark is used for ingestion.

`
export SPARK_HOME=/opt/spark3
/opt/apache-pinot-1.2.0-bin/bin/pinot-admin.sh LaunchSparkDataIngestionJob -jobSpecFile=/opt/apache-pinot-1.2.0-bin/bin/specs/jobspec.yaml -deployMode cluster -master yarn -pinotBaseDir=/opt/apache-pinot-1.2.0-bin/ -pluginsToLoad pinot-hdfs:pinot-batch-ingestion-spark-3  -sparkConf executor-memory=20GB
`

**Comment by Jackie-Jiang** [comment]
cc @swaminathanmanish @KKcorps
