### ISSUE TITLE
java.lang.IllegalArgumentException: bound must be positive

### ISSUE THREAD

**Issue by lucentcosmos** [apache/pinot#1924]
bin/pinot-admin.sh PostQuery -query "select count(*) from mytable"
Executing command: PostQuery -brokerHost 43.138.13.224 -brokerPort 8099 -query select count(*) from mytable
Caught exception while processing POST request
java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388)
	at com.linkedin.pinot.broker.routing.builder.AbstractRoutingTableBuilder.findServers(AbstractRoutingTableBuilder.java:113)
	at com.linkedin.pinot.broker.routing.builder.DefaultRealtimeRoutingTableBuilder.findServers(DefaultRealtimeRoutingTableBuilder.java:103)
	at com.linkedin.pinot.broker.routing.HelixExternalViewBasedRouting.findServers(HelixExternalViewBasedRouting.java:100)
	at com.linkedin.pinot.broker.requesthandler.BrokerRequestHandler.findCandidateServers(BrokerRequestHandler.java:608)
	at com.linkedin.pinot.broker.requesthandler.BrokerRequestHandler.routeAndScatterBrokerRequest(BrokerRequestHandler.java:568)
	at com.linkedin.pinot.broker.requesthandler.BrokerRequestHandler.processOptimizedBrokerRequests(BrokerRequestHandler.java:483)
	at com.linkedin.pinot.broker.requesthandler.BrokerRequestHandler.processBrokerRequest(BrokerRequestHandler.java:342)
	at com.linkedin.pinot.broker.requesthandler.BrokerRequestHandler.handleRequest(BrokerRequestHandler.java:246)
	at com.linkedin.pinot.broker.servlet.PinotClientRequestServlet.doPost(PinotClientRequestServlet.java:74)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:688)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:770)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:669)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:455)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:560)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1072)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:382)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1006)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:365)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:485)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:937)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:998)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:856)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:628)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:748)
Result: bound must be positive

**Comment by shaunschembri** [comment]
I am trying to follow the How to Use Pinot tutorial. When I arrive to the step to query the data I get a similar error when I execute

bin/pinot-admin.sh PostQuery -query "select count(*) from flights"
Exception

java.io.IOException: Server returned HTTP response code: 500 for URL: http://my_private_ip:8099/query
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
        at org.apache.pinot.tools.admin.command.AbstractBaseAdminCommand.sendPostRequest(AbstractBaseAdminCommand.java:77)
        at org.apache.pinot.tools.admin.command.PostQueryCommand.run(PostQueryCommand.java:94)
        at org.apache.pinot.tools.admin.command.PostQueryCommand.execute(PostQueryCommand.java:100)
        at org.apache.pinot.tools.admin.PinotAdministrator.execute(PinotAdministrator.java:96)
        at org.apache.pinot.tools.admin.PinotAdministrator.main(PinotAdministrator.java:108)

In pinotController.log I also get

2019/02/11 14:41:54.759 ERROR [org.apache.pinot.controller.api.resources.PqlQueryResource] [] Caught exception while processing post request
java.io.IOException: Failed : HTTP error code : 500
        at org.apache.pinot.controller.api.resources.PqlQueryResource.sendPostRaw(PqlQueryResource.java:187)
        at org.apache.pinot.controller.api.resources.PqlQueryResource.sendPQLRaw(PqlQueryResource.java:230)
        at org.apache.pinot.controller.api.resources.PqlQueryResource.getQueryResponse(PqlQueryResource.java:140)
        at org.apache.pinot.controller.api.resources.PqlQueryResource.post(PqlQueryResource.java:80)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:679)
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:353)
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:200)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
        at java.lang.Thread.run(Thread.java:748)
		
OS = Centos 7.6
Pinot Version = Head on master branch (Commit ac058c5)
Java Version = openjdk version "1.8.0_191"

**Comment by snleee** [comment]
@shaunschembri Can you check and post the broker side log? `PostQuery` command will send the request to broker so it should contain specific error on why it throws 500 error.

**Comment by shaunschembri** [comment]
@snleee Here is the exception in pinotBroker.log

2019/02/12 07:59:23.384 ERROR [org.apache.pinot.broker.api.resources.PinotClientRequest] [] Caught exception while processing GET request
java.lang.IllegalArgumentException: bound must be positive
        at java.util.Random.nextInt(Random.java:388)
        at org.apache.pinot.broker.routing.builder.BaseRoutingTableBuilder.getRoutingTable(BaseRoutingTableBuilder.java:146)
        at org.apache.pinot.broker.routing.builder.DefaultRealtimeRoutingTableBuilder.getRoutingTable(DefaultRealtimeRoutingTableBuilder.java:100)
        at org.apache.pinot.broker.routing.HelixExternalViewBasedRouting.getRoutingTable(HelixExternalViewBasedRouting.java:103)
        at org.apache.pinot.broker.requesthandler.BaseBrokerRequestHandler.handleRequest(BaseBrokerRequestHandler.java:257)
        at org.apache.pinot.broker.api.resources.PinotClientRequest.processQueryPost(PinotClientRequest.java:98)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:679)
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:353)
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:200)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
        at java.lang.Thread.run(Thread.java:745)

**Comment by shaunschembri** [comment]
I found the issue and it was that the stream.kafka.decoder.class.name property was referencing an invalid class.  I updated this property to org.apache.pinot.core.realtime.impl.kafka.KafkaJSONMessageDecoder and it worked.

I updated the wiki however I cannot update the flights.tar.gz file.  If you want you can get it from here and update your wiki
https://github.com/shaunschembri/incubator-pinot-wiki/blob/master/flights.tar.gz?raw=true

I have also opened this PR with simillar updates
https://github.com/apache/incubator-pinot/pull/3826
