### ISSUE TITLE
java.lang.NoClassDefFoundError: scala/Function0

### ISSUE THREAD

**Issue by ghost** [apache/pinot#2282]
Hi, when I  run "bin/quick-start-realtime.sh" command , the following error happens. 
I checked the scala library, and it exists in pinot-0.016-pkg/lib directory. 

***** Starting Kafka *****
Exception in thread "main" java.lang.NoClassDefFoundError: scala/Function0
	at com.linkedin.pinot.common.utils.KafkaStarterUtils.startServer(KafkaStarterUtils.java:88)
	at com.linkedin.pinot.common.utils.KafkaStarterUtils.startServer(KafkaStarterUtils.java:65)
	at com.linkedin.pinot.tools.RealtimeQuickStart.execute(RealtimeQuickStart.java:65)
	at com.linkedin.pinot.tools.RealtimeQuickStart.main(RealtimeQuickStart.java:134)
Caused by: java.lang.ClassNotFoundException: scala.Function0
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 4 more

**Comment by kishoreg** [comment]
I am unable to reproduce this issue. What is the jdk version. @jfim any idea what might be the issue?

**Comment by alexband** [comment]
the version in quick-start-realtime.sh is scala-library-2.10.3.jar，  but when you build, the jar in lib is scala-library-2.10.5.jar 

this is my situation

**Comment by alexband** [comment]
also you need to add all the hadoop jars in the CLASSPATH

"$REPO"/hadoop-annotations-2.7.0.jar:"$REPO"/hadoop-auth-2.7.0.jar:"$REPO"/hadoop-client-2.7.0.jar:"$REPO"/hadoop-common-2.7.0.jar:"$REPO"/hadoop-hdfs-2.7.0.jar:"$REPO"/hadoop-mapreduce-client-app-2.7.0.jar:"$REPO"/hadoop-mapreduce-client-common-2.7.0.jar:"$REPO"/hadoop-mapreduce-client-core-2.7.0.jar:"$REPO"/hadoop-mapreduce-client-jobclient-2.7.0.jar:"$REPO"/hadoop-mapreduce-client-shuffle-2.7.0.jar:"$REPO"/hadoop-yarn-api-2.7.0.jar:"$REPO"/hadoop-yarn-client-2.7.0.jar:"$REPO"/hadoop-yarn-common-2.7.0.jar:"$REPO"/hadoop-yarn-server-common-2.7.0.jar

**Comment by alexband** [comment]
but still there is an error about CA

**Comment by kishoreg** [comment]
Can you print the entire classpath? You can add the following line to
quickstart script.

echo $CLASSPATH
