### ISSUE TITLE
Quickstart demo does not work

### ISSUE THREAD

**Issue by dyhuan123** [apache/pinot#4792]
Hi, I am following the instructions [here](https://pinot.readthedocs.io/en/latest/getting_started.html) to set up the offline quick start. But the I got 404 error in http://localhost:9000/query/. Can someone help check what is wrong? It is a bit frustrated that the quick start does not work by following the instructions. 

Maven version: 
```
Apache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117; 2019-08-27T08:06:16-07:00)
Maven home: /usr/local/Cellar/maven/3.6.2/libexec
Java version: 13.0.1, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/openjdk-13.0.1.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.6", arch: "x86_64", family: "mac"
```

Some errors I see when running `bin/quick-start-offline.sh`
```
Nov 05, 2019 5:16:28 PM org.glassfish.grizzly.http.server.NetworkListener start
INFO: Started listener bound to [0.0.0.0:9000]
Nov 05, 2019 5:16:28 PM org.glassfish.grizzly.http.server.HttpServer start
INFO: [HttpServer] Started.
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlRootElement
	at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:270)
	at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:185)
	at io.swagger.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:100)
	at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:236)
	at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:185)
	at io.swagger.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:100)
	at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:161)
	at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:112)
	at io.swagger.converter.ModelConverterContextImpl.resolveProperty(ModelConverterContextImpl.java:80)
	at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:126)
	at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:112)
	at io.swagger.converter.ModelConverterContextImpl.resolveProperty(ModelConverterContextImpl.java:80)
	at io.swagger.converter.ModelConverters.readAsProperty(ModelConverters.java:58)
	at io.swagger.jaxrs.Reader.parseMethod(Reader.java:896)
	at io.swagger.jaxrs.Reader.read(Reader.java:322)
	at io.swagger.jaxrs.Reader.read(Reader.java:172)
	at io.swagger.jaxrs.config.BeanConfig.scanAndRead(BeanConfig.java:242)
	at io.swagger.jaxrs.config.BeanConfig.setScan(BeanConfig.java:221)
	at org.apache.pinot.controller.api.ControllerAdminApiApplication.setupSwagger(ControllerAdminApiApplication.java:126)
	at org.apache.pinot.controller.api.ControllerAdminApiApplication.start(ControllerAdminApiApplication.java:87)
	at org.apache.pinot.controller.ControllerStarter.setUpPinotController(ControllerStarter.java:355)
	at org.apache.pinot.controller.ControllerStarter.start(ControllerStarter.java:229)
	at org.apache.pinot.tools.admin.command.StartControllerCommand.execute(StartControllerCommand.java:163)
	at org.apache.pinot.tools.admin.command.QuickstartRunner.startControllers(QuickstartRunner.java:89)
	at org.apache.pinot.tools.admin.command.QuickstartRunner.startAll(QuickstartRunner.java:124)
	at org.apache.pinot.tools.Quickstart.execute(Quickstart.java:147)
	at org.apache.pinot.tools.Quickstart.main(Quickstart.java:209)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlRootElement
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 27 more
```

I have found this relevant [issue](https://github.com/apache/incubator-pinot/issues/3929) and tried adding dependency in `pinot-distribution/pom.xml` but that did not solve the issue. 

Thanks!

**Comment by sunny19930321** [comment]
I used jdk1.8, did not have this problem

**Comment by kishoreg** [comment]
Maybe something to do with jdk version. can you try with a jdk 9.  Let me try to reproduce this with jdk version 13

**Comment by mayankshriv** [comment]
@dyhuan123 As @kishoreg suggested could you please try with jdk 9 and let us know if you still see an issue?

**Comment by dyhuan123** [comment]
JDK 9 is already not supported. I tried changing to JDK 11 in my terminal and run `mvn install package -DskipTests -Pbin-dist` again as mentioned in the instructions. But still it is the same problem. 

Any suggestion how can I downgrade to JDK 9 or even better how to fix this in the most recent JDK 13? 

Thanks!

**Comment by sunny19930321** [comment]
> JDK 9 is already not supported. I tried changing to JDK 11 in my terminal and run `mvn install package -DskipTests -Pbin-dist` again as mentioned in the instructions. But still it is the same problem.
> 
> Any suggestion how can I downgrade to JDK 9 or even better how to fix this in the most recent JDK 13?
> 
> Thanks!

I used jdk8 and there was no problem. @dyhuan123 I hope it helps you!

**Comment by mayankshriv** [comment]
@dyhuan123 Within LinkedIn we use jdk8, and I was under the impression that there's usage of jdk9 in the community. If jdk8 works for you please try that. If not, we can help debug the issue with jdk9.

**Comment by xiangfu0** [comment]
close as not valid
