### ISSUE TITLE
[TE] Unique index or primary key violation issue for EVALUATION_INDEX table

### ISSUE THREAD

**Issue by depatel1010** [apache/pinot#6195]
An SQLException is thrown by the backend for `EVALUATION_INDEX_INDEX_C ON PUBLIC.EVALUATION_INDEX(DETECTION_CONFIG_ID, START_TIME, END_TIME)` key. The issue occurs when `dimensionExploration` is turned on and multiple anomalies for the same time window are detected in a single run.

PFA the logs and Detection configurations used to recreate the issue with the given default h2db and default `data-source-configs.yml` file.

Dataset used: "H2.H2.total_pageviews" (uses pageviews.csv)

dimension explored during anomaly detection: "device"

Additional Changes to make: mark `worker`, `detectionPipeline` and `detectionAlert` flags as `true` in `detector.yml`

Error-Log:
``` log
11:52:02.155 [task-executor-2] INFO org.apache.pinot.thirdeye.detection.DefaultDataProvider - Fetched 2 anomalies for slice AnomalySlice{detectionId='15', startTime='1603771003484', endTime='1603786920012', filters='{}', isTaggedAsChild='false', detectionComponentNames='[]'}
11:52:02.157 [task-executor-2] INFO org.apache.pinot.thirdeye.detection.DefaultDataProvider - Fetched 2 anomalies for slice AnomalySlice{detectionId='15', startTime='1603771003484', endTime='1603786920012', filters='{}', isTaggedAsChild='false', detectionComponentNames='[]'}
11:52:02.163 [task-executor-2] ERROR org.apache.pinot.thirdeye.datalayer.dao.GenericPojoDao - Exception while executing query task
org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: "EVALUATION_INDEX_INDEX_C ON PUBLIC.EVALUATION_INDEX(DETECTION_CONFIG_ID, START_TIME, END_TIME) VALUES (15, 1603778203485, 1603779720011, 3)"; SQL statement:
INSERT INTO evaluation_index(base_id,detection_config_id,start_time,end_time,detectorname,mape,create_time,update_time,version) VALUES(?,?,?,?,?,?,?,?,?) [23505-192]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.index.BaseIndex.getDuplicateKeyException(BaseIndex.java:103)
	at org.h2.mvstore.db.MVSecondaryIndex.checkUnique(MVSecondaryIndex.java:231)
	at org.h2.mvstore.db.MVSecondaryIndex.add(MVSecondaryIndex.java:190)
	at org.h2.mvstore.db.MVTable.addRow(MVTable.java:704)
	at org.h2.command.dml.Insert.insertRows(Insert.java:156)
	at org.h2.command.dml.Insert.update(Insert.java:114)
	at org.h2.command.CommandContainer.update(CommandContainer.java:98)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:160)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:146)
	at sun.reflect.GeneratedMethodAccessor133.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy78.executeUpdate(Unknown Source)
	at org.apache.pinot.thirdeye.datalayer.dao.GenericPojoDao$1.handle(GenericPojoDao.java:261)
	at org.apache.pinot.thirdeye.datalayer.dao.GenericPojoDao$1.handle(GenericPojoDao.java:229)
	at org.apache.pinot.thirdeye.datalayer.dao.GenericPojoDao.runTask(GenericPojoDao.java:890)
	at org.apache.pinot.thirdeye.datalayer.dao.GenericPojoDao.put(GenericPojoDao.java:229)
	at org.apache.pinot.thirdeye.datalayer.bao.jdbc.AbstractManagerImpl.save(AbstractManagerImpl.java:66)
	at org.apache.pinot.thirdeye.detection.DetectionPipelineTaskRunner.execute(DetectionPipelineTaskRunner.java:159)
	at org.apache.pinot.thirdeye.anomaly.task.TaskDriver$1$1.call(TaskDriver.java:128)
	at org.apache.pinot.thirdeye.anomaly.task.TaskDriver$1$1.call(TaskDriver.java:125)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Detection Configurations:

``` yaml
detectionName: test
description: If this alert fires then it means so-and-so and check so-and-so for irregularities
metric: pageviews
dataset: H2.H2.total_pageviews
cron: "0 */2 * * * ? *"
dimensionExploration:
  dimensions:
    - device
rules:
- detection:
    - name: detection_rule_1
      type: PERCENTAGE_RULE
      params:
        offset: wo1w
        percentageChange: 0.01
```

`generic_json_entity` row for the rule created.
```json
{
	"id": null,
	"version": 0,
	"updateTime": null,
	"createdBy": null,
	"updatedBy": null,
	"cron": "0 */2 * * * ? *",
	"name": "test",
	"description": "If this alert fires then it means so-and-so and check so-and-so for irregularities",
	"lastTimestamp": -1,
	"properties": {
		"className": "org.apache.pinot.thirdeye.detection.wrapper.ChildKeepingMergeWrapper",
		"nested": [{
			"nestedMetricUrns": ["thirdeye:metric:7"],
			"className": "org.apache.pinot.thirdeye.detection.algorithm.DimensionWrapper",
			"metricUrn": "thirdeye:metric:7",
			"nested": [{
				"baselineValueProvider": "$detection_rule_1:PERCENTAGE_RULE",
				"className": "org.apache.pinot.thirdeye.detection.wrapper.BaselineFillingMergeWrapper",
				"nested": [{
					"bucketPeriod": "P1D",
					"className": "org.apache.pinot.thirdeye.detection.wrapper.AnomalyDetectorWrapper",
					"subEntityName": "test"
				}],
				"detector": "$detection_rule_1:PERCENTAGE_RULE"
			}],
			"dimensions": ["device"]
		}]
	},
	"active": true,
	"yaml": "detectionName: test\ndescription: If this alert fires then it means so-and-so and check so-and-so for irregularities\nmetric: pageviews\ndataset: H2.H2.total_pageviews\ncron: \"0 */2 * * * ? *\"\ndimensionExploration:\n  dimensions:\n    - device\nrules:\n- detection:\n    - name: detection_rule_1\n      type: PERCENTAGE_RULE\n      params:\n        offset: wo1w\n        percentageChange: 0.01",
	"componentSpecs": {
		"detection_rule_1:PERCENTAGE_RULE": {
			"className": "org.apache.pinot.thirdeye.detection.components.PercentageChangeRuleDetector",
			"metricUrn": "thirdeye:metric:7",
			"offset": "wo1w",
			"percentageChange": 0.01
		}
	},
	"lastTuningTimestamp": 0,
	"owners": [],
	"dataQualityProperties": {},
	"taskTriggerFallBackTimeInSec": 0,
	"health": null,
	"dataAvailabilitySchedule": false
}
```
Slack Chat Reference: https://apache-thirdeye.slack.com/archives/C014CS60A22/p1598938054008700
@suvodeep-pyne  please have a look. 😀☝️  
Thanks.

**Comment by Jackie-Jiang** [comment]
Closing third-eye related issue as the project has been moved out of the pinot repo. For unsolved issue that still applies, please create a new one under third-eye repo: https://github.com/project-thirdeye/thirdeye
