### ISSUE TITLE
A problem occurs when running thrideye using helm.

### ISSUE THREAD

**Issue by minwoo-jung** [apache/pinot#6591]
Hello~ 

When thirdeye is executed using helm, if the following message is displayed, it does not work. The same problem occurs when using the master branch, 0.6.0 release branch.

```
Running Thirdeye frontend config: ./config/pinot-quickstart
log4j:WARN No appenders could be found for logger (org.apache.pinot.thirdeye.dashboard.ThirdEyeDashboardApplication).
log4j:WARN Please initialize the log4j system properly.
[2021-02-18 12:25:39] INFO  [main] o.h.v.i.u.Version - HV000001: Hibernate Validator null 
io.dropwizard.configuration.ConfigurationParsingException: ./config/pinot-quickstart/dashboard.yml has an error:
  * Failed to parse configuration at: logging; Cannot construct instance of `io.dropwizard.logging.DefaultLoggingFactory`, problem: Unable to acquire the logger context
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: org.apache.pinot.thirdeye.dashboard.ThirdEyeDashboardConfiguration["logging"])

	at io.dropwizard.configuration.ConfigurationParsingException$Builder.build(ConfigurationParsingException.java:279)
	at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:156)
	at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:89)
	at io.dropwizard.cli.ConfiguredCommand.parseConfiguration(ConfiguredCommand.java:126)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:74)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:93)
	at org.apache.pinot.thirdeye.dashboard.ThirdEyeDashboardApplication.main(ThirdEyeDashboardApplication.java:200)
Caused by: com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `io.dropwizard.logging.DefaultLoggingFactory`, problem: Unable to acquire the logger context
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: org.apache.pinot.thirdeye.dashboard.ThirdEyeDashboardConfiguration["logging"])
	at com.fasterxml.jackson.databind.exc.ValueInstantiationException.from(ValueInstantiationException.java:47)
	at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:1732)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.wrapAsJsonMappingException(StdValueInstantiator.java:491)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.rewrapCtorProblem(StdValueInstantiator.java:514)
	at com.fasterxml.jackson.module.afterburner.deser.OptimizedValueInstantiator._handleInstantiationProblem(OptimizedValueInstantiator.java:59)
	at io.dropwizard.logging.DefaultLoggingFactory$Creator4JacksonDeserializer53fd30f2.createUsingDefault(io/dropwizard/logging/DefaultLoggingFactory$Creator4JacksonDeserializer.java)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:277)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:189)
	at com.fasterxml.jackson.module.afterburner.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:120)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedUsingDefaultImpl(AsPropertyTypeDeserializer.java:178)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:105)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:254)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:252)
	at com.fasterxml.jackson.module.afterburner.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:155)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4173)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2467)
	at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:127)
	... 6 more
Caused by: java.lang.IllegalStateException: Unable to acquire the logger context
	at io.dropwizard.logging.LoggingUtil.getLoggerContext(LoggingUtil.java:46)
	at io.dropwizard.logging.DefaultLoggingFactory.<init>(DefaultLoggingFactory.java:77)
	... 19 more

```

When I analyzed the problem, it seems to be a logging-related issue, but I do not know how to fix it. Can I get guidance on how to fix it?

**Comment by FcoLopera** [comment]
I have suffered the same issue. Fortunately, there is a solution provided by the community, you can check it here: 
- https://communityinviter.com/apps/apache-thirdeye/apache-thirdeye.

Thanks to @suvodeep-pyne, he has a fork of the incubator project: 
- https://github.com/suvodeep-pyne/incubator-pinot/tree/1.x/kubernetes/helm/thirdeye

By using it and the thirdeye image from his dockerhub repository ( spyne/thirdeye:1.4), I finally make it work.

Instructions provided by another user (ayush sharma, sorry I have not found your Github user ).
```
git clone https://github.com/suvodeep-pyne/incubator-pinot
git checkout 1.x
kubectl create ns my-pinot-kube
helm install pinot spyne/incubator-pinot/kubernetes/helm/pinot -n my-pinot-kube --set replicas=1
cd spyne/incubator-pinot/kubernetes/helm/thirdeye
./install.sh --set image.repository=spyne/thirdeye --set image.tag=1.4 -n my-pinot-kube
```
