### ISSUE TITLE
Controller Crashing - repetition of same config causing multi value setting

### ISSUE THREAD

**Issue by opschronicle** [apache/pinot#6595]
I have following settings in controller config where validation.frequencyInSeconds is accidentally repeated. This is causing controller to crash as the value is derived as multi value. it will be better to take either last defined value or avoid this crash.

controller.realtime.segment.validation.frequencyInSeconds=300
controller.realtime.segment.validation.frequencyInSeconds=900
controller.broker.resource.validation.frequencyInSeconds=900

Error:

2021/02/18 14:46:44.389 ERROR [StartServiceManagerCommand] [main] Failed to start a Pinot [CONTROLLER] at 39.246 since launch
java.lang.NumberFormatException: For input string: "[300, 900]"
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_282]
at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_282]

**Comment by fx19880617** [comment]
I feel we should try to validate those configures and provide more meaningful error msgs, e.g. the config `controller.realtime.segment.validation.frequencyInSeconds` is invalid.

**Comment by kirusigan03** [comment]
Hi, I would like to work on this issue. Could you please assign it to me?

**Comment by Jackie-Jiang** [comment]
Addressed by #15648, which also closed #15646. Service config files now reject duplicate keys before loading, with a ConfigurationException identifying the duplicate key, file path, and both line numbers. This validation covers both controller startup and the service-manager bootstrap path from this report, and the change includes a regression test for duplicate-key detection and line numbers.

Duplicate settings still prevent startup; the implemented behavior is explicit validation rather than last-value-wins. This addresses the request in this issue for a more meaningful configuration error.
