### ISSUE TITLE
StringColumnPreIndexStatsCollector doesnt work for datetime

### ISSUE THREAD

**Issue by walterddr** [apache/pinot#7786]
datetime fields are not necessarily sorted by string ordering. 

adding StringDatetimeColumnPreIndexStatsCollector to handle the ordering issue

**Comment by Jackie-Jiang** [comment]
We don't have a data type for date time as of now, so we need to use other data type (`STRING`, `INT` or `LONG`) to represent the values. We process date time fields the same way as dimensions and metrics, so the ordering must be aligned with the data type. Ordering date time field differently will cause wrong result.

**Comment by walterddr** [comment]
well. this will cause problem because it doesn't give correct statistics to the SegmentColumnarIndexCreator
```
2021/11/17 11:56:03.510 ERROR [SegmentGenerationJobRunner] [pool-2-thread-1] Failed to generate Pinot segment for file - file:/data/mark.csv
java.lang.IllegalArgumentException: The end instant must be greater than the start instant
	at org.joda.time.base.AbstractInterval.checkInterval(AbstractInterval.java:63) ~[pinot-all-0.9.0-SNAPSHOT-jar-with-dependencies.jar:0.9.0-SNAPSHOT-540e70e9e3e24bdb2a14f56b2c1264180abaeda8]
	at org.joda.time.base.BaseInterval.<init>(BaseInterval.java:73) ~[pinot-all-0.9.0-SNAPSHOT-jar-with-dependencies.jar:0.9.0-SNAPSHOT-540e70e9e3e24bdb2a14f56b2c1264180abaeda8]
	at org.joda.time.Interval.<init>(Interval.java:173) ~[pinot-all-0.9.0-SNAPSHOT-jar-with-dependencies.jar:0.9.0-SNAPSHOT-540e70e9e3e24bdb2a14f56b2c1264180abaeda8]
	at org.apache.pinot.segment.local.segment.creator.impl.SegmentColumnarIndexCreator.writeMetadata(SegmentColumnarIndexCreator.java:672) ~[pinot-all-0.9.0-SNAPSHOT-jar-with-dependencies.jar:0.9.0-SNAPSHOT-540e70e9e3e24bdb2a14f56b2c1264180abaeda8]
	at org.apache.pinot.segment.local.segment.creator.impl.SegmentColumnarIndexCreator.seal(SegmentColumnarIndexCreator.java:603) ~[pinot-all-0.9.0-SNAPSHOT-jar-with-dependencies.jar:0.9.0-SNAPSHOT-540e70e9e3e24bdb2a14f56b2c1264180abaeda8]
	at org.apache.pinot.segment.local.segment.creator.impl.SegmentIndexCreationDriverImpl.handlePostCreation(SegmentIndexCreationDriverImpl.java:286) ~[pinot-all-0.9.0-SNAPSHOT-jar-with-dependencies.jar:0.9.0-SNAPSHOT-540e70e9e3e24bdb2a14f56b2c1264180abaeda8]
	at org.apache.pinot.segment.local.segment.creator.impl.SegmentIndexCreationDriverImpl.build(SegmentIndexCreationDriverImpl.java:258) ~[pinot-all-0.9.0-SNAPSHOT-jar-with-dependencies.jar:0.9.0-SNAPSHOT-540e70e9e3e24bdb2a14f56b2c1264180abaeda8]
...
```

**Comment by Jackie-Jiang** [comment]
I see. I feel we should force the time format to increase along with the time (e.g. `yyyyMMdd` is fine, but not `MMddyyyy`). If the original time value does not follow such time format, we can use ingestion transform to convert it

**Comment by walterddr** [comment]
that's definitely one solution but IMO it will make user experience bad. either we enhance our documentation and error messaging; or we should automatically populate a shadow timeColumn that's sorted by time. 

Especially when we have the tableConfig / ingestionConfig telling us we should sort by underlying datetime.

**Comment by Jackie-Jiang** [comment]
E.g. date time is stored as `STRING` but ordered as time value, the following query will fail because it will still filter with string order:
`SELECT * FROM myTable WHERE timeCol < '11182021'`
This query will match time value `01012022`.

Because of this behavior, we should definitely validate the time format to ensure the time ordering is the same as data type ordering.

**Comment by walterddr** [comment]
> E.g. date time is stored as `STRING` but ordered as time value, the following query will fail because it will still filter with string order: `SELECT * FROM myTable WHERE timeCol < '11182021'` This query will match time value `01012022`.
> 
> Because of this behavior, we should definitely validate the time format to ensure the time ordering is the same as data type ordering.

Well in that case yeah. I don't see a better solution. But I still think we need some sort of automated solution instead of relying on the user to safe guard this

**Comment by Jackie-Jiang** [comment]
Agree. We should provide a `DATE_TIME` data type which is similar to the `TIMESTAMP` data type but with timezone info embedded, then everything would work seamlessly.
