### ISSUE TITLE
Query 500 on `select col, count(*) from table` missing `group by` (query mistake)

### ISSUE THREAD

**Issue by lgo** [apache/pinot#7868]
While writing some adhoc queries, I found the controller query console was throwing a 500 and I was scratching my head about the error until I realized the query was incorrect. I'm not sure if Pinot often 500s on invalid queries, or this is a corner case, but certainly making sure a helpful error is returned is better that informs the user their query is invalid.

For example, I was trying
```sql
select $segmentName, count(*)
from table
where $segmentName = 'bar'
```
Mind, the same error happened when I used actual columns rather than the virtual column.

And it was raising the following exception
```ProcessingException(errorCode:450, message:InternalError:
java.io.IOException: Failed : HTTP error code : 500
	at org.apache.pinot.controller.api.resources.PinotQueryResource.sendPostRaw(PinotQueryResource.java:305)
	at org.apache.pinot.controller.api.resources.PinotQueryResource.sendRequestRaw(PinotQueryResource.java:343)
	at org.apache.pinot.controller.api.resources.PinotQueryResource.getQueryResponse(PinotQueryResource.java:225)
	at org.apache.pinot.controller.api.resources.PinotQueryResource.handlePostSql(PinotQueryResource.java:137))
```

**Comment by mayankshriv** [comment]
Hello Joey,
Thanks for finding this issue. Do you mind creating a GitHub issue with details for both the problems you encountered?
Also, please feel free to join the Apache Pinot slack community for more interactive discussions.

Thanks
Mayank

**Comment by Jackie-Jiang** [comment]
We should validate this query on the broker side and directly reject it if the query is invalid

@xiangfu0 For the example query above, should we attach the group-by clause if it is missing or just fail it?

**Comment by PrachiPrakash** [comment]
https://github.com/apache/pinot/pull/7972/commits/b6d96982294b7a0158fae3a434050623f052caa1 this tries to solve this problem by validating it after the query compilation. it would be really good if someone can review this change.
Thanks,
Prachi
