### ISSUE TITLE
Queries are failed under load(looks like regression bug)

### ISSUE THREAD

**Issue by rasmus93** [apache/pinot#8156]
Hi, seems like there is problem with running many queries in parallel in latest build.
While performing load test I found such exceptions in logs:
```
2022/02/07 19:55:51.317 ERROR [InstanceRequestHandler] [nioEventLoopGroup-3-1] Query processing error: 
org.apache.thrift.protocol.TProtocolException: don't know what type: 15
        at org.apache.thrift.protocol.TCompactProtocol.getTType(TCompactProtocol.java:898) ~[pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at org.apache.thrift.protocol.TCompactProtocol.readFieldBegin(TCompactProtocol.java:562) ~[pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at org.apache.thrift.protocol.TProtocolUtil.skip(TProtocolUtil.java:108) ~[pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at org.apache.thrift.protocol.TProtocolUtil.skip(TProtocolUtil.java:112) ~[pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at org.apache.thrift.protocol.TProtocolUtil.skip(TProtocolUtil.java:112) ~[pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at org.apache.thrift.protocol.TProtocolUtil.skip(TProtocolUtil.java:60) ~[pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at org.apache.pinot.common.request.InstanceRequest$InstanceRequestStandardScheme.read(InstanceRequest.java:679) ~[pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at org.apache.pinot.common.request.InstanceRequest$InstanceRequestStandardScheme.read(InstanceRequest.java:662) ~[pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at org.apache.pinot.common.request.InstanceRequest.read(InstanceRequest.java:569) ~[pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at org.apache.thrift.TDeserializer.deserialize(TDeserializer.java:81) ~[pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at org.apache.thrift.TDeserializer.deserialize(TDeserializer.java:67) ~[pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at org.apache.pinot.core.transport.InstanceRequestHandler.channelRead0(InstanceRequestHandler.java:110) [pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at org.apache.pinot.core.transport.InstanceRequestHandler.channelRead0(InstanceRequestHandler.java:56) [pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at shaded.io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311) [pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at shaded.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:425) [pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```
and 
```
2022/02/07 20:14:39.500 ERROR [InstanceRequestHandler] [nioEventLoopGroup-3-1] Query processing error:
org.apache.thrift.protocol.TProtocolException: Required field 'query' is unset! Struct:InstanceRequest(requestId:1635638400000, query:null)
        at org.apache.pinot.common.request.InstanceRequest.validate(InstanceRequest.java:629) ~[pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at org.apache.pinot.common.request.InstanceRequest$InstanceRequestStandardScheme.read(InstanceRequest.java:731) ~[pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at org.apache.pinot.common.request.InstanceRequest$InstanceRequestStandardScheme.read(InstanceRequest.java:662) ~[pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at org.apache.pinot.common.request.InstanceRequest.read(InstanceRequest.java:569) ~[pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at org.apache.thrift.TDeserializer.deserialize(TDeserializer.java:81) ~[pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at org.apache.thrift.TDeserializer.deserialize(TDeserializer.java:67) ~[pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at org.apache.pinot.core.transport.InstanceRequestHandler.channelRead0(InstanceRequestHandler.java:110) [pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at org.apache.pinot.core.transport.InstanceRequestHandler.channelRead0(InstanceRequestHandler.java:56) [pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at shaded.io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [pinot-all-0.10.0-SNAPSHOT-jar-with-dependencies.jar:0.10.0-SNAPSHOT-3c98a4469644fe94c40ec004c0792870ef9d8af3]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```

Such exception I get even if run load only with queries like `select count(column) from test_table`. I can say that this exception is happened only on high load, i.e. I found request which were failed in logs and tried to run it separately then everything is ok.

Also I found that such problem exists in build with this commit - [3c98a44696](https://github.com/apache/pinot/commit/3c98a4469644fe94c40ec004c0792870ef9d8af3), but in build with commit - [34f371d1cb](https://github.com/apache/pinot/commit/34f371d1cb6dbe9e174094d373fc8682e814ffdd) everything is ok, so it looks like regression bug

**Comment by richardstartin** [comment]
Hi @rasmus93, thanks for the report. It is unlikely that this is caused by 3c98a4469644fe94c40ec004c0792870ef9d8af3 if it affects `select count(column) from test_table` because the code changed there is only invoked by the `lookup` UDF. There are several commits between the two you report:

```
commit 86fe41e2e9c17090f1fa9bcc39dbd61e3b649402
Author: Liang Mingqiang <miliang@linkedin.com>
Date:   Tue Feb 1 10:50:17 2022 -0800

    Timeout if waiting server channel lock takes a long time (#8083)
    
    - make requests be able to time out early when "waiting the channel lock".
    - move the request serialization logic out of critical section.

commit 3f761544e2fb6532558c9882f18bfd48e4c927e6
Author: Richard Startin <richard@startree.ai>
Date:   Tue Feb 1 18:48:20 2022 +0000

    Upgrade to JsonPath 2.7.0 (#7819)

commit 88dda0e2a09fa035038c8af98aa0ee76ecdff136
Author: Jialiang Li <jlli@linkedin.com>
Date:   Tue Feb 1 10:29:23 2022 -0800

    Validate the numbers of input and output files in HadoopSegmentCreationJob (#8098)
    
    Co-authored-by: Jack Li(Analytics Engineering) <jlli@jlli-mn1.linkedin.biz>

commit 71e28a2313a0e175e64398b195e488b0fd67d49b
Author: Liang Mingqiang <miliang@linkedin.com>
Date:   Mon Jan 31 23:53:10 2022 -0800

    Wire EmptySegmentPruner to routing config (#8067)
    
    * Remove EmptySegmentPruner from the default path and wire it to the config
    
    * fix unit test
    
    * rename isKinesisEnabled as needsEmptySegmentPruner and move to TableConfigUtils
    
    * add pinot-kinesis dependency to pinot-segment-local
    
    * hardcode kinesis in TableConfigUtils to avoid pulling pinot-kinesis module as dependency
    
    * Minor change on the comments

commit 6eb71f601b0a8fe33147e984e1de5ea93960b9f2
Author: Richard Startin <richard@startree.ai>
Date:   Tue Feb 1 07:25:58 2022 +0000

    downgrade verbose log message to DEBUG (#8096)

commit bd42dc38a4b44b03112deefca5498f8bcdde43d9
Author: Jeff Moszuti <moszutij@users.noreply.github.com>
Date:   Tue Feb 1 07:00:07 2022 +0000

    Support for TIMESTAMP data type in Configuration Recommendation Engin… (#8087)
    
    * Support for TIMESTAMP data type in Configuration Recommendation Engine (#8086)
    
    * add unit test for TIMESTAMP data type

commit a22cc0022933df6de85b4b966556e95ab5b81c5f
Author: Prachi Prakash <prachiprakash80@gmail.com>
Date:   Tue Feb 1 12:28:11 2022 +0530

    Broker Side validation for the query with aggregation and col but without group by (#7972)
    
    * validate that col expr and aggregate expr is not present without group by
    
    * fixing the AggregateMetricsRules test.
    
    * changes as per the review comments
```

and I think the most likely culprit is 86fe41e2e9c17090f1fa9bcc39dbd61e3b649402 which times out queries on the broker rather than let them wait indefinitely, especially since you report that this happens in a load test. If so, it's not really a regression (this is strictly better behaviour) but we should produce better error messages before releasing 0.10.0. 

Would you be open to building at 3f761544e2fb6532558c9882f18bfd48e4c927e6 and running your test to help narrow this down?

**Comment by Jackie-Jiang** [comment]
I think the issue is most likely caused by #8083 where the same `TSerializer` is shared across multiple threads. Per this [ticket](https://issues.apache.org/jira/browse/THRIFT-2218), seems it is not thread-safe. @mqliang Can you please help fix it?

**Comment by mqliang** [comment]
Sure, will send a PR soon

**Comment by rasmus93** [comment]
I have tested with latest build(which contains https://github.com/apache/pinot/pull/8160 fix) and everything is good.
So I will close issue. Thanks for quick fix!
