### ISSUE TITLE
[Flaky test] Failed to upload segments in integration tests

### ISSUE THREAD

**Issue by Jackie-Jiang** [apache/pinot#8265]
Example failure run: https://github.com/apache/pinot/runs/5365010836?check_suite_focus=true

Exception stack trace:
```
20:24:09.131 ERROR [WebApplicationExceptionMapper] [jersey-server-managed-async-executor-1] Server error: 
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 0
	at java.util.ArrayList.add(ArrayList.java:487) ~[?:?]
	at java.util.ArrayList.add(ArrayList.java:499) ~[?:?]
	at org.jvnet.mimepull.WeakDataFile.<init>(WeakDataFile.java:68) ~[mimepull-1.9.11.jar:?]
	at org.jvnet.mimepull.DataFile.<init>(DataFile.java:28) ~[mimepull-1.9.11.jar:?]
	at org.jvnet.mimepull.MemoryData.createNext(MemoryData.java:72) ~[mimepull-1.9.11.jar:?]
	at org.jvnet.mimepull.Chunk.createNext(Chunk.java:34) ~[mimepull-1.9.11.jar:?]
	at org.jvnet.mimepull.DataHead.addBody(DataHead.java:57) ~[mimepull-1.9.11.jar:?]
	at org.jvnet.mimepull.MIMEPart.addBody(MIMEPart.java:214) ~[mimepull-1.9.11.jar:?]
	at org.jvnet.mimepull.MIMEMessage.makeProgress(MIMEMessage.java:241) ~[mimepull-1.9.11.jar:?]
	at org.jvnet.mimepull.MIMEMessage.parseAll(MIMEMessage.java:160) ~[mimepull-1.9.11.jar:?]
	at org.jvnet.mimepull.MIMEMessage.getAttachments(MIMEMessage.java:86) ~[mimepull-1.9.11.jar:?]
	at org.glassfish.jersey.media.multipart.internal.MultiPartReaderClientSide.getMimeParts(MultiPartReaderClientSide.java:248) ~[jersey-media-multipart-2.28.jar:?]
	at org.glassfish.jersey.media.multipart.internal.MultiPartReaderClientSide.readMultiPart(MultiPartReaderClientSide.java:207) ~[jersey-media-multipart-2.28.jar:?]
	at org.glassfish.jersey.media.multipart.internal.MultiPartReaderServerSide.readMultiPart(MultiPartReaderServerSide.java:67) ~[jersey-media-multipart-2.28.jar:?]
	at org.glassfish.jersey.media.multipart.internal.MultiPartReaderClientSide.readFrom(MultiPartReaderClientSide.java:159) ~[jersey-media-multipart-2.28.jar:?]
	at org.glassfish.jersey.media.multipart.internal.MultiPartReaderClientSide.readFrom(MultiPartReaderClientSide.java:69) ~[jersey-media-multipart-2.28.jar:?]
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:233) ~[jersey-common-2.28.jar:?]
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:212) ~[jersey-common-2.28.jar:?]
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:132) ~[jersey-common-2.28.jar:?]
	at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundReadFrom(MappableExceptionWrapperInterceptor.java:49) ~[jersey-server-2.28.jar:?]
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:132) ~[jersey-common-2.28.jar:?]
	at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1067) ~[jersey-common-2.28.jar:?]
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:850) ~[jersey-common-2.28.jar:?]
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:784) ~[jersey-common-2.28.jar:?]
	at org.glassfish.jersey.server.ContainerRequest.readEntity(ContainerRequest.java:210) ~[jersey-server-2.28.jar:?]
	at org.glassfish.jersey.media.multipart.internal.FormDataParamValueParamProvider$ValueProvider.getEntity(FormDataParamValueParamProvider.java:84) ~[jersey-media-multipart-2.28.jar:?]
	at org.glassfish.jersey.media.multipart.internal.FormDataParamValueParamProvider$FormDataMultiPartProvider.apply(FormDataParamValueParamProvider.java:102) ~[jersey-media-multipart-2.28.jar:?]
	at org.glassfish.jersey.media.multipart.internal.FormDataParamValueParamProvider$FormDataMultiPartProvider.apply(FormDataParamValueParamProvider.java:98) ~[jersey-media-multipart-2.28.jar:?]
	at org.glassfish.jersey.server.spi.internal.ParamValueFactoryWithSource.apply(ParamValueFactoryWithSource.java:50) ~[jersey-server-2.28.jar:?]
	at org.glassfish.jersey.server.spi.internal.ParameterValueHelper.getParameterValues(ParameterValueHelper.java:68) ~[jersey-server-2.28.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$AbstractMethodParamInvoker.getParamValues(JavaResourceMethodDispatcherProvider.java:109) ~[jersey-server-2.28.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$VoidOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:159) ~[jersey-server-2.28.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79) ~[jersey-server-2.28.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469) ~[jersey-server-2.28.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.lambda$apply$0(ResourceMethodInvoker.java:381) ~[jersey-server-2.28.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder$2$1.run(ServerRuntime.java:819) ~[jersey-server-2.28.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) ~[jersey-common-2.28.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) ~[jersey-common-2.28.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) ~[jersey-common-2.28.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) ~[jersey-common-2.28.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244) ~[jersey-common-2.28.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) ~[jersey-common-2.28.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder$2.run(ServerRuntime.java:814) ~[jersey-server-2.28.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Comment by Jackie-Jiang** [comment]
This is caused by a bug in the `metro-mimepull` library: https://github.com/eclipse-ee4j/metro-mimepull/issues/11
