### ISSUE TITLE
PinotSinkIntegrationTest is flaky

### ISSUE THREAD

**Issue by Jackie-Jiang** [apache/pinot#8316]
Failure run: https://github.com/apache/pinot/runs/5468924909?check_suite_focus=true

**Comment by Jackie-Jiang** [comment]
@yupeng9 Can you please help take a look?

**Comment by xiangfu0** [comment]
https://github.com/apache/pinot/pull/8320

**Comment by xiangfu0** [comment]
```
Caused by: java.lang.IllegalStateException: Failed to find time field: DaysSinceEpoch from schema: null
	at com.google.common.base.Preconditions.checkState(Preconditions.java:721)
	at org.apache.pinot.segment.local.recordtransformer.NullValueTransformer.<init>(NullValueTransformer.java:61)
	at org.apache.pinot.segment.local.recordtransformer.CompositeTransformer.getDefaultTransformer(CompositeTransformer.java:62)
	at org.apache.pinot.connector.flink.sink.FlinkSegmentWriter.init(FlinkSegmentWriter.java:140)
	at org.apache.pinot.connector.flink.sink.FlinkSegmentWriter.init(FlinkSegmentWriter.java:104)
	at org.apache.pinot.connector.flink.sink.PinotSinkFunction.open(PinotSinkFunction.java:86)
	at org.apache.flink.api.common.functions.util.FunctionUtils.openFunction(FunctionUtils.java:36)
	at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.open(AbstractUdfStreamOperator.java:102)
	at org.apache.flink.streaming.api.operators.StreamSink.open(StreamSink.java:48)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.initializeStateAndOpenOperators(OperatorChain.java:401)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.lambda$beforeInvoke$2(StreamTask.java:507)
	at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$1.runThrowing(StreamTaskActionExecutor.java:47)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.beforeInvoke(StreamTask.java:501)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:531)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:722)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:547)
	at java.base/java.lang.Thread.run(Thread.java:829)
	Suppressed: java.lang.NullPointerException
		at org.apache.pinot.connector.flink.sink.PinotSinkFunction.close(PinotSinkFunction.java:105)
		at org.apache.flink.api.common.functions.util.FunctionUtils.closeFunction(FunctionUtils.java:43)
		at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.dispose(AbstractUdfStreamOperator.java:117)
		at org.apache.flink.streaming.runtime.tasks.StreamTask.disposeAllOperators(StreamTask.java:740)
		at org.apache.flink.streaming.runtime.tasks.StreamTask.runAndSuppressThrowable(StreamTask.java:720)
		at org.apache.flink.streaming.runtime.tasks.StreamTask.cleanUpInvoke(StreamTask.java:643)
		at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:552)
		... 3 more
```

**Comment by yupeng9** [comment]
interesting. I need to debug to see why it happens, but @xiangfu0 why did you close the fix PR?

**Comment by xiangfu0** [comment]
That is not the correct fix :p

**Comment by Jackie-Jiang** [comment]
@yupeng9 It failed because the table config and schema does not match with each other (#8310 added a time column check and triggered the issue). I refactored the test in #8322
