### ISSUE TITLE
boolean function not recognized in filter clause

### ISSUE THREAD

**Issue by walterddr** [apache/pinot#8487]
- `SELECT * FROM t WHERE startsWith(stringCol, 'myStr') = true`
this query works fine

- `SELECT * FROM t WHERE startsWith(stringCol, 'myStr')` 
throws exception
```
ProcessingException(errorCode:150, message:PQLParsingError:
org.apache.pinot.sql.parsers.SqlCompilationException: Unsupported filter kind: STARTSWITH
	at org.apache.pinot.sql.parsers.rewriter.PredicateComparisonRewriter.updateComparisonPredicate(PredicateComparisonRewriter.java:58)
	at org.apache.pinot.sql.parsers.rewriter.PredicateComparisonRewriter.rewrite(PredicateComparisonRewriter.java:37)
	at org.apache.pinot.sql.parsers.CalciteSqlParser.queryRewrite(CalciteSqlParser.java:413)
	at org.apache.pinot.sql.parsers.CalciteSqlParser.compileCalciteSqlToPinotQuery(CalciteSqlParser.java:407))
```

**Comment by Jackie-Jiang** [comment]
This and #8444 is the same issue and can be solved together

**Comment by walterddr** [comment]
closing duplicate with https://github.com/apache/pinot/issues/8444

**Comment by siddharthteotia** [comment]
Fixed with https://github.com/apache/pinot/pull/8518
