### ISSUE TITLE
"Failed to generate Pinot segment for file" didn't throw an exception

### ISSUE THREAD

**Issue by xingyc15** [apache/pinot#8641]
A pinot segment creation failure happened when I run a standalone script for offline ingestion. But the problem is that, this failure didn't raise any exception, but just print an error and mark the task as succeed. We are running this data ingestion as an airflow task, this missing exception pretty much delay us from debugging. Our error log is:

> [2022-04-28 00:32:33,981] {pod_launcher.py:149} INFO - Start building IndexCreator!
[2022-04-28 00:32:36,377] {pod_launcher.py:149} INFO - Failed to generate Pinot segment for file - s3://deepmap-anga-production/metrics/etl_staging/pinot_ingest/map_making_metrics/date=2022-02-22/part-0-0
[2022-04-28 00:32:36,377] {pod_launcher.py:149} INFO - shaded.com.fasterxml.jackson.core.io.JsonEOFException: Unexpected end-of-input: was expecting closing quote for a string value
[2022-04-28 00:32:36,377] {pod_launcher.py:149} INFO -  at [Source: (String)"{"extra":"[13508528,13508529,13508604,13594110,13594112,13508467,13508479,13563695,13594105,13508475,13508489,13508494,13594107,13508483,13594109]","missed":"[6900744,6900745,6900746,6900747,6900748,6900748,6900804,6900804,6900804,6900805,6900806,6901088,6901088,6901089,6901090,6901470,6908481,6908886,6911028,6911030,7647532,7647592,8062355,8062356,8062357,8062358,8062359,8062360,8062364,8062365,8062366,8091813,8091819,8091821,8091822,8091823,8091825,8091827,8091828,8091829,8091830,8091838,80918"[truncated 1000 chars]; line: 1, column: 3001]
[2022-04-28 00:32:36,377] {pod_launcher.py:149} INFO - 	at shaded.com.fasterxml.jackson.core.base.ParserMinimalBase._reportInvalidEOF(ParserMinimalBase.java:664) ~[pinot-all-0.8.0-jar-with-dependencies.jar:0.8.0-c4ceff06d21fc1c1b88469a8dbae742a4b609808]
[2022-04-28 00:32:36,377] {pod_launcher.py:149} INFO - 	at shaded.com.fasterxml.jackson.core.json.ReaderBasedJsonParser._finishString2(ReaderBasedJsonParser.java:2051) ~[pinot-all-0.8.0-jar-with-dependencies.jar:0.8.0-c4ceff06d21fc1c1b88469a8dbae742a4b609808]
[2022-04-28 00:32:36,378] {pod_launcher.py:149} INFO - 	at shaded.com.fasterxml.jackson.core.json.ReaderBasedJsonParser._finishString(ReaderBasedJsonParser.java:2038) ~[pinot-all-0.8.0-jar-with-dependencies.jar:0.8.0-c4ceff06d21fc1c1b88469a8dbae742a4b609808]
[2022-04-28 00:32:36,378] {pod_launcher.py:149} INFO - 	at shaded.com.fasterxml.jackson.core.json.ReaderBasedJsonParser.getText(ReaderBasedJsonParser.java:293) ~[pinot-all-0.8.0-jar-with-dependencies.jar:0.8.0-c4ceff06d21fc1c1b88469a8dbae742a4b609808]
[2022-04-28 00:32:36,378] {pod_launcher.py:149} INFO - 	at shaded.com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:267) ~[pinot-all-0.8.0-jar-with-dependencies.jar:0.8.0-c4ceff06d21fc1c1b88469a8dbae742a4b609808]
[2022-04-28 00:32:36,378] {pod_launcher.py:149} INFO - 	at shaded.com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:68) ~[pinot-all-0.8.0-jar-with-dependencies.jar:0.8.0-c4ceff06d21fc1c1b88469a8dbae742a4b609808]
[2022-04-28 00:32:36,378] {pod_launcher.py:149} INFO - 	at shaded.com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:15) ~[pinot-all-0.8.0-jar-with-dependencies.jar:0.8.0-c4ceff06d21fc1c1b88469a8dbae742a4b609808]
[2022-04-28 00:32:36,378] {pod_launcher.py:149} INFO - 	at shaded.com.fasterxml.jackson.databind.ObjectReader._bindAsTree(ObjectReader.java:1770) ~[pinot-all-0.8.0-jar-with-dependencies.jar:0.8.0-c4ceff06d21fc1c1b88469a8dbae742a4b609808]
[2022-04-28 00:32:36,378] {pod_launcher.py:149} INFO - 	at shaded.com.fasterxml.jackson.databind.ObjectReader._bindAndCloseAsTree(ObjectReader.java:1735) ~[pinot-all-0.8.0-jar-with-dependencies.jar:0.8.0-c4ceff06d21fc1c1b88469a8dbae742a4b609808]
[2022-04-28 00:32:36,378] {pod_launcher.py:149} INFO - 	at shaded.com.fasterxml.jackson.databind.ObjectReader.readTree(ObjectReader.java:1422) ~[pinot-all-0.8.0-jar-with-dependencies.jar:0.8.0-c4ceff06d21fc1c1b88469a8dbae742a4b609808]
[2022-04-28 00:32:36,379] {pod_launcher.py:149} INFO - 	at org.apache.pinot.spi.utils.JsonUtils.stringToJsonNode(JsonUtils.java:87) ~[pinot-all-0.8.0-jar-with-dependencies.jar:0.8.0-c4ceff06d21fc1c1b88469a8dbae742a4b609808]
[2022-04-28 00:32:36,379] {pod_launcher.py:149} INFO - 	at org.apache.pinot.segment.local.segment.creator.impl.inv.json.BaseJsonIndexCreator.add(BaseJsonIndexCreator.java:92) ~[pinot-all-0.8.0-jar-with-dependencies.jar:0.8.0-c4ceff06d21fc1c1b88469a8dbae742a4b609808]
[2022-04-28 00:32:36,379] {pod_launcher.py:149} INFO - 	at org.apache.pinot.segment.local.segment.creator.impl.SegmentColumnarIndexCreator.indexRow(SegmentColumnarIndexCreator.java:402) ~[pinot-all-0.8.0-jar-with-dependencies.jar:0.8.0-c4ceff06d21fc1c1b88469a8dbae742a4b609808]
[2022-04-28 00:32:36,379] {pod_launcher.py:149} INFO - 	at org.apache.pinot.segment.local.segment.creator.impl.SegmentIndexCreationDriverImpl.build(SegmentIndexCreationDriverImpl.java:243) ~[pinot-all-0.8.0-jar-with-dependencies.jar:0.8.0-c4ceff06d21fc1c1b88469a8dbae742a4b609808]
[2022-04-28 00:32:36,379] {pod_launcher.py:149} INFO - 	at org.apache.pinot.plugin.ingestion.batch.common.SegmentGenerationTaskRunner.run(SegmentGenerationTaskRunner.java:111) ~[pinot-all-0.8.0-jar-with-dependencies.jar:0.8.0-c4ceff06d21fc1c1b88469a8dbae742a4b609808]
[2022-04-28 00:32:36,379] {pod_launcher.py:149} INFO - 	at org.apache.pinot.plugin.ingestion.batch.standalone.SegmentGenerationJobRunner.lambda$submitSegmentGenTask$1(SegmentGenerationJobRunner.java:263) ~[pinot-batch-ingestion-standalone-0.8.0-shaded.jar:0.8.0-c4ceff06d21fc1c1b88469a8dbae742a4b609808]
[2022-04-28 00:32:36,379] {pod_launcher.py:149} INFO - 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
[2022-04-28 00:32:36,379] {pod_launcher.py:149} INFO - 	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
[2022-04-28 00:32:36,380] {pod_launcher.py:149} INFO - 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
[2022-04-28 00:32:36,380] {pod_launcher.py:149} INFO - 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
[2022-04-28 00:32:36,380] {pod_launcher.py:149} INFO - 	at java.lang.Thread.run(Unknown Source) [?:?]
[2022-04-28 00:32:36,383] {pod_launcher.py:149} INFO - Trying to create instance for class org.apache.pinot.plugin.ingestion.batch.standalone.SegmentUriPushJobRunner
[2022-04-28 00:32:36,383] {pod_launcher.py:149} INFO - Initializing PinotFS for scheme s3, classname org.apache.pinot.plugin.filesystem.S3PinotFS

Here is something I find in the source code [code](https://github.com/apache/pinot/blob/1e90f141282e40f819de806920cc2a836e0e35ba/pinot-plugins/pinot-batch-ingestion/pinot-batch-ingestion-standalone/src/main/java/org/apache/pinot/plugin/ingestion/batch/standalone/SegmentGenerationJobRunner.java#L284), I saw that this function didn't raise the exception, instead it just print an error. Can you fix this? I suppose it should raise an error and fail the process.

**Comment by Jackie-Jiang** [comment]
Thanks for reporting the issue. Can you help contribute a fix to this?
cc @xiangfu0

**Comment by Jackie-Jiang** [comment]
@kkrugler Good question. I also found that override is not properly handled when it is not allowed. Currently we only log a warning and continue.
We may support both behaviors using a `terminateOnFailure` flag:
1. If it is not set (default), we should track all the failed segment and continue. We shouldn't need to clean up the file in the `outputSegmentTarURI` because copy is the last step of the segment creation. In the end, fail the task with all the failed segments returned but keep the already generated one
2. If it is set, we should terminate immediately and clean up all the files already copied to the `outputSegmentTarURI`

wdyt?

**Comment by kkrugler** [comment]
@Jackie-Jiang - that does seem much cleaner.

When you say `fail the task with all the failed segments returned` are you saying the thrown exception should contain a message with a list of all failed segment names?

Also should the fix for override disallowed (a) be a separate issue/PR, and (b) would you expect that the job would still fail, regardless of the new `terminateOnFailure` flag? If so then that would be a change in behavior, I wonder if anyone is relying on it.

**Comment by Jackie-Jiang** [comment]
@kkrugler
IMO we should definitely fail the task if some segments are not properly generated. If we only log some warning/error but let the task succeed, very likely user will ignore them and get unexpected behavior.

To keep the behavior similar to the current behavior, we can add them in multiple PRs:
1. Track all the failed segments into a list, but keep the task running. After all the segments are processed (succeeded or failed), fail the task if there are failed segments but keep the segment files in the output dir
2. Add the flag `terminateOnFailure`, and cancel/interrupt all the remaining segments on failure
3. We may also add a flag `cleanupOnFailure` to configure whether we want to clean up the output dir when the task failed. We do need to be careful here because the output dir might contain files not generated by this task, and we should not delete them

**Comment by npawar** [comment]
@xingyc15 @kkrugler are either of you planning to pick this up?

**Comment by kkrugler** [comment]
@npawar - I was going to pick this up, but am leaving on vacation in a few hours. If it's still around when I get back next week I'll take a look.

**Comment by kkrugler** [comment]
@Jackie-Jiang - I was thinking about the `terminateOnFailure` flag a bit. The other segment generating code (Spark & Hadoop) already terminate on failure implicitly, as the task (and thus job) will fail if there's a segment generation failure. I guess there's some small value in finding out all of the segment generation failures in one pass (so not terminating on failure), but in my experience this hasn't been an issue for our Hadoop jobs, so not sure how much value is added by being able to control that behavior. And to be consistent, I think we'd need to change Hadoop & Spark code to support NOT terminating on failure if that flag isn't set, yes?

**Comment by Jackie-Jiang** [comment]
@kkrugler Agree on having the consistent behavior. I think terminating on failure by default might be the desired behavior, and we can introduce a flag to `continueOnFailure` (maybe pick a better name). We can change the standalone one to match the behavior of Hadoop & Spark

**Comment by kkrugler** [comment]
Hi @Jackie-Jiang - I can keep support for reporting multiple segment failures, and change this PR to terminate on the first failure. I think support for `cleanupOnFailure` would be next most important, and then if there's a need we could add `continueOnFailure` (and support for that in Spark/Hadoop, and I guess now Flink). LMK if you agree, thanks.

**Comment by Jackie-Jiang** [comment]
@kkrugler Sounds good. To simplify it, we can keep an AtomicReference for the failed file, and when an exception is encountered, we set the reference and drain the latch. In the main thread, we can check the reference to determine whether there is a failed file. If we do terminate on failure, logging one failed file should be good.

**Comment by kkrugler** [comment]
@Jackie-Jiang OK, updated the PR accordingly.

**Comment by kkrugler** [comment]
@Jackie-Jiang - I'm assuming this can be closed. I'll create a new issue for `cleanupOnFailure` support.
