### ISSUE TITLE
[flaky test] HelixZNodeSizeLimitTest generates huge log

### ISSUE THREAD

**Issue by walterddr** [apache/pinot#9127]
see: https://github.com/apache/pinot/actions/runs/2756316034/attempts/1
```
2022-07-28T20:06:45.6832112Z [INFO] Running org.apache.pinot.integration.tests.HelixZNodeSizeLimitTest
2022-07-28T20:07:04.1516635Z Jul 28, 2022 8:06:56 PM org.glassfish.grizzly.http.server.NetworkListener start
2022-07-28T20:07:04.1517664Z 20:06:48.058 ERROR [ZkAsyncCallbacks] [ZkClient-EventThread-25-localhost:2191] Interrupted waiting for success
2022-07-28T20:07:04.1518358Z INFO: Started listener bound to [0.0.0.0:18998]
2022-07-28T20:07:04.1518878Z Jul 28, 2022 8:06:56 PM org.glassfish.grizzly.http.server.HttpServer start
2022-07-28T20:07:04.1519346Z INFO: [HttpServer] Started.
2022-07-28T20:07:04.1519771Z Jul 28, 2022 8:06:57 PM org.glassfish.grizzly.http.server.NetworkListener start
2022-07-28T20:07:04.1520197Z INFO: Started listener bound to [0.0.0.0:18099]
2022-07-28T20:07:04.1520604Z Jul 28, 2022 8:06:57 PM org.glassfish.grizzly.http.server.HttpServer start
2022-07-28T20:07:04.1521159Z INFO: [HttpServer-1] Started.
2022-07-28T20:07:04.1521660Z Jul 28, 2022 8:07:03 PM org.glassfish.grizzly.http.server.NetworkListener start
2022-07-28T20:07:04.1522187Z INFO: Started listener bound to [0.0.0.0:8097]
2022-07-28T20:07:04.1522677Z Jul 28, 2022 8:07:03 PM org.glassfish.grizzly.http.server.HttpServer start
2022-07-28T20:07:04.1523189Z INFO: [HttpServer-2] Started.
2022-07-28T20:07:04.1525928Z java.lang.InterruptedException: null
2022-07-28T20:07:04.1526427Z 	at java.lang.Object.wait(Native Method) ~[?:?]
2022-07-28T20:07:04.1526907Z 	at java.lang.Object.wait(Object.java:328) ~[?:?]
2022-07-28T20:07:04.1528089Z 	at org.apache.helix.zookeeper.zkclient.callback.ZkAsyncCallbacks$DefaultCallback.waitForSuccess(ZkAsyncCallbacks.java:248) ~[helix-core-1.0.4.jar:1.0.4]
2022-07-28T20:07:04.1529137Z 	at org.apache.helix.zookeeper.zkclient.ZkClient.issueSync(ZkClient.java:1616) ~[helix-core-1.0.4.jar:1.0.4]
2022-07-28T20:07:04.1530231Z 	at org.apache.helix.zookeeper.zkclient.ZkClient.access$300(ZkClient.java:85) ~[helix-core-1.0.4.jar:1.0.4]
2022-07-28T20:07:04.1531237Z 	at org.apache.helix.zookeeper.zkclient.ZkClient$4.run(ZkClient.java:1642) ~[helix-core-1.0.4.jar:1.0.4]
2022-07-28T20:07:04.1532276Z 	at org.apache.helix.zookeeper.zkclient.ZkEventThread.run(ZkEventThread.java:99) ~[helix-core-1.0.4.jar:1.0.4]
2022-07-28T20:07:04.1532958Z 20:06:50.390 WARN [ServiceStartableUtils] [main] Failed to find cluster config for cluster: HelixZNodeSizeLimitTest, skipping applying cluster config
2022-07-28T20:07:04.1533561Z 20:06:51.244 WARN [ZKUtil] [main] Invalid cluster setup for cluster: zookeeper, missing znode path: /zookeeper/IDEALSTATES
2022-07-28T20:07:04.1534100Z Invalid cluster setup for cluster: zookeeper, missing znode path: /zookeeper/CONFIGS/CLUSTER/zookeeper
2022-07-28T20:07:04.1534617Z Invalid cluster setup for cluster: zookeeper, missing znode path: /zookeeper/CONFIGS/PARTICIPANT
2022-07-28T20:07:04.1535122Z Invalid cluster setup for cluster: zookeeper, missing znode path: /zookeeper/CONFIGS/RESOURCE
2022-07-28T20:07:04.1535613Z Invalid cluster setup for cluster: zookeeper, missing znode path: /zookeeper/PROPERTYSTORE
2022-07-28T20:07:04.1536223Z Invalid cluster setup for cluster: zookeeper, missing znode path: /zookeeper/LIVEINSTANCES
2022-07-28T20:07:04.1536715Z Invalid cluster setup for cluster: zookeeper, missing znode path: /zookeeper/INSTANCES
2022-07-28T20:07:04.1537197Z Invalid cluster setup for cluster: zookeeper, missing znode path: /zookeeper/EXTERNALVIEW
2022-07-28T20:07:04.1537990Z Invalid cluster setup for cluster: zookeeper, missing znode path: /zookeeper/CONTROLLER
2022-07-28T20:07:04.1538481Z Invalid cluster setup for cluster: zookeeper, missing znode path: /zookeeper/STATEMODELDEFS
2022-07-28T20:07:04.1538988Z Invalid cluster setup for cluster: zookeeper, missing znode path: /zookeeper/CONTROLLER/MESSAGES
2022-07-28T20:07:04.1539491Z Invalid cluster setup for cluster: zookeeper, missing znode path: /zookeeper/CONTROLLER/ERRORS
2022-07-28T20:07:04.1540024Z Invalid cluster setup for cluster: zookeeper, missing znode path: /zookeeper/CONTROLLER/STATUSUPDATES
2022-07-28T20:07:04.1540641Z Invalid cluster setup for cluster: zookeeper, missing znode path: /zookeeper/CONTROLLER/HISTORY
2022-07-28T20:07:04.1542656Z 
2022-07-28T20:07:04.1542926Z 20:06:51.590 WARN [ConfigAccessor] [main] No cloud config found at /HelixZNodeSizeLimitTest/CONFIGS/CLOUD/HelixZNodeSizeLimitTest.
2022-07-28T20:07:04.1543462Z 20:06:51.745 WARN [ConfigAccessor] [main] No cloud config found at /HelixZNodeSizeLimitTest/CONFIGS/CLOUD/HelixZNodeSizeLimitTest.
2022-07-28T20:07:04.1544249Z 20:06:52.069 WARN [ZkBaseDataAccessor] [ZkClient-EventThread-64-localhost:2191] Node already exists. path: /HelixZNodeSizeLimitTest/CONTROLLER/LEADER
2022-07-28T20:07:04.1545043Z 20:06:52.081 WARN [CallbackHandler] [main] Callback handler 1 received event in wrong order. Listener: org.apache.helix.messaging.handling.HelixTaskExecutor@4228f269, path: /HelixZNodeSizeLimitTest/CONTROLLER/MESSAGES, expected types: [CALLBACK, FINALIZE], but was INIT
2022-07-28T20:07:04.1545982Z 20:06:52.082 WARN [CallbackHandler] [main] Callback handler 2 received event in wrong order. Listener: org.apache.helix.controller.GenericHelixController@7534785a, path: /HelixZNodeSizeLimitTest/CONTROLLER, expected types: [CALLBACK, FINALIZE], but was INIT
2022-07-28T20:07:04.1546888Z 20:06:52.082 WARN [CallbackHandler] [main] Callback handler 3 received event in wrong order. Listener: org.apache.helix.controller.GenericHelixController@7534785a, path: /HelixZNodeSizeLimitTest/CONFIGS/PARTICIPANT, expected types: [CALLBACK, FINALIZE], but was INIT
2022-07-28T20:07:04.1547803Z 20:06:52.082 WARN [CallbackHandler] [main] Callback handler 4 received event in wrong order. Listener: org.apache.helix.controller.GenericHelixController@7534785a, path: /HelixZNodeSizeLimitTest/CONFIGS/RESOURCE, expected types: [CALLBACK, FINALIZE], but was INIT
2022-07-28T20:07:04.1548746Z 20:06:52.082 WARN [CallbackHandler] [main] Callback handler 5 received event in wrong order. Listener: org.apache.helix.controller.GenericHelixController@7534785a, path: /HelixZNodeSizeLimitTest/CONFIGS/CLUSTER/HelixZNodeSizeLimitTest, expected types: [CALLBACK, FINALIZE], but was INIT
2022-07-28T20:07:04.1549859Z 20:06:52.082 WARN [CallbackHandler] [main] Callback handler 6 received event in wrong order. Listener: org.apache.helix.controller.GenericHelixController@7534785a, path: /HelixZNodeSizeLimitTest/CONFIGS/CUSTOMIZED_STATE/HelixZNodeSizeLimitTest, expected types: [CALLBACK, FINALIZE], but was INIT
2022-07-28T20:07:04.1550813Z 20:06:52.082 WARN [CallbackHandler] [main] Callback handler 7 received event in wrong order. Listener: org.apache.helix.controller.GenericHelixController@7534785a, path: /HelixZNodeSizeLimitTest/LIVEINSTANCES, expected types: [CALLBACK, FINALIZE], but was INIT
2022-07-28T20:07:04.1551707Z 20:06:52.082 WARN [CallbackHandler] [main] Callback handler 8 received event in wrong order. Listener: org.apache.helix.controller.GenericHelixController@7534785a, path: /HelixZNodeSizeLimitTest/IDEALSTATES, expected types: [CALLBACK, FINALIZE], but was INIT
2022-07-28T20:07:04.1552382Z 20:06:52.128 WARN [ZKUtil] [main] Invalid cluster setup for cluster: zookeeper, missing znode path: /zookeeper/IDEALSTATES
2022-07-28T20:07:04.1552917Z Invalid cluster setup for cluster: zookeeper, missing znode path: /zookeeper/CONFIGS/CLUSTER/zookeeper
2022-07-28T20:07:04.1553368Z Invalid cluster setup for cluster: zookeeper, missing znode path: /zookeeper/CONFIGS/PARTICIPANT
2022-07-28T20:07:04.1553786Z Invalid cluster setup for cluster: zookeeper, missing znode path: /zookeeper/CONFIGS/RESOURCE
2022-07-28T20:07:04.1554209Z Invalid cluster setup for cluster: zookeeper, missing znode path: /zookeeper/PROPERTYSTORE
2022-07-28T20:07:04.1554630Z Invalid cluster setup for cluster: zookeeper, missing znode path: /zookeeper/LIVEINSTANCES
2022-07-28T20:07:04.1555033Z Invalid cluster setup for cluster: zookeeper, missing znode path: /zookeeper/INSTANCES
2022-07-28T20:07:04.1555438Z Invalid cluster setup for cluster: zookeeper, missing znode path: /zookeeper/EXTERNALVIEW
2022-07-28T20:07:04.1555851Z Invalid cluster setup for cluster: zookeeper, missing znode path: /zookeeper/CONTROLLER
2022-07-28T20:07:04.1556274Z Invalid cluster setup for cluster: zookeeper, missing znode path: /zookeeper/STATEMODELDEFS
2022-07-28T20:07:04.1556690Z Invalid cluster setup for cluster: zookeeper, missing znode path: /zookeeper/CONTROLLER/MESSAGES
2022-07-28T20:07:04.1557120Z Invalid cluster setup for cluster: zookeeper, missing znode path: /zookeeper/CONTROLLER/ERRORS
2022-07-28T20:07:04.1557559Z Invalid cluster setup for cluster: zookeeper, missing znode path: /zookeeper/CONTROLLER/STATUSUPDATES
2022-07-28T20:07:04.1558000Z Invalid cluster setup for cluster: zookeeper, missing znode path: /zookeeper/CONTROLLER/HISTORY
2022-07-28T20:07:04.1558234Z 
2022-07-28T20:07:04.1558487Z 20:06:52.186 WARN [ConfigAccessor] [main] No config found at /HelixZNodeSizeLimitTest/CONFIGS/RESOURCE/leadControllerResource.
2022-07-28T20:07:04.1559467Z 20:06:52.425 WARN [TopStateHandoffReportStage] [HelixController-pipeline-default-HelixZNodeSizeLimitTest-(8e519abe_DEFAULT)] Event 8e519abe_DEFAULT : Cannot confirm top state missing start time. Use the current system time as the start time.
```
The last message kees going for more than 500,000 lines

afterwards all following tests are getting flaky results.

**Comment by walterddr** [comment]
@jackjlli ^ any idea? this has been happening more and more often lately

**Comment by walterddr** [comment]
https://github.com/apache/pinot/runs/7791177184?check_suite_focus=true
https://github.com/apache/pinot/runs/7790179872?check_suite_focus=true
