### ISSUE TITLE
Pinot quickstart issue with "Load data into Kafka and create Pinot schema/tables"

### ISSUE THREAD

**Issue by amitoj** [apache/pinot#9284]
Following the guide from [kubernetes-quickstart](https://docs.pinot.apache.org/basics/getting-started/kubernetes-quickstart#3.4-load-data-into-kafka-and-create-pinot-schema-tables)

When I run the jobs in section "Load data into Kafka and create Pinot schema/tables" 
`kubectl apply -f pinot/pinot-realtime-quickstart.yml
`

The job container 'pinot-add-example-realtime-table-avro' fails with error
```
2022/08/26 14:32:20.484 INFO [AddTableCommand] [main] Executing command: AddTable -tableConfigFile /var/pinot/examples/airlineStatsAvro_realtime_table_config.json -schemaFile /var/pinot/examples/airlineStats_schema.json -controllerProtocol http -controllerHost pinot-controller -controllerPort 9000 -user null -password [hidden] -exec
2022/08/26 14:32:21.130 INFO [AddTableCommand] [main] {"code":400,"error":"Invalid TableConfigs. Invalid TableConfigs: airlineStatsAvro. 'tableName': airlineStatsAvro must be equal to 'schemaName' from 'schema': airlineStats"}
``` 

Also, there are errors in the other job Pod

Pod - pinot-realtime-quickstart-load-data-into-kafka-xxxxx
Container - loading-json-data-to-kafka

```
java.lang.RuntimeException: java.io.FileNotFoundException: examples/stream/airlineStats/sample_data/airlineStats_data.avro (No such file or directory)
	at org.apache.pinot.tools.admin.command.StreamAvroIntoKafkaCommand.execute(StreamAvroIntoKafkaCommand.java:157)
	at org.apache.pinot.tools.Command.call(Command.java:33)
	at org.apache.pinot.tools.Command.call(Command.java:29)
        ...
Caused by: java.io.FileNotFoundException: examples/stream/airlineStats/sample_data/airlineStats_data.avro (No such file or directory)
	at org.apache.pinot.plugin.inputformat.avro.AvroUtils.getAvroReader(AvroUtils.java:220)
	at org.apache.pinot.tools.admin.command.StreamAvroIntoKafkaCommand.execute(StreamAvroIntoKafkaCommand.java:127)
```

And, Container - loading-avro-data-to-kafka

```
java.lang.RuntimeException: java.io.FileNotFoundException: examples/stream/airlineStats/sample_data/airlineStats_data.avro (No such file or directory)
	at org.apache.pinot.tools.admin.command.StreamAvroIntoKafkaCommand.execute(StreamAvroIntoKafkaCommand.java:157)
        ...
Caused by: java.io.FileNotFoundException: examples/stream/airlineStats/sample_data/airlineStats_data.avro (No such file or directory)
        ....
```

It seems like this script is not updated after refactoring of example files

**Comment by liyujiel** [comment]
I believe https://github.com/apache/pinot/pull/9562 can fix this issue :)
