### ISSUE TITLE
[multistage] Query Fails When Using IN Clause With String Args

### ISSUE THREAD

**Issue by ankitsultana** [apache/pinot#9345]
Repro query (issue happens when using IN clause with string arguments in the filters):

```
SELECT a.playerID, a.runs, a.yearID, b.runs, b.yearID
        FROM baseballStats_OFFLINE AS a JOIN baseballStats_OFFLINE AS b ON a.playerID = b.playerID
        WHERE a.runs > 160 AND b.teamID IN ('SFN')
```

The broker throws this error:

```
QueryExecutionError:\nio.grpc.StatusRuntimeException: INVALID_ARGUMENT: Bad request
```

The actual error happens in the server:

```
Caused by: java.lang.InstantiationException: org.apache.calcite.util.NlsString
        at java.lang.Class.newInstance(Class.java:571) ~[?:?]
        at org.apache.pinot.query.planner.serde.ProtoSerializationUtils.constructObject(ProtoSerializationUtils.java:237)
        ... 25 more
Caused by: java.lang.NoSuchMethodException: org.apache.calcite.util.NlsString.<init>()
        at java.lang.Class.getConstructor0(Class.java:3349) ~[?:?]
        at java.lang.Class.newInstance(Class.java:556) ~[?:?]
        at org.apache.pinot.query.planner.serde.ProtoSerializationUtils.constructObject(ProtoSerializationUtils.java:237)
        ... 25 more
```

cc: @walterddr

**Comment by ankitsultana** [comment]
Sounds good. Will give it a shot.
