### ISSUE TITLE
Error messages while launching Quickstart

### ISSUE THREAD

**Issue by amrishlal** [apache/pinot#9395]
Seeing these error messages while launching Quickstart. After this query does not execute in the quickstart console.

```
Caused by: java.net.ConnectException: Operation timed out (Connection timed out)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:?]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399) ~[?:?]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242) ~[?:?]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403) ~[?:?]
	at java.net.Socket.connect(Socket.java:609) ~[?:?]
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.pinot.common.utils.http.HttpClient.sendRequest(HttpClient.java:276) ~[classes/:?]
	at org.apache.pinot.common.utils.FileUploadDownloadClient.uploadSegment(FileUploadDownloadClient.java:711) ~[classes/:?]
	at org.apache.pinot.segment.local.utils.SegmentPushUtils.lambda$pushSegments$0(SegmentPushUtils.java:131) ~[classes/:?]
	at org.apache.pinot.spi.utils.retry.BaseRetryPolicy.attempt(BaseRetryPolicy.java:50) ~[classes/:?]
	at org.apache.pinot.segment.local.utils.SegmentPushUtils.pushSegments(SegmentPushUtils.java:128) ~[classes/:?]
	at org.apache.pinot.plugin.minion.tasks.segmentgenerationandpush.SegmentGenerationAndPushTaskExecutor.pushSegment(SegmentGenerationAndPushTaskExecutor.java:172) ~[classes/:?]
	at org.apache.pinot.plugin.minion.tasks.segmentgenerationandpush.SegmentGenerationAndPushTaskExecutor.generateAndPushSegment(SegmentGenerationAndPushTaskExecutor.java:144) ~[classes/:?]
	at org.apache.pinot.plugin.minion.tasks.segmentgenerationandpush.SegmentGenerationAndPushTaskExecutor.executeTask(SegmentGenerationAndPushTaskExecutor.java:118) ~[classes/:?]

```

```
2022/09/13 17:15:50.130 ERROR [MessageGenerationPhase] [HelixController-pipeline-default-QuickStartCluster-(4e66b11c_DEFAULT)] Event 4e66b11c_DEFAULT : Unable to find a next state for resource: airlineStats_OFFLINE partition: airlineStats_OFFLINE_16071_16071_0 from stateModelDefinitionclass org.apache.helix.model.StateModelDefinition from:ERROR to:ONLINE
```

**Comment by xiangfu0** [comment]
How do you run the QuickStart? OSS release or you build it locally or from IDE? Can you provide more information. Also check if there is any port conflict from your local server

**Comment by amrishlal** [comment]
I usually kill all the java processes to resolve port conflict issues, but in this case that didn't seem to work. Although, its working now. If it happens again, I will try to record more info. I ran it in IntelliJ (Quickstart.java -> Right click -> Run) on latest master.

**Comment by kkrugler** [comment]
Hi @amrishlal - this is a good question for the troubleshooting channel in the Pinot Slack workspace. Then, if after discussion it seems like a Pinot issue (vs. your environment, for example) you would open a GitHub issue.

**Comment by npawar** [comment]
Closing this, as it is not an issue anymore or reproducible
