### ISSUE TITLE
[multistage] table aliasing doesn't work with SELECT *

### ISSUE THREAD

**Issue by agavra** [apache/pinot#9904]
## Scenario A

<img width="1328" alt="Screen Shot 2022-12-02 at 1 26 17 PM" src="https://user-images.githubusercontent.com/3172405/205389930-f76dfdfc-391f-4713-9ed8-8e73778a9db4.png">

## Scenario B

<img width="1327" alt="image" src="https://user-images.githubusercontent.com/3172405/205390041-876fbbf2-49b7-4d66-95d1-662cc554e00f.png">

## NOTE

this may be a regression as it doesn't seem to be an issue on our staging clusters

## ResourceBasedQueriesTest

I cannot reproduce this in the `ResourceBasedQueriesTest` as the following queries work:

```json
      {
        "description": "basic test case example",
        "sql": "SELECT * FROM {tbl} xyz"
      },
      {
        "description": "basic test case example",
        "sql": "SELECT xyz.col1, xyz.col2 FROM {tbl} xyz"
      }
```

**Comment by agavra** [comment]
I see the following in the logs:

```
2022/12/02 13:25:40.861 ERROR [MailboxSendOperator] [query_worker_on_8842_port-1-thread-8] Exception occur while sending data via mailbox
java.lang.RuntimeException: Unable to create DataBlock
	at org.apache.pinot.query.runtime.blocks.TransferableBlock.getDataBlock(TransferableBlock.java:117) ~[pinot-all-0.12.0-SNAPSHOT-jar-with-dependencies.jar:0.12.0-SNAPSHOT-2f640ff8683728b844be9e045d5ce0f026d09e71]
	at org.apache.pinot.query.runtime.blocks.TransferableBlockUtils.splitBlock(TransferableBlockUtils.java:73) ~[pinot-all-0.12.0-SNAPSHOT-jar-with-dependencies.jar:0.12.0-SNAPSHOT-2f640ff8683728b844be9e045d5ce0f026d09e71]
	at org.apache.pinot.query.runtime.operator.MailboxSendOperator.sendDataTableBlockToServers(MailboxSendOperator.java:207) ~[pinot-all-0.12.0-SNAPSHOT-jar-with-dependencies.jar:0.12.0-SNAPSHOT-2f640ff8683728b844be9e045d5ce0f026d09e71]
	at org.apache.pinot.query.runtime.operator.MailboxSendOperator.getNextBlock(MailboxSendOperator.java:146) [pinot-all-0.12.0-SNAPSHOT-jar-with-dependencies.jar:0.12.0-SNAPSHOT-2f640ff8683728b844be9e045d5ce0f026d09e71]
	at org.apache.pinot.query.runtime.operator.MailboxSendOperator.getNextBlock(MailboxSendOperator.java:50) [pinot-all-0.12.0-SNAPSHOT-jar-with-dependencies.jar:0.12.0-SNAPSHOT-2f640ff8683728b844be9e045d5ce0f026d09e71]
	at org.apache.pinot.core.operator.BaseOperator.nextBlock(BaseOperator.java:39) [pinot-all-0.12.0-SNAPSHOT-jar-with-dependencies.jar:0.12.0-SNAPSHOT-2f640ff8683728b844be9e045d5ce0f026d09e71]
	at org.apache.pinot.query.runtime.executor.WorkerQueryExecutor$1.runJob(WorkerQueryExecutor.java:84) [pinot-all-0.12.0-SNAPSHOT-jar-with-dependencies.jar:0.12.0-SNAPSHOT-2f640ff8683728b844be9e045d5ce0f026d09e71]
	at org.apache.pinot.core.util.trace.TraceRunnable.run(TraceRunnable.java:40) [pinot-all-0.12.0-SNAPSHOT-jar-with-dependencies.jar:0.12.0-SNAPSHOT-2f640ff8683728b844be9e045d5ce0f026d09e71]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.ClassCastException
```

**Comment by agavra** [comment]
nevermind - this happens because MV columns aren't supported
